force-app/main/default/objects/Assessment_Question__c/fields/Answer_Choice__c.field-meta.xml
<CustomField>
    <fullName>Answer_Choice__c</fullName>
    <label>Answer Choice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Question__c/fields/Answer_Number__c.field-meta.xml
<CustomField>
    <fullName>Answer_Number__c</fullName>
    <label>Answer (Number)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment_Question__c/fields/Answer_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Answer_Picklist__c</fullName>
    <label>Answer (Picklist)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment_Question__c/fields/Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>Answer_Type__c</fullName>
    <label>Answer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
                <default>true</default>
                <label>Picklist</label>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>True/False</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Question__c/fields/Assessment_Question_Master__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Question_Master__c</fullName>
    <label>Assessment Question Master</label>
    <referenceTo>Ass_Ques_Master__c</referenceTo>
    <relationshipLabel>Assessment Questions</relationshipLabel>
    <relationshipName>Assessment_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Question__c/fields/Expected_Answer__c.field-meta.xml
<CustomField>
    <fullName>Expected_Answer__c</fullName>
    <label>Expected Answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Applied_by__c.field-meta.xml
<CustomField>
    <fullName>Applied_by__c</fullName>
    <formula>Contact__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applied by</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Master_Name__c</fullName>
    <formula>Course_Master__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Master Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <formula>Course_Master__r.Thumbnail_URL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Image URL of Course Master</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Test_Master__c.field-meta.xml
<CustomField>
    <fullName>Test_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Master</label>
    <referenceTo>Test_Master__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Test_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Type__c</fullName>
    <formula>TEXT( Test_Master__r.Test_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Total_Marks_Obtained__c.field-meta.xml
<CustomField>
    <fullName>Total_Marks_Obtained__c</fullName>
    <label>Total Marks Obtained</label>
    <summarizedField>Student_Assessment_Result__c.Marks__c</summarizedField>
    <summaryForeignKey>Student_Assessment_Result__c.Student_Test_Association__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Total_Questions__c.field-meta.xml
<CustomField>
    <fullName>Total_Questions__c</fullName>
    <description>display total number of questions</description>
    <label>Total Questions</label>
    <summaryForeignKey>Student_Assessment_Result__c.Student_Test_Association__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/Assessment_Question_Master__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Question_Master__c</fullName>
    <label>Assessment Question Master</label>
    <referenceTo>Ass_Ques_Master__c</referenceTo>
    <relationshipLabel>Test Masters</relationshipLabel>
    <relationshipName>Test_Masters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>Test Masters</relationshipLabel>
    <relationshipName>Test_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Test Masters</relationshipLabel>
    <relationshipName>Test_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/Test_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Type__c</fullName>
    <label>Test Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetEnrollmentAndRelatedSTAwithQuestion.cls
@RestResource(urlMapping='/v1/Course_Enrollment__c/*')
global class GetEnrollmentAndRelatedSTAwithQuestion {
    @HttpGet
    global static StudentsEnrollementAndAssementQuestionswrapper getAssessmentQuestionForCEofStudent() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        Map<String,String> paramsMap = RestContext.request.params;
        String studentId = paramsMap.get('id'); 						
        List<Course_Enrollment__c> courseEnrollmentOfStudent = new List<Course_Enrollment__c>();
        List<Student_Test_Association__c> STAofStudent = new List<Student_Test_Association__c>();
        set<Id> testMasterIds = new Set<Id>();
        set<id> assessmentQuestionMasterId = new set<Id>();
        set<id> assessmentQuestionMasterIdOfModuleTest = new set<Id>();
        Map<String,String> testTypeByTestMasterId = new Map<String,String>(); 
        Map<String,String> testMasterByAssmentQuestionMaster = new Map<String,String>(); 
        Map<Id, Test_Master__c> testMasterMapById = new Map<Id, Test_Master__c>();
        Map<string, List<Assessment_Question__c>> assessmentQuestionsByTestName = new Map<string, List<Assessment_Question__c>>();
        List<Assessment_Question__c> assessmentQuestionList = new List<Assessment_Question__c>();
        Map<String, Course_Enrollment__c> courseEnrollmentByTestType = new Map<String, Course_Enrollment__c>();
        
        if(studentId != ''){
            courseEnrollmentOfStudent = [Select id,Name,Course_Master_Name__c,Applied_by__c,Contact__c,Course_Master__c,Image_URL__c,(Select Id,Contact__c,CE_Module__c,Course_Enrollment__c,Test_Master__c,Test_Master__r.Test_Type__c,Test_Master__r.CE_Module__r.Name,Status__c,Total_Marks_Obtained__c,Total_Questions__c From Student_Test_Associations__r Where Status__c = 'Pending') From Course_Enrollment__c Where Contact__c =:studentId ];
        }
        if(!courseEnrollmentOfStudent.isEmpty()){
            for(Course_Enrollment__c studentsCourseEnrollment : courseEnrollmentOfStudent){
                for(Student_Test_Association__c STARec : studentsCourseEnrollment.Student_Test_Associations__r){
                    testMasterIds.add(STARec.Test_Master__c);
                    if(STARec.Test_Master__r.Test_Type__c == 'Module'){
                        testTypeByTestMasterId.put(STARec.Test_Master__c, STARec.Test_Master__r.CE_Module__r.Name);
                    }
                    else if(STARec.Test_Master__r.Test_Type__c == 'Pre' || STARec.Test_Master__r.Test_Type__c == 'Post'){
                        testTypeByTestMasterId.put(STARec.Test_Master__c, STARec.Test_Master__r.Test_Type__c);
                    }
                }
            }
        }
        if(!testMasterIds.isEmpty()){
            testMasterMapById = new Map<Id, Test_Master__c>([Select id,Name,Assessment_Question_Master__c,Test_Type__c,CE_Module__c From Test_Master__c Where Id in : testMasterIds]);
        }
        if(!testMasterMapById.isEmpty()){
            for(Test_Master__c testMasterRec : testMasterMapById.values()){
                assessmentQuestionMasterId.add(testMasterRec.Assessment_Question_Master__c);
                testMasterByAssmentQuestionMaster.put(testMasterRec.Assessment_Question_Master__c, testMasterRec.Id);
            }
        }
        if(!assessmentQuestionMasterId.isEmpty()){
            assessmentQuestionList = [SELECT Answer_Choice__c,Answer_Number__c,Answer_Picklist__c,Answer_Type__c,Assessment_Question_Master__c,Category__c,Expected_Answer__c,Id,Name,Question__c FROM Assessment_Question__c WHERE Assessment_Question_Master__c in : assessmentQuestionMasterId];
        }
        
        if(!assessmentQuestionList.isEmpty()){
            for(Assessment_Question__c assessmentQuestion : assessmentQuestionList){
                if(assessmentQuestionsByTestName.containsKey(testTypeByTestMasterId.get(testMasterByAssmentQuestionMaster.get(assessmentQuestion.Assessment_Question_Master__c)))){
                    List<Assessment_Question__c> questionToBEAdded = assessmentQuestionsByTestName.get(testTypeByTestMasterId.get(testMasterByAssmentQuestionMaster.get(assessmentQuestion.Assessment_Question_Master__c)));
                    questionToBEAdded.add(assessmentQuestion);
                    assessmentQuestionsByTestName.put(testTypeByTestMasterId.get(testMasterByAssmentQuestionMaster.get(assessmentQuestion.Assessment_Question_Master__c)), questionToBEAdded );
                }else{
                    assessmentQuestionsByTestName.put(testTypeByTestMasterId.get(testMasterByAssmentQuestionMaster.get(assessmentQuestion.Assessment_Question_Master__c)), new List<Assessment_Question__c>{ assessmentQuestion } );
                }
            }
        }
        StudentsEnrollementAndAssementQuestionswrapper wrapperInstance = new StudentsEnrollementAndAssementQuestionswrapper(courseEnrollmentOfStudent , assessmentQuestionsByTestName);        
        return wrapperInstance;
    }
    
    global class StudentsEnrollementAndAssementQuestionswrapper {
        global List<Course_Enrollment__c> courseEnrollmentsOfStudent;
        global Map<string, List<Assessment_Question__c>> assessmentQuestionsByTestName;
        
        global StudentsEnrollementAndAssementQuestionswrapper(List<Course_Enrollment__c> courseEnrollmentsOfStudent, Map<string, List<Assessment_Question__c>> assessmentQuestionsByTestName){
            this.courseEnrollmentsOfStudent = courseEnrollmentsOfStudent;
            this.assessmentQuestionsByTestName = assessmentQuestionsByTestName;
        }
    }
}