force-app/main/default/objects/Assessment_Question__c/fields/Answer_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Answer_Picklist__c</fullName>
    <label>Answer (Picklist)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment_Question__c/fields/Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>Answer_Type__c</fullName>
    <label>Answer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
                <default>true</default>
                <label>Picklist</label>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>True/False</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Question__c/fields/Assessment_Question_Master__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Question_Master__c</fullName>
    <label>Assessment Question Master</label>
    <referenceTo>Ass_Ques_Master__c</referenceTo>
    <relationshipLabel>Assessment Questions</relationshipLabel>
    <relationshipName>Assessment_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Question__c/fields/Expected_Answer__c.field-meta.xml
<CustomField>
    <fullName>Expected_Answer__c</fullName>
    <label>Expected Answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Test_Master__c.field-meta.xml
<CustomField>
    <fullName>Test_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Master</label>
    <referenceTo>Test_Master__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Total_Marks_Obtained__c.field-meta.xml
<CustomField>
    <fullName>Total_Marks_Obtained__c</fullName>
    <label>Total Marks Obtained</label>
    <summarizedField>Student_Assessment_Result__c.Marks__c</summarizedField>
    <summaryForeignKey>Student_Assessment_Result__c.Student_Test_Association__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Total_Questions__c.field-meta.xml
<CustomField>
    <fullName>Total_Questions__c</fullName>
    <description>display total number of questions</description>
    <label>Total Questions</label>
    <summaryForeignKey>Student_Assessment_Result__c.Student_Test_Association__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/Assessment_Question_Master__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Question_Master__c</fullName>
    <label>Assessment Question Master</label>
    <referenceTo>Ass_Ques_Master__c</referenceTo>
    <relationshipLabel>Test Masters</relationshipLabel>
    <relationshipName>Test_Masters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>Test Masters</relationshipLabel>
    <relationshipName>Test_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GetCEModuleTest.cls
@RestResource(urlMapping='/v1/CE_Module__c/*')
global with sharing class GetCEModuleTest {
    @HttpGet
    global static MentorshipServiceModels.CEModuleQuestionAndSTAWrapper getAssessmentQuestionForCEModules() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        Map<String,String> paramsMap = RestContext.request.params;
        String CEModuleId = paramsMap.get('id'); // 'a0p6D000000llObQAI'
        
        //system.debug('CEModuleId::'+CEModuleId);
        set<Id> assessmentQuestionMasterId = new Set<Id>();
        Map<String, String> assessmentQuestionMasterIdByCEMOduleId = new Map<String, String>();
        Map<String, List<Assessment_Question__c>> assessmentQuestionsByAssessmentQuestionMasterId = new Map<String, List<Assessment_Question__c>>();
        Map<String, List<Assessment_Question__c>> assessmentQuestionByCEModuleId = new Map<String, List<Assessment_Question__c>>(); 
        List<Test_Master__c> TestMasterList = [SELECT Assessment_Question_Master__c,CE_Module__c  FROM Test_Master__c WHERE CE_Module__c = :  CEModuleId];
        List<Assessment_Question__c> assessmentQuestionToBeReturned = new List<Assessment_Question__c>();
        List<Assessment_Question__c> assessmentQuestionList = new List<Assessment_Question__c>();
        
        if(!TestMasterList.isEmpty()){
            for(Test_Master__c testMasterRec : TestMasterList){
                assessmentQuestionMasterIdByCEMOduleId.put(testMasterRec.CE_Module__c, testMasterRec.Assessment_Question_Master__c);
                assessmentQuestionMasterId.add(testMasterRec.Assessment_Question_Master__c);
            }  
        }
        //system.debug('assessmentQuestionMasterIdByCEMOduleId::'+assessmentQuestionMasterIdByCEMOduleId);
        //system.debug('assessmentQuestionMasterId::'+assessmentQuestionMasterId);
        if(!assessmentQuestionMasterId.isEmpty()){
            assessmentQuestionList = [SELECT Assessment_Question_Master__c,Question__c,Answer_Type__c,Answer_Picklist__c,Expected_Answer__c,Category__c FROM Assessment_Question__c Where Assessment_Question_Master__c in : assessmentQuestionMasterId];
        }
        //system.debug('assessmentQuestionList::'+assessmentQuestionList);
        if(!assessmentQuestionList.isEmpty()){
            for(Assessment_Question__c questionRec : assessmentQuestionList){
                
                if(assessmentQuestionsByAssessmentQuestionMasterId.containsKey(questionRec.Assessment_Question_Master__c)){
                    List<Assessment_Question__c> questionsToBeAdded = assessmentQuestionsByAssessmentQuestionMasterId.get(questionRec.Assessment_Question_Master__c);
                    questionsToBeAdded.add(questionRec);
                    assessmentQuestionsByAssessmentQuestionMasterId.put(questionRec.Assessment_Question_Master__c, questionsToBeAdded);
                }
                else{
                    assessmentQuestionsByAssessmentQuestionMasterId.put(questionRec.Assessment_Question_Master__c, new List<Assessment_Question__c>{questionRec});
                }
            }
        }
        //system.debug('assessmentQuestionsByAssessmentQuestionMasterId::'+assessmentQuestionsByAssessmentQuestionMasterId);
        if(!assessmentQuestionMasterIdByCEMOduleId.isEmpty()){
            for(String IdOfCEModule : assessmentQuestionMasterIdByCEMOduleId.keyset()){
                assessmentQuestionByCEModuleId.put(IdOfCEModule,assessmentQuestionsByAssessmentQuestionMasterId.get(assessmentQuestionMasterIdByCEMOduleId.get(IdOfCEModule)));
            }
        }
        //system.debug('assessmentQuestionByCEModuleId::'+assessmentQuestionByCEModuleId);
        if(!assessmentQuestionByCEModuleId.isEmpty()){
            for(String idOfCEModule : assessmentQuestionByCEModuleId.keyset()){
                if(idOfCEModule == CEModuleId){
                    assessmentQuestionToBeReturned = assessmentQuestionByCEModuleId.get(idOfCEModule);
                }
            }
        }
        //system.debug('assessmentQuestionToBeReturned::'+assessmentQuestionToBeReturned);
        
        List<Student_Test_Association__c> StudentTestAssociationList = [Select Id,Contact__c,CE_Module__c,Course_Enrollment__c,Total_Questions__c,Total_Marks_Obtained__c,Test_Master__c,Status__c From Student_Test_Association__c Where CE_Module__c = : CEModuleId AND Test_Master__c != null ];
        MentorshipServiceModels.CEModuleQuestionAndSTAWrapper wrapperInstance = new MentorshipServiceModels.CEModuleQuestionAndSTAWrapper(StudentTestAssociationList, assessmentQuestionToBeReturned);
        
        return wrapperInstance;
    } 
   
}