force-app/main/default/objects/Assessment_Question__c/fields/Answer_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Answer_Picklist__c</fullName>
    <label>Answer (Picklist)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment_Question__c/fields/Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>Answer_Type__c</fullName>
    <label>Answer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
                <default>true</default>
                <label>Picklist</label>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>True/False</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Question__c/fields/Assessment_Question_Master__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Question_Master__c</fullName>
    <label>Assessment Question Master</label>
    <referenceTo>Ass_Ques_Master__c</referenceTo>
    <relationshipLabel>Assessment Questions</relationshipLabel>
    <relationshipName>Assessment_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Question__c/fields/Expected_Answer__c.field-meta.xml
<CustomField>
    <fullName>Expected_Answer__c</fullName>
    <label>Expected Answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Result_Category__c/fields/Percentage_Obtained__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Obtained__c</fullName>
    <formula>( Right_Answered_Ques__c  /  Total_Questions__c ) * 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percentage Obtained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Result_Category__c/fields/Right_Answered_Ques__c.field-meta.xml
<CustomField>
    <fullName>Right_Answered_Ques__c</fullName>
    <label>Right Answered Questions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Result_Category__c/fields/Student_Test_Association__c.field-meta.xml
<CustomField>
    <fullName>Student_Test_Association__c</fullName>
    <label>Student Test Association</label>
    <referenceTo>Student_Test_Association__c</referenceTo>
    <relationshipLabel>Result Categories</relationshipLabel>
    <relationshipName>Result_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Result_Category__c/fields/Total_Questions__c.field-meta.xml
<CustomField>
    <fullName>Total_Questions__c</fullName>
    <label>Total Questions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student_Assessment_Result__c/fields/Assessment_Question__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Question</label>
    <referenceTo>Assessment_Question__c</referenceTo>
    <relationshipLabel>Student Assessment Results</relationshipLabel>
    <relationshipName>Student_Assessment_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Assessment_Result__c/fields/Marks__c.field-meta.xml
<CustomField>
    <fullName>Marks__c</fullName>
    <label>Marks</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student_Assessment_Result__c/fields/Que_Category__c.field-meta.xml
<CustomField>
    <fullName>Que_Category__c</fullName>
    <label>Que Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Assessment_Result__c/fields/Student_Test_Association__c.field-meta.xml
<CustomField>
    <fullName>Student_Test_Association__c</fullName>
    <label>Student Test Association</label>
    <referenceTo>Student_Test_Association__c</referenceTo>
    <relationshipLabel>Student Assessment Results</relationshipLabel>
    <relationshipName>Student_Assessment_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Test_Master__c.field-meta.xml
<CustomField>
    <fullName>Test_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Master</label>
    <referenceTo>Test_Master__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Test_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Type__c</fullName>
    <formula>TEXT( Test_Master__r.Test_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Total_Questions__c.field-meta.xml
<CustomField>
    <fullName>Total_Questions__c</fullName>
    <description>display total number of questions</description>
    <label>Total Questions</label>
    <summaryForeignKey>Student_Assessment_Result__c.Student_Test_Association__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/Assessment_Question_Master__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Question_Master__c</fullName>
    <label>Assessment Question Master</label>
    <referenceTo>Ass_Ques_Master__c</referenceTo>
    <relationshipLabel>Test Masters</relationshipLabel>
    <relationshipName>Test_Masters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/Test_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Type__c</fullName>
    <label>Test Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetQuestionsForGenericTest.cls
@RestResource(urlMapping='/v1/generic_Test_Questions/*')
global class GetQuestionsForGenericTest {
    @HttpGet
    global static MentorshipServiceModels.result doGetQuestions() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        Map<String,String> paramsMap = RestContext.request.params;
        String contactId = paramsMap.get('id');
        // contactId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        system.debug('contactId::'+contactId);
        
        MentorshipServiceModels.result wrapInstance = new MentorshipServiceModels.result();
        List<Assessment_Question__c> questionsList = new List<Assessment_Question__c> ();
        List<Result_Category__c> categoryResultList = new List<Result_Category__c>();
        List<Student_Assessment_Result__c> studentAssessmentResultList = new List<Student_Assessment_Result__c>();
        
        if(!string.isBlank(contactId)){
            List<Student_Test_Association__c> staRecList = [SELECT Id,Status__C FROM Student_Test_Association__c WHERE Contact__c =: contactId AND Test_Type__c = 'Generic' limit 1];
            if(!staRecList.isEmpty()){
                wrapInstance.studentTestAssociationid = staRecList[0].id;
                if(staRecList[0].Status__c == 'Pending' || staRecList[0].Status__c == null){
                    String testMasterId = [SELECT Test_Master__c FROM Student_Test_Association__c WHERE Contact__c =: contactId AND Test_Type__c = 'Generic'].Test_Master__c;
                    String assQuestionMasterID = [SELECT Assessment_Question_Master__c FROM Test_Master__c WHERE Id =: testMasterId].Assessment_Question_Master__c;
                    questionsList = [SELECT Question__c,Category__c,Expected_Answer__c,Answer_Picklist__c,Answer_Type__c,id From Assessment_Question__c WHERE Assessment_Question_Master__c =: assQuestionMAsterID];
                }else{
                    studentAssessmentResultList = [SELECT Answer__c,Assessment_Question__c,Marks__c,Question__c,Que_Category__c FROM Student_Assessment_Result__c WHERE Student_Test_Association__c =: staRecList[0].Id];
                    categoryResultList = [SELECT Name,Percentage_Obtained__c,Right_Answered_Ques__c,Total_Questions__c FROM Result_Category__c WHERE Student_Test_Association__c =: staRecList[0].Id];
                }
            }
        }
        wrapInstance.categoryResultList = categoryResultList;
        wrapInstance.questionsList = questionsList;
        wrapInstance.studentAssessmentResultList = studentAssessmentResultList;
        
        return wrapInstance;
    }    
}