force-app/main/default/objects/CE_Modules__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Is_All_Sessions_Completed__c.field-meta.xml
<CustomField>
    <fullName>Is_All_Sessions_Completed__c</fullName>
    <formula>Total_Session__c  =  Total_Sessions_Completed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is All Sessions Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Module_Agenda__c.field-meta.xml
<CustomField>
    <fullName>Module_Agenda__c</fullName>
    <label>Module Agenda</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Module_Icon__c.field-meta.xml
<CustomField>
    <fullName>Module_Icon__c</fullName>
    <label>Module Icon</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Session_s_Point__c.field-meta.xml
<CustomField>
    <fullName>Session_s_Point__c</fullName>
    <formula>If( Course_Enrollment__r.Applied_by__c == &quot;Mentor&quot;,If(Total_Sessions_Completed__c &gt; 0,100 *  Total_Sessions_Completed__c,0) ,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Session&apos;s Point</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Total_Session__c.field-meta.xml
<CustomField>
    <fullName>Total_Session__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Session</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Total_Sessions_Completed__c.field-meta.xml
<CustomField>
    <fullName>Total_Sessions_Completed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Sessions Completed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Total_Sessions_Duration__c.field-meta.xml
<CustomField>
    <fullName>Total_Sessions_Duration__c</fullName>
    <label>Total Sessions Duration</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Assignment_Required__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assignment Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>CE-Sessions</relationshipLabel>
    <relationshipName>CE_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <formula>CASESAFEID(CE_Module__r.Course_Enrollment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Enrollment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <formula>IF( OR( VALUE( MID( TEXT(   End_DateTime__c + 330/1440), 12, 2 ) ) = 0, VALUE( MID( TEXT( End_DateTime__c + 330/1440 ), 12, 2 ) ) = 12 ), &quot;12&quot;, TEXT( VALUE( MID( TEXT( End_DateTime__c + 330/1440 ), 12, 2 ) ) - IF( VALUE( MID( TEXT( End_DateTime__c + 330/1440), 12, 2 ) ) &lt; 12, 0, 12 ) ) ) &amp; &quot;:&quot; &amp; MID( TEXT( End_DateTime__c + 330/1440), 15, 2 ) &amp;&quot; &quot; &amp; IF( VALUE( MID( TEXT( End_DateTime__c + 330/1440 ), 12, 2 ) ) &lt; 12, &quot;AM&quot;, &quot;PM&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Meeting_Link__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Link__c</fullName>
    <label>Meeting Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.FirstName  +  CE_Module__r.Course_Enrollment__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor_Email__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Email__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor_Id__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Id__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <defaultValue>100</defaultValue>
    <label>Points</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newly created</fullName>
            </value>
            <value>
                <fullName>Applied for Programme</fullName>
            </value>
            <value>
                <fullName>Mentorship Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Master_Name__c</fullName>
    <formula>Course_Master__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Master Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Total_Sessions_Completed__c.field-meta.xml
<CustomField>
    <fullName>Total_Sessions_Completed__c</fullName>
    <label>Total Sessions Completed</label>
    <summarizedField>CE_Modules__c.Total_Sessions_Completed__c</summarizedField>
    <summaryForeignKey>CE_Modules__c.Course_Enrollment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Update__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>Course Updates</relationshipLabel>
    <relationshipName>Course_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Update__c/fields/CE_Session__c.field-meta.xml
<CustomField>
    <fullName>CE_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CE-Session</label>
    <referenceTo>CE_Session__c</referenceTo>
    <relationshipLabel>Course Updates</relationshipLabel>
    <relationshipName>Course_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Update__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Students Course Enrollement</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Course Updates</relationshipLabel>
    <relationshipName>Course_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Attachment__c/fields/CE_Session__c.field-meta.xml
<CustomField>
    <fullName>CE_Session__c</fullName>
    <label>CE-Session</label>
    <referenceTo>CE_Session__c</referenceTo>
    <relationshipLabel>Session Attachments</relationshipLabel>
    <relationshipName>Session_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WS_CourseEnrollmentDetailsModel.cls
public class WS_CourseEnrollmentDetailsModel {
    public static List<CE_Modules__c> getCEModules(String enrolmentId){
        return [SELECT Active__c,Course_Enrollment__c,Course_Enrollment__r.Course_Master_Name__c,Course_Master__c,CreatedById,CreatedDate,Description__c,Id,IsDeleted,Is_All_Sessions_Completed__c,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Module_Agenda__c,Module_Icon__c,Name,Order__c,Session_s_Point__c,Status__c,SystemModstamp,Total_Sessions_Completed__c,Total_Sessions_Duration__c,Total_Session__c FROM CE_Modules__c WHERE Course_Enrollment__c =: enrolmentId AND Total_Session__c > 0];
    }
    public static List<CE_Session__c> getCESessions(set<Id> moduleIds){
        return [SELECT Assignment_Required__c,CE_Module__c,CreatedById,CreatedDate,End_DateTime__c,End_Time__c,Id,IsDeleted,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Meeting_Link__c,Mentor_Email__c,Mentor_Id__c,Mentor__c,Name,OwnerId,Planned_Date__c,Points__c,Replanned_Date_Time__c,Self_Paced__c,Session_Agenda__c,Session_Duration__c,Session_Title__c,Start_DateTime__c,Start_Time_del__c,Status__c,SystemModstamp,Video_Url__c
                FROM CE_Session__c WHERE CE_Module__c in : moduleIds ORDER BY Start_DateTime__c ASC NULLS LAST];
    }
    public static List<Session_Attachment__c> getCESessionAtt(set<Id> sessionIds){
        return [SELECT Attachment_Type__c,CE_Session__c,File_Type__c,FILE_URL__c,Id,Name,Uploaded_By__c,Video_Id__c,CreatedDate  FROM Session_Attachment__c WHERE CE_Session__c in : sessionIds ORDER BY CreatedDate ASC NULLS LAST];
    }
    public static Course_Enrollment__c getMentorCE(String enrolmentId){
        return [SELECT Id,Mentor__c,Contact__c,Contact__r.Name,Contact__r.Firebase_Id__c,Contact__r.Email,Contact__r.Profile_Picture__c,Contact__r.Registered_By__c,Contact__r.Initials__c ,Course_Master__c FROM Course_Enrollment__c WHERE id =: enrolmentId limit 1];
    }
    public static List<Course_Enrollment__c> getMenteesEnrolledUnder(String courseMasterId, String mentorContactId, String CEStatus){
        return [Select Id,Name,Contact__c,Mentor__c,Applied_by__c,Contact__r.Name,Contact__r.Firebase_Id__c,Contact__r.Email,Contact__r.Profile_Picture__c,Contact__r.Registered_By__c,Contact__r.Initials__c from Course_Enrollment__c where Mentor__c =: mentorContactId and Course_Master__c =: courseMasterId ];
    }
    public static Course_Enrollment__c getStudentCE(String enrolmentId){
        return [SELECT Id,Mentor__c,Course_Master__c FROM Course_Enrollment__c WHERE id =: enrolmentId limit 1];
    }
    public static Course_Enrollment__c getMentorsEnrollment(String courseMasterId, String mentorContactId, String CEStatus){
        system.debug('courseMasterId::'+courseMasterId);
        system.debug('mentorContactId::'+mentorContactId);
        system.debug('CEStatus::'+CEStatus);
        return [SELECT Id,Mentor__c,Course_Master__c,Contact__r.Name,Contact__r.Firebase_Id__c,Contact__r.Email,Contact__r.Profile_Picture__c,Contact__r.Registered_By__c,Contact__r.Initials__c FROM Course_Enrollment__c WHERE Contact__c	 =: mentorContactId and Course_Master__c =: courseMasterId limit 1];
    }
    public static string getMentorCEFromStudentsCe(String enrolmentId){
        return [Select Mentor_Course_Enrollment__c FROM Course_Enrollment__c WHERE id =: enrolmentId limit 1].Mentor_Course_Enrollment__c;
    }
    public static List<Course_Update__c> getStudentCourseUpdate(String studentEnrolmentId){
        return [SELECT CE_Module__c,CE_Session__c,Course_Enrollment__c,Id,Status__c FROM Course_Update__c WHERE Course_Enrollment__c =: studentEnrolmentId];
    }
}