force-app/main/default/objects/CE_Modules__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MentorAssessmentQuestionWrapper.cls
global class MentorAssessmentQuestionWrapper{
    global cls_Course_Enrollment[] Result;
 
    global class cls_Course_Enrollment {
        global Course_Enrollment__c record;
        global cls_CourseMaster[] CourseMaster;
        global cls_CEModules[] CEModules;
    }
    global class cls_CourseMaster {
        global Course_Master__c record;
        global Assessment_Question__c[] Pre;
        global Assessment_Question__c[] Post;
    }
    global class cls_CEModules {
        global CE_Modules__c record;
        global Assessment_Question__c[] ModuleAssessmentQuestions;
    }
    
    global static MentorAssessmentQuestionWrapper parse(String json){
        return (MentorAssessmentQuestionWrapper) System.JSON.deserialize(json, MentorAssessmentQuestionWrapper.class);
    }  
}