force-app/main/default/objects/CE_Modules__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>CE-Sessions</relationshipLabel>
    <relationshipName>CE_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <formula>CASESAFEID(CE_Module__r.Course_Enrollment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Enrollment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Meeting_Link__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Link__c</fullName>
    <label>Meeting Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.FirstName  +  CE_Module__r.Course_Enrollment__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Agenda__c.field-meta.xml
<CustomField>
    <fullName>Session_Agenda__c</fullName>
    <label>Session Agenda</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Duration__c.field-meta.xml
<CustomField>
    <fullName>Session_Duration__c</fullName>
    <formula>IF(ISNULL(Start_DateTime__c)|| ISNULL(End_DateTime__c),0,(End_DateTime__c-Start_DateTime__c)*24*60)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Session&apos;s Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Title__c.field-meta.xml
<CustomField>
    <fullName>Session_Title__c</fullName>
    <label>Session Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Firebase_Id__c.field-meta.xml
<CustomField>
    <fullName>Firebase_Id__c</fullName>
    <externalId>true</externalId>
    <label>Firebase Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Initials__c.field-meta.xml
<CustomField>
    <fullName>Initials__c</fullName>
    <formula>LEFT(FirstName, 1)+&apos;.&apos;+LEFT(LastName, 1)</formula>
    <label>Initials</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Registered_By__c.field-meta.xml
<CustomField>
    <fullName>Registered_By__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registered By</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newly created</fullName>
            </value>
            <value>
                <fullName>Applied for Programme</fullName>
            </value>
            <value>
                <fullName>Mentorship Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Attachment__c/fields/Attachment_Type__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Type__c</fullName>
    <label>Attachment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Note</fullName>
                <label>NOTE</label>
            </value>
            <value>
                <fullName>Assessment</fullName>
                <label>ASSESSMENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Attachment__c/fields/CE_Session__c.field-meta.xml
<CustomField>
    <fullName>CE_Session__c</fullName>
    <label>CE-Session</label>
    <referenceTo>CE_Session__c</referenceTo>
    <relationshipLabel>Session Attachments</relationshipLabel>
    <relationshipName>Session_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Attachment__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIDEO</fullName>
            </value>
            <value>
                <fullName>PDF</fullName>
            </value>
            <value>
                <fullName>IMAGE</fullName>
            </value>
            <value>
                <fullName>TEXT</fullName>
            </value>
            <value>
                <fullName>FILE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Attachment__c/fields/FILE_URL__c.field-meta.xml
<CustomField>
    <fullName>FILE_URL__c</fullName>
    <label>File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Session_Attachment__c/fields/Uploaded_By__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Uploaded By(contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Session Attachments</relationshipLabel>
    <relationshipName>Session_Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Attachment__c/fields/Video_Id__c.field-meta.xml
<CustomField>
    <fullName>Video_Id__c</fullName>
    <label>Video Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetSessionDetailsService.cls
@RestResource(urlMapping='/v1/get_Session_Attachments/')
global  with sharing class  GetSessionDetailsService {
    @HttpGet
    global static List<MentorshipServiceModels.sessionsAttachment> doGetAllSessionDetails() {
        RestRequest req 																						= RestContext.request;
        RestResponse res 																						= RestContext.response;
        Map<String,String> paramsMap 																			= RestContext.request.params;
        String sessionId 																						= paramsMap.get('id');//a166D000000Rlx3
        
        //system.debug('sessionId::'+sessionId);
        List<MentorshipServiceModels.sessionsAttachment> wrapInstance = new List<MentorshipServiceModels.sessionsAttachment>();
        List<CE_Session__c> attachmentList = new List<CE_Session__c>();
        List<Course_Enrollment__c> menteesUnderMentorsEnrollment = new List<Course_Enrollment__c>();
        String CEofMentor;
        
        if(!String.isBlank(sessionId)){
            attachmentList = [SELECT Id, Name,Session_Title__c,Session_Agenda__c,Meeting_Link__c,Start_DateTime__c,End_DateTime__c,Session_Duration__c,Status__c,CE_Module__r.Course_Master__r.Name,CE_Module__r.Course_Master__r.Description__c,CE_Module__r.Course_Master__r.Thumbnail_URL__c,CE_Module__r.Course_Master__r.Short_Description__c,CE_Module__r.Course_Master__r.Brand__c,CE_Module__r.Course_Enrollment__r.Contact__r.Firebase_Id__c, (SELECT Id, Name, FILE_URL__c, Video_Id__c, Attachment_Type__c ,FILE_TYPE__C,Uploaded_By__c,Uploaded_By__r.Name,Uploaded_By__r.Profile_Picture__c FROM Session_Attachments__r ) FROM CE_Session__c WHERE Id =: sessionId];
            CEofMentor = [SELECT CE_Module__r.Course_Enrollment__c FROM CE_Session__c where id = : sessionId limit 1].CE_Module__r.Course_Enrollment__c;
            //system.debug('CEofMentor::'+CEofMentor);
            menteesUnderMentorsEnrollment = [SELECT Id,Contact__c,Contact__r.RecordTypeId,Contact__r.Registered_By__c,Contact__r.Name,Contact__r.Profile_Picture__c,Contact__r.Firebase_Id__c,Contact__r.Initials__c,Mentor__c,Mentor__r.Name,Mentor__r.Profile_Picture__c,Mentor__r.Firebase_Id__c,Mentor__r.Initials__c,Mentor__r.Registered_By__c,Mentor_Course_Enrollment__r.Id FROM Course_Enrollment__c WHERE Mentor_Course_Enrollment__c =: CEofMentor ];
            //system.debug('menteesUnderMentorsEnrollment.size()::'+menteesUnderMentorsEnrollment.size());
            //system.debug('menteesUnderMentorsEnrollment::'+menteesUnderMentorsEnrollment);
        }
        wrapInstance.add(new MentorshipServiceModels.sessionsAttachment(attachmentList,menteesUnderMentorsEnrollment));
        return wrapInstance;
    }
}