force-app/main/default/objects/CE_Modules__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <formula>CASESAFEID(CE_Module__r.Course_Enrollment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Enrollment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Update__c/fields/CE_Session__c.field-meta.xml
<CustomField>
    <fullName>CE_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CE-Session</label>
    <referenceTo>CE_Session__c</referenceTo>
    <relationshipLabel>Course Updates</relationshipLabel>
    <relationshipName>Course_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Update__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Students Course Enrollement</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Course Updates</relationshipLabel>
    <relationshipName>Course_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Attachment__c/fields/CE_Session__c.field-meta.xml
<CustomField>
    <fullName>CE_Session__c</fullName>
    <label>CE-Session</label>
    <referenceTo>CE_Session__c</referenceTo>
    <relationshipLabel>Session Attachments</relationshipLabel>
    <relationshipName>Session_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Attachment__c/fields/Course_Update__c.field-meta.xml
<CustomField>
    <fullName>Course_Update__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Update</label>
    <referenceTo>Course_Update__c</referenceTo>
    <relationshipLabel>Session Attachments</relationshipLabel>
    <relationshipName>Session_Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GetDetailedCourseEnrolledDetailsWrapper.cls
global class GetDetailedCourseEnrolledDetailsWrapper{
    global cls_result[] Result;
    global class cls_result {
        global List<Course_Enrollment__c> mentee;
        global cls_modules[] modules;
        global Course_Update__c[] courseupdatelist ;
    }
	global class cls_modules {
		global CE_Modules__c moduleRec;	
		global cls_sessions[] sessions;
	}
	global class cls_sessions {
		global CE_Session__c session;	
		global Session_Attachment__c[] attachmentsByMentor;
        global Session_Attachment__c[] attachmentsByMentee;
	}
	
	global static GetDetailedCourseEnrolledDetailsWrapper parse(String json){
		return (GetDetailedCourseEnrolledDetailsWrapper) System.JSON.deserialize(json, GetDetailedCourseEnrolledDetailsWrapper.class);
	}
}