force-app/main/default/objects/CE_Modules__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Session_s_Point__c.field-meta.xml
<CustomField>
    <fullName>Session_s_Point__c</fullName>
    <formula>If( Course_Enrollment__r.Applied_by__c == &quot;Mentor&quot;,If(Total_Sessions_Completed__c &gt; 0,100 *  Total_Sessions_Completed__c,0) ,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Session&apos;s Point</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newly created</fullName>
            </value>
            <value>
                <fullName>Applied for Programme</fullName>
            </value>
            <value>
                <fullName>Mentorship Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <description>This record type will be selected when a Mentor comes on platform for mentoring purpose</description>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/fields/Applied_by__c.field-meta.xml
<CustomField>
    <fullName>Applied_by__c</fullName>
    <formula>Contact__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applied by</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Master_Name__c</fullName>
    <formula>Course_Master__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Master Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Points</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/classes/CEModuleTriggerHelper.cls
public class CEModuleTriggerHelper {
    //Notify mentor about CE-Module completion
    public static void sendEmailOnCEModuleCompletion(Map<id, CE_Modules__c> newCEModuleMap, Map<id, CE_Modules__c> oldCEModuleMAp){
        set<Id> CEIdonCEModule = new set<Id>();
        map<String, String> CEModuleNameByCEID = new map<String, String>();
        List<Course_Enrollment__c> courseEnrollementsByMentor = new List<Course_Enrollment__c> ();
        
        for(CE_Modules__c CEModule : newCEModuleMap.values()){
            if(CEModule.Status__c != oldCEModuleMAp.get(CEModule.Id).Status__c && CEModule.Status__c == 'Completed'){
                CEIdonCEModule.add(CEModule.Course_Enrollment__c);
                CEModuleNameByCEID.put(CEModule.Course_Enrollment__c,CEModule.Name);
            }
        }
        if(!CEIdonCEModule.isEmpty()){
            courseEnrollementsByMentor = [Select Contact__r.Name,Applied_by__c ,Contact__r.Email,Course_Master__c,Course_Master_Name__c,Mentor_Course_Enrollment__c  From Course_Enrollment__c Where Id in : CEIdonCEModule ];
        }
        EmailHepler.sendEmailforCEModuleCompletion(courseEnrollementsByMentor, 'Module Completion Mail',CEModuleNameByCEID );
    }
    //Notify mentee about CE-Module completion
    public static void sendEmailOnCEModuleCompletionToStudents(Map<id, CE_Modules__c> newCEModuleMap, Map<id, CE_Modules__c> oldCEModuleMAp){
        set<Id> CEIdOfMentoronCEModule = new set<Id>();
        map<String, String> CEModuleNameByCEID = new map<String, String>();
        List<Course_Enrollment__c> courseEnrollementsStudents = new  List<Course_Enrollment__c> ();
        for(CE_Modules__c CEModule : newCEModuleMap.values()){
            if(CEModule.Status__c != oldCEModuleMAp.get(CEModule.Id).Status__c && CEModule.Status__c == 'Completed'){
                CEIdOfMentoronCEModule.add(CEModule.Course_Enrollment__c);
                CEModuleNameByCEID.put(CEModule.Course_Enrollment__c,CEModule.Name);
            }
        }
        if(!CEIdOfMentoronCEModule.isEmpty()){
            courseEnrollementsStudents = [Select Contact__r.Name,Applied_by__c ,Contact__r.Email,Course_Master__c,Course_Master_Name__c,Mentor_Course_Enrollment__c  From Course_Enrollment__c Where Mentor_Course_Enrollment__c in : CEIdOfMentoronCEModule ];     
        }
        EmailHepler.sendEmailforCEModuleCompletion(courseEnrollementsStudents, 'Module Completion Mail',CEModuleNameByCEID );
    }
    public static void updatePointsOnCourseEnrollment(Map<id, CE_Modules__c> newCEModuleMap, Map<id, CE_Modules__c> oldCEModuleMAp){
        set<Id> courseEnrollmentId = new set<Id>();
		List<Course_Enrollment__c> CourseEnrollmentList = new List<Course_Enrollment__c>();
        List<Course_Enrollment__c> CourseEnrollmentListToBeUpdated = new List<Course_Enrollment__c>();

        for(CE_Modules__c CEModule : newCEModuleMap.values()){
            if(CEModule.Session_s_Point__c > oldCEModuleMAp.get(CEModule.Id).Session_s_Point__c){
                courseEnrollmentId.add(CEModule.Course_Enrollment__c);
            }
        }
        if(!courseEnrollmentId.isEmpty()){
            CourseEnrollmentList = [Select Id, Total_Points__c,(Select id,Session_s_Point__c From CE_Modules__r) From Course_Enrollment__c where Id in : courseEnrollmentId];
        }
        if(!CourseEnrollmentList.isEmpty()){
            for(Course_Enrollment__c courseEnrollment : CourseEnrollmentList){
                Course_Enrollment__c courseEnrollmentToBeUpdated = new Course_Enrollment__c();
                courseEnrollmentToBeUpdated.Id = courseEnrollment.id;
                decimal points = 0;
                for(CE_Modules__c CEModule : courseEnrollment.CE_Modules__r){
                    points += CEModule.Session_s_Point__c != 0? CEModule.Session_s_Point__c:0;
                }
                courseEnrollmentToBeUpdated.Total_Points__c = courseEnrollment.Total_Points__c>0? courseEnrollment.Total_Points__c + points : points;
                CourseEnrollmentListToBeUpdated.add(courseEnrollmentToBeUpdated);
            }
        }
        if(!CourseEnrollmentListToBeUpdated.isEmpty()){
         update CourseEnrollmentListToBeUpdated;   
        }
    }
}