force-app/main/default/objects/CE_Modules__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <formula>CASESAFEID(CE_Module__r.Course_Enrollment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Enrollment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WrapperTest.cls
@isTest public class WrapperTest {
    @isTest Static void FireBaseWrapperForAddingValuesToArrayTest(){
        FireBaseWrapperForAddingValuesToArray.parse('{"firstName":"aakash"}');
    }
    @isTest Static void GetDetailedCourseEnrolledDetailsWrapperTest(){
        GetDetailedCourseEnrolledDetailsWrapper.parse('{"firstName":"aakash"}');
    }
    @isTest Static void MentorAssessmentQuestionWrapperTest(){
        MentorAssessmentQuestionWrapper.parse('{"firstName":"aakash"}');
    }
    @isTest Static void CreateUserFbWrapperTest(){
        CreateUserFbWrapper.parse('{"firstName":"aakash"}');
        CreateUserFbWrapper wrappInstance = new CreateUserFbWrapper();
        wrappInstance.email = 'aakash@mailinator.com';
        wrappInstance.expiresIn = 'testing';
        wrappInstance.idToken = 'testing';
        wrappInstance.kind = 'testing';
        wrappInstance.localId = 'testing';
        wrappInstance.refreshToken = 'testing';
    }
    @isTest Static void MentorshipServiceModelsTest(){
        List<Student_Test_Association__c> StudentTestAssociation = new List<Student_Test_Association__c>();
        List<Assessment_Question__c> assessmentQuestion = new List<Assessment_Question__c>();
        List<CE_Session__c> sessionsAttachmentList = new List<CE_Session__c>();
        List<Course_Enrollment__c> menteesUnderMentor = new List<Course_Enrollment__c>() ;
        List<CE_Modules__c> CEModuleList = new List<CE_Modules__c>();
        List<CE_Session__c> CESessionsListWuthAttachment = new List<CE_Session__c>();
        List<Course_Enrollment__c> relatedApplicants = new List<Course_Enrollment__c>();
        List<Course_Enrollment__c> upcoming_sessions = new List<Course_Enrollment__c>();
        Course_Enrollment__c ceRec = new Course_Enrollment__c();		
        Object compareTo ;
        
        MentorshipServiceModels.ErrorInfo errorWrap = new MentorshipServiceModels.ErrorInfo();
        MentorshipServiceModels.CourseSchedule courseSchedule = new MentorshipServiceModels.CourseSchedule();
        
        MentorshipServiceModels.CEModuleQuestionAndSTAWrapper STAWrap = New MentorshipServiceModels.CEModuleQuestionAndSTAWrapper(StudentTestAssociation,assessmentQuestion);
        MentorshipServiceModels.sessionsAttachment sessionAttWrap = New MentorshipServiceModels.sessionsAttachment(sessionsAttachmentList, menteesUnderMentor);
        MentorshipServiceModels.enrollmentDetails enrollmentWrap = New MentorshipServiceModels.enrollmentDetails(CEModuleList,CESessionsListWuthAttachment,relatedApplicants);
        MentorshipServiceModels.mentor_details mentorDetailWrap = new MentorshipServiceModels.mentor_details();
        mentorDetailWrap.compareTo(compareTo);
    }
    @isTest Static void StudentTestAPIWrapperTest(){
        StudentTestAPIWrapper.parse('{"firstName":"aakash"}');
    }
    @isTest Static void wrapperForFetchingFBDataUsingBatchTest(){
        wrapperForFetchingFBDataUsingBatch.parse('{"firstName":"aakash"}');
        wrapperForFetchingFBDataUsingBatch wrappInstance = new wrapperForFetchingFBDataUsingBatch();
        wrapperForFetchingFBDataUsingBatch.document docInstance =  new wrapperForFetchingFBDataUsingBatch.document();
        docInstance.createTime = 'dateTest';
        docInstance.updateTime = 'updateTest';
        docInstance.name = 'nameTest';
    }
    @isTest Static void FireBaseWrapperTest(){
        FireBaseWrapper.parse('{"firstName":"aakash"}');
    }
}