force-app/main/default/objects/CE_Modules__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>CE-Sessions</relationshipLabel>
    <relationshipName>CE_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <formula>CASESAFEID(CE_Module__r.Course_Enrollment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Enrollment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <formula>IF( OR( VALUE( MID( TEXT(   End_DateTime__c + 330/1440), 12, 2 ) ) = 0, VALUE( MID( TEXT( End_DateTime__c + 330/1440 ), 12, 2 ) ) = 12 ), &quot;12&quot;, TEXT( VALUE( MID( TEXT( End_DateTime__c + 330/1440 ), 12, 2 ) ) - IF( VALUE( MID( TEXT( End_DateTime__c + 330/1440), 12, 2 ) ) &lt; 12, 0, 12 ) ) ) &amp; &quot;:&quot; &amp; MID( TEXT( End_DateTime__c + 330/1440), 15, 2 ) &amp;&quot; &quot; &amp; IF( VALUE( MID( TEXT( End_DateTime__c + 330/1440 ), 12, 2 ) ) &lt; 12, &quot;AM&quot;, &quot;PM&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Meeting_Link__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Link__c</fullName>
    <label>Meeting Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.FirstName  +  CE_Module__r.Course_Enrollment__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor_Email__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Email__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor_Id__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Id__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <defaultValue>100</defaultValue>
    <label>Points</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Replanned_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Replanned_Date_Time__c</fullName>
    <label>Replanned Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Agenda__c.field-meta.xml
<CustomField>
    <fullName>Session_Agenda__c</fullName>
    <label>Session Agenda</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Duration__c.field-meta.xml
<CustomField>
    <fullName>Session_Duration__c</fullName>
    <formula>IF(ISNULL(Start_DateTime__c)|| ISNULL(End_DateTime__c),0,(End_DateTime__c-Start_DateTime__c)*24*60)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Session&apos;s Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Title__c.field-meta.xml
<CustomField>
    <fullName>Session_Title__c</fullName>
    <label>Session Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Start_Time_del__c.field-meta.xml
<CustomField>
    <fullName>Start_Time_del__c</fullName>
    <formula>IF( OR( VALUE( MID( TEXT(   Start_DateTime__c + 330/1440), 12, 2 ) ) = 0, VALUE( MID( TEXT( Start_DateTime__c + 330/1440 ), 12, 2 ) ) = 12 ), &quot;12&quot;, TEXT( VALUE( MID( TEXT( Start_DateTime__c + 330/1440 ), 12, 2 ) ) - IF( VALUE( MID( TEXT( Start_DateTime__c + 330/1440), 12, 2 ) ) &lt; 12, 0, 12 ) ) ) &amp; &quot;:&quot; &amp; MID( TEXT( Start_DateTime__c + 330/1440), 15, 2 ) &amp;&quot; &quot; &amp; IF( VALUE( MID( TEXT( Start_DateTime__c + 330/1440 ), 12, 2 ) ) &lt; 12, &quot;AM&quot;, &quot;PM&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Master_Name__c</fullName>
    <formula>Course_Master__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Master Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduledCourseSessionPdfHelper.cls
global class ScheduledCourseSessionPdfHelper {
    public static List<CE_Modules__c> courseModuleWithCourseSession 		{get;set;}
    public String courseEnrollmentId 										{get;set;}
    public static string CourseName 										{get;set;}
    public static string courseDescription 									{get;set;}
    global ScheduledCourseSessionPdfHelper (){
        set<Id> CEMOdulesId = new set<id>();
        courseEnrollmentId = ApexPages.currentPage().getParameters().get('id');
        //system.debug('courseEnrollmentId::'+courseEnrollmentId);
        List<CE_Modules__c> CEModulesList = [SELECT Id FROM CE_Modules__c WHERE Course_Enrollment__c =: courseEnrollmentId ];
        for(CE_Modules__c CEModule : CEModulesList){
            CEMOdulesId.add(CEModule.Id);
        }
        
        //system.debug('CEMOdulesId::'+CEMOdulesId);
        courseModuleWithCourseSession = [SELECT Name,Id,(SELECT CE_Module__c,End_DateTime__c,End_Time__c,Meeting_Link__c,Mentor_Email__c,Mentor_Id__c,Mentor__c,Name,Planned_Date__c,Points__c,Replanned_Date_Time__c,Self_Paced__c,Session_Agenda__c,Session_Duration__c,Session_Title__c,Start_DateTime__c,Start_Time_del__c,Status__c FROM CE_Sessions__r WHERE Status__c = 'SCHEDULED' ORDER BY Start_DateTime__c ASC NULLS LAST) FROM CE_Modules__c WHERE Course_Enrollment__c =: courseEnrollmentId ];
        CourseName = [Select Course_Master_Name__c From Course_Enrollment__c Where Id = :courseEnrollmentId ].Course_Master_Name__c;
        //system.debug('CourseName::'+CourseName);
        
        courseDescription = [Select Course_Master__r.Description__c From Course_Enrollment__c Where Id = :courseEnrollmentId].Course_Master__r.Description__c;
        //system.debug('courseDescription::'+courseDescription);
    }  
    @future(Callout=true)
    global static void attachPDFAuto(string courseEnrollmentId){
        attachingPDF(courseEnrollmentId);
    }
    @auraEnabled
    global static void attachingPDF(string courseEnrollmentId) {
        //system.debug('courseEnrollmentId::'+courseEnrollmentId);
        PageReference pdfPage = Page.ScheduledCourseSessionPDFclone;
        pdfPage.getParameters().put('id',courseEnrollmentId);
        Blob pdfBlob;
        if(Test.isRunningTest()){
            pdfBlob = blob.valueof('TEST');
        }else{
            pdfBlob = pdfPage.getContent(); 
        }
        
        List<Attachment> attachmetsList = new List<Attachment> ();
        attachmetsList = [select id from Attachment where parentId = : courseEnrollmentId]; 
        if(!attachmetsList.isEmpty()){
            delete attachmetsList;           
        }
        
        Attachment attach = new Attachment(parentId = courseEnrollmentId, Name = 'scheduledCourseSession.pdf', body = pdfBlob); 
        insert attach;
    }  
}