force-app/main/default/objects/CE_Modules__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Applied_by__c.field-meta.xml
<CustomField>
    <fullName>Applied_by__c</fullName>
    <formula>Contact__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applied by</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Master_Name__c</fullName>
    <formula>Course_Master__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Master Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Student_Test_Association__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Test_Master__c.field-meta.xml
<CustomField>
    <fullName>Test_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Master</label>
    <referenceTo>Test_Master__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Test_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Type__c</fullName>
    <formula>TEXT( Test_Master__r.Test_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>Test Masters</relationshipLabel>
    <relationshipName>Test_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Test Masters</relationshipLabel>
    <relationshipName>Test_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/Test_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Type__c</fullName>
    <label>Test Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestMasterTriggerHelper.cls
public class TestMasterTriggerHelper {
    public static void insertSTARec(Map<id, Test_Master__c> newTestMasterMap){
        //system.debug('newTestMasterMap::'+newTestMasterMap);
        map<String, String> testMasterIdByCEModuleId = new map<String, String>();
        set<Id> CEModuleIds  = new Set<Id>();
        List<CE_Modules__c> CEmodulesList = new List<CE_Modules__c >();
        Set<Id> courseEnrollmetIdOfMentors = new Set<Id>();
        List<Course_Enrollment__c> courseEnrollmentOfStudentsRelatedToMentorsCE = new List<Course_Enrollment__c>();
        List<Course_Enrollment__c> studentsCourseEnrollment = new List<Course_Enrollment__c>();
        List<Student_Test_Association__c> StudentTestAssociationToBeInserted = new List<Student_Test_Association__c>();
        map<String, String> CEModuleIdByMentorsCourseEnrollmentId = new map<String, String>();
        
        for(Test_Master__c testMaster : newTestMasterMap.values()){
            if(testMaster.Test_Type__c == 'Module'){
                testMasterIdByCEModuleId.put(testMaster.CE_Module__c,testMaster.Id);
            }
        }
        //system.debug('testMasterIdByCEModuleId::'+testMasterIdByCEModuleId);
        if(!testMasterIdByCEModuleId.isEmpty()){
            for(String CEModuleId : testMasterIdByCEModuleId.KeySet()){
                CEModuleIds.add(CEModuleId);
            }
        }
        //system.debug('CEModuleIds::'+CEModuleIds);
        if(!CEModuleIds.isEmpty()){
            CEmodulesList = [SELECT Id,Course_Enrollment__c,Course_Enrollment__r.Applied_by__c FROM CE_Modules__c WHERE Id in :  CEModuleIds];
        }
        //system.debug('CEmodulesList::'+CEmodulesList);
        
        if(!CEmodulesList.isEmpty()){
            for(CE_Modules__c CEModule : CEmodulesList){
                courseEnrollmetIdOfMentors.add(CEModule.Course_Enrollment__c);
                CEModuleIdByMentorsCourseEnrollmentId.put(CEModule.Course_Enrollment__c, CEModule.Id);
            }
        }
        //system.debug('CEModuleIdByMentorsCourseEnrollmentId::'+CEModuleIdByMentorsCourseEnrollmentId);
        //system.debug('courseEnrollmetIdOfMentors::'+courseEnrollmetIdOfMentors);
        if(!courseEnrollmetIdOfMentors.isEmpty()){
            studentsCourseEnrollment = [SELECT Applied_by__c,Contact__c,Course_Master_Name__c,Course_Master__c,Id,Mentor_Course_Enrollment__c,Mentor__c,Name FROM Course_Enrollment__c WHERE Mentor_Course_Enrollment__c in : courseEnrollmetIdOfMentors];
        }
        //system.debug('studentsCourseEnrollment::'+studentsCourseEnrollment);
        if(!studentsCourseEnrollment.isEmpty()){
            for(Course_Enrollment__c CourseEnrollmentofStudent : studentsCourseEnrollment){
                Student_Test_Association__c studentTestAssociationRec = new Student_Test_Association__c();
                studentTestAssociationRec.Contact__c = CourseEnrollmentofStudent.Contact__c;
                //testMAster by mentor Id    
                studentTestAssociationRec.Test_Master__c = testMasterIdByCEModuleId.get(CEModuleIdByMentorsCourseEnrollmentId.get(CourseEnrollmentofStudent.Mentor_Course_Enrollment__c)) != null ? testMasterIdByCEModuleId.get(CEModuleIdByMentorsCourseEnrollmentId.get(CourseEnrollmentofStudent.Mentor_Course_Enrollment__c)) : ''; 
                //system.debug('testMasterIdByCEModuleId.get(CEModuleIdByMentorsCourseEnrollmentId.get(CourseEnrollmentofStudent.Mentor_Course_Enrollment__c))::'+testMasterIdByCEModuleId.get(CEModuleIdByMentorsCourseEnrollmentId.get(CourseEnrollmentofStudent.Mentor_Course_Enrollment__c)));
                studentTestAssociationRec.Status__c = 'Pending';
                studentTestAssociationRec.Course_Enrollment__c = CourseEnrollmentofStudent.Id;
                // module id by mentor id   
                studentTestAssociationRec.CE_Module__c = CEModuleIdByMentorsCourseEnrollmentId.get(CourseEnrollmentofStudent.Mentor_Course_Enrollment__c) != null ? CEModuleIdByMentorsCourseEnrollmentId.get(CourseEnrollmentofStudent.Mentor_Course_Enrollment__c) : ''; 
                //system.debug('CEModuleIdByMentorsCourseEnrollmentId.get(CourseEnrollmentofStudent.Mentor_Course_Enrollment__c)::'+CEModuleIdByMentorsCourseEnrollmentId.get(CourseEnrollmentofStudent.Mentor_Course_Enrollment__c));
                StudentTestAssociationToBeInserted.add(studentTestAssociationRec);
            }
        }
        //system.debug('StudentTestAssociationToBeInserted::'+StudentTestAssociationToBeInserted);
        if(!StudentTestAssociationToBeInserted.isEmpty()){
            insert StudentTestAssociationToBeInserted;
        }
    }
    
}