force-app/main/default/objects/CE_Modules__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <formula>CASESAFEID(CE_Module__r.Course_Enrollment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Enrollment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.FirstName  +  CE_Module__r.Course_Enrollment__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Session_Attachment__c/fields/Attachment_Type__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Type__c</fullName>
    <label>Attachment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Note</fullName>
                <label>NOTE</label>
            </value>
            <value>
                <fullName>Assessment</fullName>
                <label>ASSESSMENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Attachment__c/fields/CE_Session__c.field-meta.xml
<CustomField>
    <fullName>CE_Session__c</fullName>
    <label>CE-Session</label>
    <referenceTo>CE_Session__c</referenceTo>
    <relationshipLabel>Session Attachments</relationshipLabel>
    <relationshipName>Session_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WS_CourseEnrollmentDetails.cls
@RestResource(urlMapping='/v1/get/get_all_details_under_enrollment/*')
global  with sharing class  WS_CourseEnrollmentDetails {
    public static Set<Id> sessionIds;
    @HttpGet
    global static GetDetailedCourseEnrolledDetailsWrapper doGetAllDetailsUnderEnrollment() {
        
        RestRequest GetRequest 																		= RestContext.request;
        RestResponse GetResponse 																	= RestContext.response;
        String enrolmentId 																			= RestContext.request.params.get('id');	
        // Student/Instructor
        String userType 																			= RestContext.request.params.get('user_type');
        
        //System.debug('--- enrolmentId '+enrolmentId);
        //System.debug('--- userType '+userType);
        
        Set<Id> moduleIds 																			= new Set<Id>();
        sessionIds																					= new Set<Id>();
        
        Set<Id> allMenteesPlusMentor 																= new Set<Id>();
        Map<Id,List<CE_Session__c>> CESessionsByModuleId 											= new Map<Id,List<CE_Session__c>> ();
        Map<Id,List<Session_Attachment__c>> attachmentListBySessionId 								= new Map<Id,List<Session_Attachment__c>>();
        List<Session_Attachment__c> attachmentsUnderSession 										= new List<Session_Attachment__c>();
        List<CE_Modules__c> CEModulesList 															= new List<CE_Modules__c>();
        List<CE_Session__c> sessionsList 															= new List<CE_Session__c>();
        GetDetailedCourseEnrolledDetailsWrapper wrapInstance 										= new GetDetailedCourseEnrolledDetailsWrapper();
        wrapInstance.Result 																		= New List<GetDetailedCourseEnrolledDetailsWrapper.cls_result>();
        GetDetailedCourseEnrolledDetailsWrapper.cls_result enrollWrap 								= new GetDetailedCourseEnrolledDetailsWrapper.cls_result();
        enrollWrap.modules 																			= new List<GetDetailedCourseEnrolledDetailsWrapper.cls_modules>();
        
        if(!String.isBlank(enrolmentId) && userType == 'instructor'){
            CEModulesList 																			= WS_CourseEnrollmentDetailsModel.getCEModules(enrolmentId);
            if(!CEModulesList.isEmpty()){
                for(CE_Modules__c moduleRec : CEModulesList)
                    moduleIds.add(moduleRec.Id); 
                if(!moduleIds.isEmpty()){
                    sessionsList 																	= WS_CourseEnrollmentDetailsModel.getCESessions(moduleIds);
                    if(!sessionsList.isEmpty()){
                        CESessionsByModuleId 														= WS_CourseEnrollmentDetailsHelper.getSessionByModule(sessionsList);
                        if(!sessionIds.isEmpty()){
                            attachmentsUnderSession 												= WS_CourseEnrollmentDetailsModel.getCESessionAtt(sessionIds);
                            if(!attachmentsUnderSession.isEmpty()){
                                attachmentListBySessionId 											= WS_CourseEnrollmentDetailsHelper.getAttachmentBySession(attachmentsUnderSession);
                            }
                        }
                    }                   
                }
            }
            
            if(userType.containsIgnoreCase('instructor')){
                Course_Enrollment__c mentorCourseEnrollment 										= WS_CourseEnrollmentDetailsModel.getMentorCE(enrolmentId);
                if(mentorCourseEnrollment != null){
                    enrollWrap.mentee  																= WS_CourseEnrollmentDetailsModel.getMenteesEnrolledUnder(mentorCourseEnrollment.Course_Master__c, mentorCourseEnrollment.Contact__c, 'Course Completed');
                    enrollWrap.mentee.add(mentorCourseEnrollment);
                }
            }
            if(!CEModulesList.isEmpty()){
                for(CE_Modules__c module : CEModulesList){
                    GetDetailedCourseEnrolledDetailsWrapper.cls_modules moduleWrap 					= new GetDetailedCourseEnrolledDetailsWrapper.cls_modules();
                    moduleWrap.moduleRec 															= module;
                    moduleWrap.sessions 															= new List<GetDetailedCourseEnrolledDetailsWrapper.cls_sessions>();
                    if(CESessionsByModuleId.containsKEy(module.Id))
                        for(CE_Session__c sessions : CESessionsByModuleId.get(module.Id)){
                            List<Session_Attachment__c> mentorsAtachment 							= new List<Session_Attachment__c>();
                            List<Session_Attachment__c> menteesAtachment 							= new List<Session_Attachment__c>();
                            
                            GetDetailedCourseEnrolledDetailsWrapper.cls_sessions sessionWrap 		= new GetDetailedCourseEnrolledDetailsWrapper.cls_sessions();
                            sessionWrap.session = sessions;
                            if(attachmentListBySessionId.containsKey(sessions.Id))
                                for(Session_Attachment__c attachmentRec : attachmentListBySessionId.get(sessions.Id)){
                                    if(attachmentRec.Attachment_Type__c == Constants.SESSION_ATTACHMENT_TYPE_ASSESSMENT){
                                        menteesAtachment.add(attachmentRec);
                                    }
                                    else if(attachmentRec.Attachment_Type__c == Constants.SESSION_ATTACHMENT_TYPE_NOTE){
                                        mentorsAtachment.add(attachmentRec);
                                    }
                                    sessionWrap.attachmentsByMentor 								= mentorsAtachment;
                                    sessionWrap.attachmentsByMentee 								= menteesAtachment;
                                }
                            moduleWrap.sessions.add(sessionWrap);
                        }
                    enrollWrap.modules.add(moduleWrap);
                }
            }
            wrapInstance.Result.add(enrollWrap);
        }else{
            try{            
                //system.debug('In student');
                if(userType.containsIgnoreCase('student')){
                    //system.debug('In student');
                    Course_Enrollment__c studentCourseEnrollment 										= WS_CourseEnrollmentDetailsModel.getStudentCE(enrolmentId);
                    system.debug('studentCourseEnrollment::'+studentCourseEnrollment);
                    if(studentCourseEnrollment != null){
                        system.debug('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
                        Course_Enrollment__c mentorCourseEnrollment 									= WS_CourseEnrollmentDetailsModel.getMentorsEnrollment(studentCourseEnrollment.Course_Master__c, studentCourseEnrollment.Mentor__c, 'Course Completed');
                        system.debug('mentorCourseEnrollment::'+mentorCourseEnrollment);
                        allMenteesPlusMentor.add(studentCourseEnrollment.Id);
                        enrollWrap.mentee  																= WS_CourseEnrollmentDetailsModel.getMenteesEnrolledUnder(studentCourseEnrollment.Course_Master__c, studentCourseEnrollment.Mentor__c, 'Course Completed');
                        system.debug('enrollWrap.mentee::'+enrollWrap.mentee);
                        enrollWrap.mentee.add(mentorCourseEnrollment);
                    }
                }
                String mentorsCEID 																		= WS_CourseEnrollmentDetailsModel.getMentorCEFromStudentsCe(enrolmentId);
                CEModulesList 																			= WS_CourseEnrollmentDetailsModel.getCEModules(mentorsCEID);
                if(!CEModulesList.isEmpty()){
                    for(CE_Modules__c moduleRec : CEModulesList){
                        moduleIds.add(moduleRec.Id);
                    } 
                    if(!moduleIds.isEmpty()){
                        sessionsList 																	= WS_CourseEnrollmentDetailsModel.getCESessions(moduleIds);
                        if(!sessionsList.isEmpty()){
                            CESessionsByModuleId = WS_CourseEnrollmentDetailsHelper.getSessionByModule(sessionsList);
                            if(!sessionIds.isEmpty()){
                                attachmentsUnderSession 												= WS_CourseEnrollmentDetailsModel.getCESessionAtt(sessionIds);
                                if(!attachmentsUnderSession.isEmpty()){
                                    for(Session_Attachment__c attRec : attachmentsUnderSession){
                                        if(attachmentListBySessionId.containsKey(attRec.CE_Session__c)){
                                            List<Session_Attachment__c> attachmentToBeAdded 			=  attachmentListBySessionId.get(attRec.CE_Session__c);
                                            attachmentToBeAdded.add(attRec);
                                            attachmentListBySessionId.put(attRec.CE_Session__c, attachmentToBeAdded);
                                        }else{
                                            attachmentListBySessionId.put(attRec.CE_Session__c, new List<Session_Attachment__c>{attRec});
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                
                enrollWrap.courseupdatelist 															= WS_CourseEnrollmentDetailsModel.getStudentCourseUpdate(enrolmentId);
                if(!CEModulesList.isEmpty()){
                    for(CE_Modules__c module : CEModulesList){
                        GetDetailedCourseEnrolledDetailsWrapper.cls_modules moduleWrap = new GetDetailedCourseEnrolledDetailsWrapper.cls_modules();
                        moduleWrap.moduleRec = module;
                        moduleWrap.sessions = new List<GetDetailedCourseEnrolledDetailsWrapper.cls_sessions>();
                        if(CESessionsByModuleId.containsKEy(module.Id))
                            for(CE_Session__c sessions : CESessionsByModuleId.get(module.Id)){
                                GetDetailedCourseEnrolledDetailsWrapper.cls_sessions sessionWrap 		= new GetDetailedCourseEnrolledDetailsWrapper.cls_sessions();
                                List<Session_Attachment__c> mentorsAtachment 							= new List<Session_Attachment__c>();
                                List<Session_Attachment__c> menteesAtachment 							= new List<Session_Attachment__c>();
                                sessionWrap.session 													= sessions;
                                
                                if(attachmentListBySessionId.containsKey(sessions.Id))
                                    for(Session_Attachment__c attachmentRec : attachmentListBySessionId.get(sessions.Id)){
                                        if(attachmentRec.Attachment_Type__c == Constants.SESSION_ATTACHMENT_TYPE_ASSESSMENT){
                                            menteesAtachment.add(attachmentRec);
                                        }
                                        else if(attachmentRec.Attachment_Type__c == Constants.SESSION_ATTACHMENT_TYPE_NOTE){
                                            mentorsAtachment.add(attachmentRec);
                                        }
                                        sessionWrap.attachmentsByMentor 								= mentorsAtachment;
                                        sessionWrap.attachmentsByMentee 								= menteesAtachment;
                                    }
                                moduleWrap.sessions.add(sessionWrap);
                            }
                        enrollWrap.modules.add(moduleWrap);
                    }
                }
                wrapInstance.Result.add(enrollWrap);}catch(exception ex){
                    //system.debug('Error::>'+ex.getMessage());
                    //system.debug('Error::>'+ex.getLineNumber());
                }
        }
        return wrapInstance;
    }
}