force-app/main/default/objects/CE_Modules__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Modules__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>CE-Modules</relationshipLabel>
    <relationshipName>CE_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <formula>CASESAFEID(CE_Module__r.Course_Enrollment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Enrollment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <formula>IF( OR( VALUE( MID( TEXT(   End_DateTime__c + 330/1440), 12, 2 ) ) = 0, VALUE( MID( TEXT( End_DateTime__c + 330/1440 ), 12, 2 ) ) = 12 ), &quot;12&quot;, TEXT( VALUE( MID( TEXT( End_DateTime__c + 330/1440 ), 12, 2 ) ) - IF( VALUE( MID( TEXT( End_DateTime__c + 330/1440), 12, 2 ) ) &lt; 12, 0, 12 ) ) ) &amp; &quot;:&quot; &amp; MID( TEXT( End_DateTime__c + 330/1440), 15, 2 ) &amp;&quot; &quot; &amp; IF( VALUE( MID( TEXT( End_DateTime__c + 330/1440 ), 12, 2 ) ) &lt; 12, &quot;AM&quot;, &quot;PM&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Meeting_Link__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Link__c</fullName>
    <label>Meeting Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.FirstName  +  CE_Module__r.Course_Enrollment__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor_Email__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Email__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor_Id__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Id__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Replanned_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Replanned_Date_Time__c</fullName>
    <label>Replanned Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Agenda__c.field-meta.xml
<CustomField>
    <fullName>Session_Agenda__c</fullName>
    <label>Session Agenda</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Duration__c.field-meta.xml
<CustomField>
    <fullName>Session_Duration__c</fullName>
    <formula>IF(ISNULL(Start_DateTime__c)|| ISNULL(End_DateTime__c),0,(End_DateTime__c-Start_DateTime__c)*24*60)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Session&apos;s Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Title__c.field-meta.xml
<CustomField>
    <fullName>Session_Title__c</fullName>
    <label>Session Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Start_Time_del__c.field-meta.xml
<CustomField>
    <fullName>Start_Time_del__c</fullName>
    <formula>IF( OR( VALUE( MID( TEXT(   Start_DateTime__c + 330/1440), 12, 2 ) ) = 0, VALUE( MID( TEXT( Start_DateTime__c + 330/1440 ), 12, 2 ) ) = 12 ), &quot;12&quot;, TEXT( VALUE( MID( TEXT( Start_DateTime__c + 330/1440 ), 12, 2 ) ) - IF( VALUE( MID( TEXT( Start_DateTime__c + 330/1440), 12, 2 ) ) &lt; 12, 0, 12 ) ) ) &amp; &quot;:&quot; &amp; MID( TEXT( Start_DateTime__c + 330/1440), 15, 2 ) &amp;&quot; &quot; &amp; IF( VALUE( MID( TEXT( Start_DateTime__c + 330/1440 ), 12, 2 ) ) &lt; 12, &quot;AM&quot;, &quot;PM&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Registered_By__c.field-meta.xml
<CustomField>
    <fullName>Registered_By__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registered By</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <description>This record type will be selected when a Mentor comes on platform for mentoring purpose</description>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Enrolled__c.field-meta.xml
<CustomField>
    <fullName>Enrolled__c</fullName>
    <formula>IF(Applied_by__c = &apos;Mentor&apos;,true,If(Course_Master__r.Paid_Course__c = false,true,If( ISPICKVAL(Payment_Order__r.Status__c, &apos;SUCCESS&apos;),true,false)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enrolled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Total_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Total_Sessions__c</fullName>
    <label>Total Sessions</label>
    <summarizedField>CE_Modules__c.Total_Session__c</summarizedField>
    <summaryForeignKey>CE_Modules__c.Course_Enrollment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Course_Master__c/fields/Average_review_rating__c.field-meta.xml
<CustomField>
    <fullName>Average_review_rating__c</fullName>
    <formula>Total_Reviews__c  /  Count_of_Ratings__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Average Review Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Course_Category__c.field-meta.xml
<CustomField>
    <fullName>Course_Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course Category</label>
    <referenceTo>Course_Category__c</referenceTo>
    <relationshipLabel>Course Masters</relationshipLabel>
    <relationshipName>Course_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Course_Price__c.field-meta.xml
<CustomField>
    <fullName>Course_Price__c</fullName>
    <label>Course Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Total_Mentor_Enrolments__c.field-meta.xml
<CustomField>
    <fullName>Total_Mentor_Enrolments__c</fullName>
    <label>Total Mentors Enrolments</label>
    <summaryFilterItems>
        <field>Course_Enrollment__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Mentor</value>
    </summaryFilterItems>
    <summaryForeignKey>Course_Enrollment__c.Course_Master__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Total_Reviews__c.field-meta.xml
<CustomField>
    <fullName>Total_Reviews__c</fullName>
    <label>Total Reviews</label>
    <summarizedField>Student_Feedback__c.Student_Rating__c</summarizedField>
    <summaryForeignKey>Student_Feedback__c.Course_Master__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Total_Session_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Session_Hours__c</fullName>
    <label>Total Session Hours</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Total_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Total_Sessions__c</fullName>
    <label>Total Session</label>
    <summarizedField>Course_Offering__c.Total_Sessions__c</summarizedField>
    <summaryForeignKey>Course_Offering__c.Course_Master__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Total_Student_Enrolments__c.field-meta.xml
<CustomField>
    <fullName>Total_Student_Enrolments__c</fullName>
    <label>Total Student Enrolments</label>
    <summaryFilterItems>
        <field>Course_Enrollment__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Student</value>
    </summaryFilterItems>
    <summaryForeignKey>Course_Enrollment__c.Course_Master__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Offering__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Offering__c/fields/Total_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Total_Sessions__c</fullName>
    <label>Total Sessions</label>
    <summaryForeignKey>Course_Schedule__c.Course_Offering__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/TrendingCourseandUpdate.cls
@RestResource(urlMapping='/get_course/*')
global class TrendingCourseandUpdate {
    @HttpGet
    global static MentorshipServiceModels.cls_courses_update getCoursesandUpdate(){
        RestRequest GetRequest = RestContext.request;
        RestResponse GetResponse = RestContext.response;
        String contactId = '';
        contactId = GetRequest.requestURI.substring(GetRequest.requestURI.lastIndexOf('/')+1);
        system.debug('contactId::'+contactId);
        map<string,list<Course_Master__c>> mapOfCategoriesbyCourseList = new map<string,list<Course_Master__c>>();
        list<Course_Master__c> courseMasterList = new list<Course_Master__c>();
        list<Top_Branding__c> brandingList = new list<Top_Branding__c>();
        List<CE_Session__c> upcomingCESessions = new List<CE_Session__c>();
        List<CE_Modules__c> CEModuleList = new List<CE_Modules__c>();
        List<CE_Session__c> CESessionsListToBeReturned = new List<CE_Session__c>();
        List<Course_Enrollment__c> mentorsCEList = new List<Course_Enrollment__c>();
        Set<Id> mentorCeIds = new Set<Id>();
        List<Course_Enrollment__c> mentorsCourseEnrollment = new List<Course_Enrollment__c>();
        
        Id mentorRecordId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Mentor').getRecordTypeId();
        //system.debug('mentorRecordId::'+mentorRecordId);
        if(contactId != '' && contactId != 'noid'){
            //system.debug('contactId::'+contactId);
            courseMasterList = [SELECT Id, Name, Description__c, Thumbnail_URL__c,Total_Reviews__c, Short_Description__c, Total_Mentor_Enrolments__c, Total_Student_Enrolments__c, Average_Review_Rating__c, Course_Price__c, Total_Session_Hours__c,Course_Category__c,Total_Sessions__c,Course_Category__r.Name,LastModifiedDate ,Discount__c,(SELECT Id,LastModifiedDate,Name FROM Course_Offerings__r) FROM Course_Master__c WHERE Active__c = true and Id NOT IN (SELECT Course_Master__c FROM Course_Enrollment__c where Contact__c =: contactId AND Enrolled__c =TRUE)]; 
            string appliedBy = [Select Registered_By__c From Contact WHERE id =: contactId].Registered_By__c;
            //system.debug('appliedBy::'+appliedBy);
            integer notificationDuration = integer.valueOf(System.Label.SessionNotificationTiming);
            //system.debug('notificationDuration::'+notificationDuration);
            if(appliedBy == 'Mentor'){
                time currentTime = system.now().time();
                
                mentorsCourseEnrollment = [Select Id From Course_Enrollment__c Where Contact__c =:contactId];
                //system.debug('mentorsCourseEnrollment::'+mentorsCourseEnrollment);
                for(Course_Enrollment__c mentorCERec : mentorsCourseEnrollment){
                    mentorCeIds.add(mentorCERec.id);
                }
                //system.debug('mentorCeIds::'+mentorCeIds);              
                upcomingCESessions = [SELECT End_DateTime__c,End_Time__c,Meeting_Link__c,Mentor_Email__c,Mentor_Id__c,Mentor__c,Name,Planned_Date__c,Replanned_Date_Time__c,Self_Paced__c,
                                      Session_Agenda__c,Session_Duration__c,Session_Title__c,Start_DateTime__c,Start_Time_del__c,Status__c,Video_Url__c 
                                      FROM CE_Session__c Where CE_Module__r.Course_Enrollment__c in : mentorCeIds AND Exact_Start_time__c >: currentTime AND Exact_Start_time__c < : currentTime.addMinutes(notificationDuration) AND Start_DateTime__c = Today];                       
                //system.debug('upcomingCESessions::'+upcomingCESessions);
            }else{
                time currentTime = system.now().time();
                mentorsCourseEnrollment = [Select Mentor_Course_Enrollment__c From Course_Enrollment__c Where Contact__c =:contactId];
                //system.debug('mentorsCourseEnrollment::'+mentorsCourseEnrollment);
                for(Course_Enrollment__c mentorCERec : mentorsCourseEnrollment){
                    mentorCeIds.add(mentorCERec.Mentor_Course_Enrollment__c);
                }
                //system.debug('mentorCeIds::'+mentorCeIds);
                upcomingCESessions = [SELECT End_DateTime__c,End_Time__c,Meeting_Link__c,Mentor_Email__c,Mentor_Id__c,Mentor__c,Name,Planned_Date__c,Replanned_Date_Time__c,Self_Paced__c,
                                      Session_Agenda__c,Session_Duration__c,Session_Title__c,Start_DateTime__c,Start_Time_del__c,Status__c,Video_Url__c 
                                      FROM CE_Session__c Where CE_Module__r.Course_Enrollment__c in : mentorCeIds  AND Exact_Start_time__c >: currentTime AND Exact_Start_time__c < : currentTime.addMinutes(notificationDuration) AND Start_DateTime__c = Today];
                
                //system.debug('upcomingCESessions::'+upcomingCESessions);
            }
            
        }else{
            courseMasterList = [SELECT Id, Name, Description__c,Total_Reviews__c, Thumbnail_URL__c, Short_Description__c, Total_Mentor_Enrolments__c, Total_Student_Enrolments__c, Average_Review_Rating__c, Course_Price__c, Total_Session_Hours__c,Course_Category__c,Total_Sessions__c,Course_Category__r.Name,Discount__c FROM Course_Master__c WHERE Active__c = true];
        }
        brandingList = [select id,Name,Brand_Description__c,Brand_Image__c from Top_Branding__c];
        
        if(!courseMasterList.isEmpty()){
            for(Course_Master__c csMaster : courseMasterList){
                if(mapOfCategoriesbyCourseList.containsKey(csMaster.Course_Category__r.Name)){
                    mapOfCategoriesbyCourseList.get(csMaster.Course_Category__r.Name).add(csMaster);
                }else{
                    mapOfCategoriesbyCourseList.put(csMaster.Course_Category__r.Name,new list<Course_Master__c>{csMaster});
                }
            }
        }
        list<MentorshipServiceModels.cls_daily_updates> dailyUpdateList = new list<MentorshipServiceModels.cls_daily_updates>();
        list<MentorshipServiceModels.cls_course_by_categories>  trendingCourseList = new list<MentorshipServiceModels.cls_course_by_categories>();
        if(!mapOfCategoriesbyCourseList.isEmpty()){
            for(string courseCategories : mapOfCategoriesbyCourseList.keySet()){
                MentorshipServiceModels.cls_course_by_categories courseCat = new MentorshipServiceModels.cls_course_by_categories();
                courseCat.course = new list<Course_Master__c>();
                courseCat.display_name = courseCategories;
                if(mapOfCategoriesbyCourseList.get(courseCategories) != null)
                    courseCat.course.addAll(mapOfCategoriesbyCourseList.get(courseCategories));
                trendingCourseList.add(courseCat);
                
            }
        }
        if(!brandingList.isEmpty()){
            for(Top_Branding__c tpBrand : brandingList){
                MentorshipServiceModels.cls_daily_updates dailyUpdate = new MentorshipServiceModels.cls_daily_updates();
                dailyUpdate.description = tpBrand.Brand_Description__c;
                dailyUpdate.title = tpBrand.Name;
                dailyUpdate.banner_url = tpBrand.Brand_Image__c;
                dailyUpdateList.add(dailyUpdate);
            }
        }
        
        MentorshipServiceModels.cls_courses_update courseUpdate = new MentorshipServiceModels.cls_courses_update();
        courseUpdate.cetegories = trendingCourseList;
        courseUpdate.dailyUpdate = dailyUpdateList;
        courseUpdate.all_mentors = [select Id,Contact_Role__c,Profile_Picture__c,Firebase_Id__c,Last_Hash_Code_Updated__c,Login_Hash_Code__c,Status__c,Total_Student_Enrolled__c,UID__c,
                                    Email,firstName,Mentor_Rating__c,Lastname,Initials__c,CreatedDate,Total_Experience__c,Current_Company__c,Current_Role__c,Public_Profile__c,(Select id,Name,Contact__r.Name,Course_Master_Name__c From Course_Enrollments__r) from contact where recordtypeid =: mentorRecordId AND Firebase_Id__c != null AND Public_Profile__c = TRUE];
        courseUpdate.upcomingCESessionsList = upcomingCESessions;
        courseUpdate.courseMasterList = [Select Id,Name FROM Course_Master__c];
        return courseUpdate;
    }
}