force-app/main/default/objects/CE_Session__c/fields/Assignment_Required__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assignment Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>CE-Sessions</relationshipLabel>
    <relationshipName>CE_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <formula>CASESAFEID(CE_Module__r.Course_Enrollment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Enrollment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Meeting_Link__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Link__c</fullName>
    <label>Meeting Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.FirstName  +  CE_Module__r.Course_Enrollment__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor_Email__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Email__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Replanned_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Replanned_Date_Time__c</fullName>
    <label>Replanned Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Agenda__c.field-meta.xml
<CustomField>
    <fullName>Session_Agenda__c</fullName>
    <label>Session Agenda</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Title__c.field-meta.xml
<CustomField>
    <fullName>Session_Title__c</fullName>
    <label>Session Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Video_Url__c.field-meta.xml
<CustomField>
    <fullName>Video_Url__c</fullName>
    <label>Video Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newly created</fullName>
            </value>
            <value>
                <fullName>Applied for Programme</fullName>
            </value>
            <value>
                <fullName>Mentorship Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <description>This record type will be selected when a Mentor comes on platform for mentoring purpose</description>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>This record type will be selected when a Student wants to get mentoring for a particular course</description>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/fields/Applied_by__c.field-meta.xml
<CustomField>
    <fullName>Applied_by__c</fullName>
    <formula>Contact__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applied by</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course_Offering__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Schedule__c/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <label>Course Module</label>
    <referenceTo>Course_Offering__c</referenceTo>
    <relationshipLabel>Course Sessions</relationshipLabel>
    <relationshipName>Course_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Schedule__c/fields/Self_Paced__c.field-meta.xml
<CustomField>
    <fullName>Self_Paced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Self Paced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Schedule__c/fields/Session_Agenda__c.field-meta.xml
<CustomField>
    <fullName>Session_Agenda__c</fullName>
    <label>Session Agenda</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>Test Masters</relationshipLabel>
    <relationshipName>Test_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Test Masters</relationshipLabel>
    <relationshipName>Test_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CESessionTriggerHelper_Test.cls
@isTest public class CESessionTriggerHelper_Test {
    @testSetup public static void creatingData(){
        Ass_Ques_Master__c assessmentQuestionMaster = UtilityClassForTestMethods.createAssementQuestionMaster('Assessment Master for Testing');
        insert assessmentQuestionMaster;
        system.debug('assessmentQuestionMaster::'+assessmentQuestionMaster);
        Assessment_Question__c assessmentQuestion =  UtilityClassForTestMethods.createAssessmentQuestion(assessmentQuestionMaster.Id,'Testing Question', 'Picklist', '1,2,3,4','2', 'Testing Category');
        insert assessmentQuestion;
        system.debug('assessmentQuestion::'+assessmentQuestion);
        Test_Master__c testMasterGeneric = UtilityClassForTestMethods.createTestMater('Testing course',assessmentQuestionMaster.Id, null, 'Generic');
        insert testMasterGeneric;
        Contact student = UtilityClassForTestMethods.insertContactRec('Aakash','Jain','aakash.jain@gmail.com','Student');
        insert student;
        Contact mentor = UtilityClassForTestMethods.insertContactRec('Shubham','Kumar','Shubham.Kumar@gmail.com','Mentor');
        insert mentor;
        Course_Master__c courseMaster = UtilityClassForTestMethods.createCourseMasterRec('Testing course', 'Testing Description', true);
        insert courseMaster;
        Course_Offering__c courseModule = UtilityClassForTestMethods.createModuleUnderCourseMAster('Testing Module',courseMaster.Id,'Testing MOdule Descrition',true,'Testing Module Agenda');
        insert courseModule;
        Course_Schedule__c courseSession = UtilityClassForTestMethods.createSessionUnderModule(courseModule.Id,'Testing Session Agenda','Testing Session Title');
        insert courseSession;  
        Course_Schedule__c courseSession1 = UtilityClassForTestMethods.createSessionUnderModule(courseModule.Id,'Testing Session Agenda1','Testing Session Title1');
        insert courseSession1; 
        Course_Schedule__c courseSession2 = UtilityClassForTestMethods.createSessionUnderModule(courseModule.Id,'Testing Session Agenda2','Testing Session Title2');
        insert courseSession2; 
        Course_Enrollment__c mentorsCE = UtilityClassForTestMethods.enrollForACourse(courseMaster.Id, 'Mentor',mentor.id,'Requested By Mentor',Date.newInstance(2021, 12, 31), 10);
        insert mentorsCE;
        Ass_Ques_Master__c assessmentQuestionMaster1 = UtilityClassForTestMethods.createAssementQuestionMaster('Assessment Master for Testing');
        insert assessmentQuestionMaster1;
        Test_Master__c testMasterPre = UtilityClassForTestMethods.createTestMater('Testing course',assessmentQuestionMaster1.Id, null, 'Pre');
        insert testMasterPre;
        Test_Master__c testMasterPost = UtilityClassForTestMethods.createTestMater('Testing course', assessmentQuestionMaster1.Id, null, 'Post');
        insert testMasterPost;
        Course_Enrollment__c studentCE = UtilityClassForTestMethods.enrollForACourse(courseMaster.Id, 'Student',student.id,'Requested By Student',null, null);
        insert studentCE;
    }
    @isTest public static void startingTest(){
        try{
            test.startTest();
            Course_Enrollment__c studentsCE = [Select id,Contact__c, Mentor__c,Mentor_Course_Enrollment__c,Status__c From Course_Enrollment__c Where Applied_by__c = 'Student'];
            Course_Enrollment__c mentorsCE = [Select id,Contact__c, Mentor__c,Mentor_Course_Enrollment__c,Status__c From Course_Enrollment__c Where Applied_by__c = 'Mentor'];
            studentsCE.Mentor__c = mentorsCE.Contact__c;
            studentsCE.Mentor_Course_Enrollment__c = mentorsCE.id;
            studentsCE.Status__c = 'Allocated For Mentoring';
            update studentsCE;
            
            List<CE_Session__c> CESessionList = [SELECT Assignment_Required__c,CE_Module__c,End_DateTime__c,Id,Meeting_Link__c,Mentor__c,Mentor_Email__c,Name,Session_Agenda__c,Planned_Date__c,Replanned_Date_Time__c,Self_Paced__c,Session_Title__c,Start_DateTime__c,Status__c,Video_Url__c FROM CE_Session__c ];
            system.debug('##################################################==>'+CESessionList.size());
            for(CE_Session__c sessionRec  : CESessionList){
                //for one day prior
                //system.debug('sessionRec==>'+sessionRec);
                if(sessionRec.Session_Agenda__c == 'Testing Session Agenda'){
                    //system.debug('sessionRec.Session_Agenda__c==>'+sessionRec.Session_Agenda__c);
                    sessionRec.Status__c = 'SCHEDULED';
                    
                    sessionRec.Start_DateTime__c = DateTime.Now().AddDays(1);
                    sessionRec.End_DateTime__c =  DateTime.Now().AddDays(1).addHours(1);
                }
                //on Same day
                if(sessionRec.Session_Agenda__c == 'Testing Session Agenda1'){
                    //system.debug('sessionRec.Session_Agenda__c==>'+sessionRec.Session_Agenda__c);
                    sessionRec.Status__c = 'SCHEDULED';
                    sessionRec.Start_DateTime__c = DateTime.Now();
                    sessionRec.End_DateTime__c =  DateTime.Now().addHours(1);
                }
                //on same day 1 hour prior
                if(sessionRec.Session_Agenda__c == 'Testing Session Agenda2'){
                    //system.debug('sessionRec.Session_Agenda__c==>'+sessionRec.Session_Agenda__c);
                    sessionRec.Status__c = 'SCHEDULED';
                    sessionRec.Start_DateTime__c = DateTime.Now();
                    sessionRec.End_DateTime__c =  DateTime.Now().addHours(1);
                }
            }
            update CESessionList;
            boolean runOnce = true;
            for(CE_Session__c CESession : CESessionList){
                if(runOnce){
                    database.delete(CESession.Id);
                    runOnce = false;
                }
            }
            test.stopTest();
        }catch(exception ex){
            //system.debug('Error=>'+ex.getLineNumber()+'Error=>'+ex.getMessage());
        }
    }
    @isTest static void testhandleSessionWhenStatusIsCancelled(){
        List<CE_Session__c> CESessionList = [SELECT Assignment_Required__c,CE_Module__c,End_DateTime__c,Id,Meeting_Link__c,Mentor__c,Mentor_Email__c,Name,Session_Agenda__c,Planned_Date__c,Replanned_Date_Time__c,Self_Paced__c,Session_Title__c,Start_DateTime__c,Status__c,Video_Url__c FROM CE_Session__c limit 1];
        CESessionList[0].Status__c = 'CANCELLED';
        update CESessionList;
    }
    @isTest static void testupdateNoOfHoursOnSession(){
        test.startTest();
        List<CE_Session__c> CESessionList = [SELECT Assignment_Required__c,CE_Module__c,End_DateTime__c,Id,Meeting_Link__c,Mentor__c,Mentor_Email__c,Name,Session_Agenda__c,Planned_Date__c,Replanned_Date_Time__c,Self_Paced__c,Session_Title__c,Start_DateTime__c,Status__c,Video_Url__c FROM CE_Session__c ];
        system.debug('##################################################==>'+CESessionList.size());
        for(CE_Session__c sessionRec  : CESessionList){
            //for one day prior
            //system.debug('sessionRec==>'+sessionRec);
            if(sessionRec.Session_Agenda__c == 'Testing Session Agenda'){
                //system.debug('sessionRec.Session_Agenda__c==>'+sessionRec.Session_Agenda__c);
                sessionRec.Status__c = 'SCHEDULED';
                
                sessionRec.Start_DateTime__c = DateTime.Now().AddDays(1);
                sessionRec.End_DateTime__c =  DateTime.Now().AddDays(1).addHours(1);
            }
            //on Same day
            if(sessionRec.Session_Agenda__c == 'Testing Session Agenda1'){
                //system.debug('sessionRec.Session_Agenda__c==>'+sessionRec.Session_Agenda__c);
                sessionRec.Status__c = 'SCHEDULED';
                sessionRec.Start_DateTime__c = DateTime.Now();
                sessionRec.End_DateTime__c =  DateTime.Now().addHours(1);
            }
            //on same day 1 hour prior
            if(sessionRec.Session_Agenda__c == 'Testing Session Agenda2'){
                //system.debug('sessionRec.Session_Agenda__c==>'+sessionRec.Session_Agenda__c);
                sessionRec.Status__c = 'SCHEDULED';
                sessionRec.Start_DateTime__c = DateTime.Now();
                sessionRec.End_DateTime__c =  DateTime.Now().addHours(1);
            }
        }
        update CESessionList;
        database.delete(CESessionList[0].id);
        test.stopTest();
    }
}