force-app/main/default/objects/CE_Session__c/fields/Assignment_Required__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assignment Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>CE-Sessions</relationshipLabel>
    <relationshipName>CE_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <formula>CASESAFEID(CE_Module__r.Course_Enrollment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Enrollment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Meeting_Link__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Link__c</fullName>
    <label>Meeting Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.FirstName  +  CE_Module__r.Course_Enrollment__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor_Email__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Email__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor_Id__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Id__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Replanned_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Replanned_Date_Time__c</fullName>
    <label>Replanned Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Agenda__c.field-meta.xml
<CustomField>
    <fullName>Session_Agenda__c</fullName>
    <label>Session Agenda</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Title__c.field-meta.xml
<CustomField>
    <fullName>Session_Title__c</fullName>
    <label>Session Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Video_Url__c.field-meta.xml
<CustomField>
    <fullName>Video_Url__c</fullName>
    <label>Video Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newly created</fullName>
            </value>
            <value>
                <fullName>Applied for Programme</fullName>
            </value>
            <value>
                <fullName>Mentorship Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Master_Name__c</fullName>
    <formula>Course_Master__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Master Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchForSessionNotification.cls
public class BatchForSessionNotification implements Database.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext BC){
        //Query all CE-Sessions whose Status is scheduled
        return Database.getQueryLocator([SELECT Assignment_Required__c,CE_Module__c,End_DateTime__c,Id,Meeting_Link__c,Mentor_Id__c,Mentor__c,Mentor_Email__c,Name,Session_Agenda__c,Planned_Date__c,Replanned_Date_Time__c,Self_Paced__c,Session_Title__c,Start_DateTime__c,Status__c,Video_Url__c FROM CE_Session__c Where Status__c = 'SCHEDULED' ]);
    }
    public void execute(Database.BatchableContext BC, List<CE_Session__c> CESessionsList){
        try{
            map<String, List<Course_Enrollment__c>> mapByMentorIdAndAssociatedStudents	= new map<String, List<Course_Enrollment__c>>();
            set<Id> mentorsId 															= new set<id>();
            set<id> studentsId 															= new set<id>();
            List<Course_Enrollment__c> studentListToBeNotifiedOneDayPrior 				= new List<Course_Enrollment__c>();
            List<CE_Session__c> mentorToBeNotifiedOneDayPrior 							= new List<CE_Session__c>();
            List<Course_Enrollment__c> studentListToBeNotifiedOneHourPrior 				= new List<Course_Enrollment__c>();  
            List<CE_Session__c> mentorToBeNotifiedOneHourPrior 							= new List<CE_Session__c>();
            
            List<Course_Enrollment__c> studentListToBeNotifiedonSameDay 				= new List<Course_Enrollment__c>(); 
            List<CE_Session__c> mentorToBeNotifiedonSameDay 							= new List<CE_Session__c>();  
            
            // getting course enrollements of students whose status is allocated for mentoring 
            List<Course_Enrollment__c> courseEnrollmentList = [SELECT Contact__r.Name,Contact__r.Email,Course_Master_Name__c,Mentor__c,Mentor__r.Name,Status__c  FROM Course_Enrollment__c Where Mentor__c != Null AND Status__c  = 'Allocated For Mentoring'];
            system.debug('courseEnrollmentList::'+courseEnrollmentList);
            for (Course_Enrollment__c courseEnrollment : courseEnrollmentList){
                if(mapByMentorIdAndAssociatedStudents.containsKey(courseEnrollment.Mentor__c)){
                    List<Course_Enrollment__c> addingStudentToList = mapByMentorIdAndAssociatedStudents.get(courseEnrollment.Mentor__c);
                    addingStudentToList.add(courseEnrollment);
                    mapByMentorIdAndAssociatedStudents.put(courseEnrollment.Mentor__c, addingStudentToList);
                }
                else{
                    mapByMentorIdAndAssociatedStudents.put(courseEnrollment.Mentor__c, new List<Course_Enrollment__c> {courseEnrollment});
                }
            }
            if(!CESessionsList.isEmpty()){
                for(CE_Session__c mentorCourseSchedule : CESessionsList){
                    if(mentorCourseSchedule.Replanned_Date_Time__c == null){
                        //system.debug('mentorCourseSchedule.Start_DateTime__c'+mentorCourseSchedule.Start_DateTime__c);
                        Date StartDate = mentorCourseSchedule.Start_DateTime__c.date();
                        //system.debug('StartDate'+StartDate);
                        Date newDate = StartDate.addDays(-1);
                        //system.debug('newDate'+newDate);
                        Time startTime = mentorCourseSchedule.Start_DateTime__c.time();
                        //system.debug('startTime'+startTime);
                        integer timeAvailable = 1;
                        if(newDate == system.today()){
                            //system.debug('In IF of one day prior');
                            studentListToBeNotifiedOneDayPrior = mapByMentorIdAndAssociatedStudents.get(mentorCourseSchedule.Mentor_Id__c);
                            mentorToBeNotifiedOneDayPrior.add( mentorCourseSchedule);
                            mentorsId.add(mentorCourseSchedule.Mentor_Id__c);
                        }
                        if(StartDate == system.today()){
                            //system.debug('In IF for same day');
                            studentListToBeNotifiedonSameDay = mapByMentorIdAndAssociatedStudents.get(mentorCourseSchedule.Mentor_Id__c);
                            studentListToBeNotifiedOneHourPrior = mapByMentorIdAndAssociatedStudents.get(mentorCourseSchedule.Mentor_Id__c);
                            mentorToBeNotifiedOneHourPrior.add(mentorCourseSchedule);
                            mentorToBeNotifiedonSameDay.add(mentorCourseSchedule);
                            mentorsId.add(mentorCourseSchedule.Mentor_Id__c);
                        }
                        if(StartDate == system.today()){
                            //system.debug('In IF for same day');
                            if((startTime.Hour() - system.now().time().hour()) <= timeAvailable){
                                //system.debug('In IFF of one hour prior');
                                studentListToBeNotifiedOneHourPrior = mapByMentorIdAndAssociatedStudents.get(mentorCourseSchedule.Mentor_Id__c);
                                mentorToBeNotifiedOneHourPrior.add(mentorCourseSchedule);
                                mentorsId.add(mentorCourseSchedule.Mentor_Id__c);
                            }
                        }
                    }
                    // In case session is Replanned 
                    else if(mentorCourseSchedule.Replanned_Date_Time__c != null){
                        //system.debug('mentorCourseSchedule.Replanned_Date_Time__c'+mentorCourseSchedule.Replanned_Date_Time__c);
                        Date StartDate = mentorCourseSchedule.Replanned_Date_Time__c.date();
                        //system.debug('StartDate'+StartDate);
                        Date newDate = StartDate.addDays(-1);
                        //system.debug('newDate'+newDate);
                        Time startTime = mentorCourseSchedule.Replanned_Date_Time__c.time();
                        //system.debug('startTime'+startTime);
                        integer timeAvailable = 1;
                        if(newDate == system.today()){
                            //system.debug('In IF of one day prior for Rescheduled session');
                            studentListToBeNotifiedOneDayPrior = mapByMentorIdAndAssociatedStudents.get(mentorCourseSchedule.Mentor_Id__c);
                            mentorToBeNotifiedOneDayPrior.add( mentorCourseSchedule);
                            mentorsId.add(mentorCourseSchedule.Mentor_Id__c);
                        }
                        if(StartDate == system.today()){
                            //system.debug('In IF for same day');
                            studentListToBeNotifiedonSameDay = mapByMentorIdAndAssociatedStudents.get(mentorCourseSchedule.Mentor_Id__c);
                            studentListToBeNotifiedOneHourPrior = mapByMentorIdAndAssociatedStudents.get(mentorCourseSchedule.Mentor_Id__c);
                            mentorToBeNotifiedOneHourPrior.add(mentorCourseSchedule);
                            mentorToBeNotifiedonSameDay.add(mentorCourseSchedule);
                            mentorsId.add(mentorCourseSchedule.Mentor_Id__c);
                        }
                        if(StartDate == system.today()){
                            //system.debug('In IFF for same day');
                            if((startTime.Hour() - system.now().time().hour()) <= timeAvailable){
                                //system.debug('In IFF of one hour prior for Rescheduled session');
                                studentListToBeNotifiedOneHourPrior = mapByMentorIdAndAssociatedStudents.get(mentorCourseSchedule.Mentor_Id__c);
                                mentorToBeNotifiedOneHourPrior.add(mentorCourseSchedule);
                                mentorsId.add(mentorCourseSchedule.Mentor_Id__c);
                            }
                        }
                    }
                }
                EmailHepler.sendSessionNotificationToStudents('Reminder For Session one Day Prior', studentListToBeNotifiedOneDayPrior);
                EmailHepler.sendSessionNotificationToMentors('Reminder For Session one Day Prior', mentorToBeNotifiedOneDayPrior);
                EmailHepler.sendSessionNotificationToStudents('Reminder For Session one Hour Prior', studentListToBeNotifiedOneHourPrior);
                EmailHepler.sendSessionNotificationToMentors('Reminder For Session one Hour Prior', mentorToBeNotifiedOneHourPrior);
                
                EmailHepler.sendSessionNotificationToStudents('Reminder For Session on Same Day', studentListToBeNotifiedonSameDay);
                EmailHepler.sendSessionNotificationToMentors('Reminder For Session on Same Day', mentorToBeNotifiedonSameDay);
                
            }
        }catch(exception ex){
            //system.debug('Error=>'+ex.getLineNumber()+'Error=>'+ex.getMessage());
        }
        
    }
    public void finish(Database.BatchableContext BC){
    }
}