force-app/main/default/objects/CE_Session__c/fields/Assignment_Required__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assignment Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>CE-Sessions</relationshipLabel>
    <relationshipName>CE_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <formula>CASESAFEID(CE_Module__r.Course_Enrollment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Enrollment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Meeting_Link__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Link__c</fullName>
    <label>Meeting Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.FirstName  +  CE_Module__r.Course_Enrollment__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor_Email__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Email__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Replanned_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Replanned_Date_Time__c</fullName>
    <label>Replanned Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Session_Agenda__c.field-meta.xml
<CustomField>
    <fullName>Session_Agenda__c</fullName>
    <label>Session Agenda</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Registered_By__c.field-meta.xml
<CustomField>
    <fullName>Registered_By__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registered By</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newly created</fullName>
            </value>
            <value>
                <fullName>Applied for Programme</fullName>
            </value>
            <value>
                <fullName>Mentorship Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <description>This record type will be selected when a Mentor comes on platform for mentoring purpose</description>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>This record type will be selected when a Student wants to get mentoring for a particular course</description>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/fields/Applied_by__c.field-meta.xml
<CustomField>
    <fullName>Applied_by__c</fullName>
    <formula>Contact__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applied by</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Payment_Order__c.field-meta.xml
<CustomField>
    <fullName>Payment_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Order</label>
    <referenceTo>Payment_Order__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course_Offering__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Schedule__c/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <label>Course Module</label>
    <referenceTo>Course_Offering__c</referenceTo>
    <relationshipLabel>Course Sessions</relationshipLabel>
    <relationshipName>Course_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Schedule__c/fields/Self_Paced__c.field-meta.xml
<CustomField>
    <fullName>Self_Paced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Self Paced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Schedule__c/fields/Session_Agenda__c.field-meta.xml
<CustomField>
    <fullName>Session_Agenda__c</fullName>
    <label>Session Agenda</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Payment_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>ABORTED</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Assessment_Result__c/fields/Assessment_Question__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Question</label>
    <referenceTo>Assessment_Question__c</referenceTo>
    <relationshipLabel>Student Assessment Results</relationshipLabel>
    <relationshipName>Student_Assessment_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Test_Master__c.field-meta.xml
<CustomField>
    <fullName>Test_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Master</label>
    <referenceTo>Test_Master__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>Test Masters</relationshipLabel>
    <relationshipName>Test_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Test Masters</relationshipLabel>
    <relationshipName>Test_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmailHeplerTest.cls
@isTest public class EmailHeplerTest {
    @testSetup public static void creatingDataForTest(){
        Ass_Ques_Master__c assessmentQuestionMaster = UtilityClassForTestMethods.createAssementQuestionMaster('Assessment Master for Testing');
        insert assessmentQuestionMaster;
        system.debug('assessmentQuestionMaster::'+assessmentQuestionMaster);
        Assessment_Question__c assessmentQuestion =  UtilityClassForTestMethods.createAssessmentQuestion(assessmentQuestionMaster.Id,'Testing Question', 'Picklist', '1,2,3,4','2', 'Testing Category');
        insert assessmentQuestion;
        system.debug('assessmentQuestion::'+assessmentQuestion);
        Test_Master__c testMasterGeneric = UtilityClassForTestMethods.createTestMater('Testing course',assessmentQuestionMaster.Id, null, 'Generic');
        insert testMasterGeneric;
        Contact student = UtilityClassForTestMethods.insertContactRec('Aakash','Jain','aakash.jain@gmail.com','Student');
        insert student;
        Contact student1 = UtilityClassForTestMethods.insertContactRec('BHaskar','Jha','Bhaskar.jha@gmail.com','Student');
        insert student1;
        Contact mentor = UtilityClassForTestMethods.insertContactRec('Shubham','Kumar','Shubham.Kumar@gmail.com','Mentor');
        insert mentor;
        Course_Master__c courseMaster = UtilityClassForTestMethods.createCourseMasterRec('Testing course', 'Testing Description', true);
        insert courseMaster;
        Course_Offering__c courseModule = UtilityClassForTestMethods.createModuleUnderCourseMAster('Testing Module',courseMaster.Id,'Testing MOdule Descrition',true,'Testing Module Agenda');
        insert courseModule;
        Course_Schedule__c courseSession = UtilityClassForTestMethods.createSessionUnderModule(courseModule.Id,'Testing Session Agenda','Testing Session Title');
        insert courseSession;
        Course_Schedule__c courseSession1 = UtilityClassForTestMethods.createSessionUnderModule(courseModule.Id,'Testing Session Agenda1','Testing Session Title1');
        insert courseSession1;
        Course_Schedule__c courseSession2 = UtilityClassForTestMethods.createSessionUnderModule(courseModule.Id,'Testing Session Agenda2','Testing Session Title2');
        insert courseSession2;
        Attachment att = UtilityClassForTestMethods.insertAttachment('Testing Attachment Name', 'Testing Blob Vlaue', courseMaster.Id);
        insert att;
        Ass_Ques_Master__c assessmentQuestionMaster1 = UtilityClassForTestMethods.createAssementQuestionMaster('Assessment Master for Testing');
        insert assessmentQuestionMaster1;
        Test_Master__c testMasterPre = UtilityClassForTestMethods.createTestMater('Testing course',assessmentQuestionMaster1.Id, null, 'Pre');
        insert testMasterPre;
        Test_Master__c testMasterPost = UtilityClassForTestMethods.createTestMater('Testing course', assessmentQuestionMaster1.Id, null, 'Post');
        insert testMasterPost;
        Course_Enrollment__c mentorsCE = UtilityClassForTestMethods.enrollForACourse(courseMaster.Id, 'Mentor',mentor.id,'Requested By Mentor',Date.newInstance(2021, 12, 31), 10);
        insert mentorsCE;
        Course_Enrollment__c studentCE = UtilityClassForTestMethods.enrollForACourse(courseMaster.Id, 'Student',student.id,'Requested By Student',null, null);
        insert studentCE;
    }
    @isTest public static void insertingPaymentOrderRecord(){
        test.startTest();
        String mentorId 					= [Select Id from Contact Where Registered_By__c = 'Mentor'].Id;
        Payment_Order__c paymentOrderRec = UtilityClassForTestMethods.insertPaymentOrder(1000, 'Stripe', 'testingOrderId123', 'SUCCESS', mentorId, 'testingTransactionId');
        insert paymentOrderRec;
        test.stopTest();
    }
    @isTest public static void sendPdf(){
        test.startTest();
        Course_Enrollment__c mentorCEId 	= 	[Select Id,Status__c from Course_Enrollment__c Where Applied_By__c = 'Mentor'];
        Attachment attUnderMentorCE = UtilityClassForTestMethods.insertAttachment('Unit Test Attachment', 'Testing Blob Vlaue', mentorCEId.Id);
        insert attUnderMentorCE;
        mentorCEId.Status__c				=	'Student Allocated';
        update mentorCEId;
        test.stopTest();
    }
    @isTest public static void sendSessionNotificationToStudentsTest(){
        test.startTest();
        List<CE_Session__c> CESessionList = [SELECT Assignment_Required__c,CE_Module__c,End_DateTime__c,Id,Meeting_Link__c,Mentor__c,Mentor_Email__c,Name,Session_Agenda__c,Planned_Date__c,Replanned_Date_Time__c,Self_Paced__c,Session_Title__c,Start_DateTime__c,Status__c,Video_Url__c FROM CE_Session__c ];
        //system.debug('##################################################==>'+CESessionList.size());
        for(CE_Session__c sessionRec  : CESessionList){
            //for one day prior
            if(sessionRec.Session_Agenda__c == 'Testing Session Agenda'){
                sessionRec.Status__c = 'SCHEDULED';
                sessionRec.Start_DateTime__c = DateTime.newInstance(2021, 09, 08, 11, 00, 00);
            }
            //on Same day prior
            if(sessionRec.Session_Agenda__c == 'Testing Session Agenda1'){
                sessionRec.Status__c = 'SCHEDULED';
                sessionRec.Start_DateTime__c = DateTime.newInstance(2021, 09, 07, 11, 00, 00);
            }
            //on same day 1 hour prior
            if(sessionRec.Session_Agenda__c == 'Testing Session Agenda2'){
                sessionRec.Status__c = 'SCHEDULED';
                sessionRec.Start_DateTime__c = DateTime.newInstance(2021, 09, 07, 15, 00, 00);
            }
        }
        update CESessionList;
        
        BatchForSessionNotification batchInstance = new BatchForSessionNotification();
        database.executeBatch(batchInstance);
        Test.stopTest();
    }
     @isTest public static void notifyMenteeAboutGenericTest(){
         test.startTest();
         Student_Test_Association__c staRec = [Select Id,Status__c From Student_Test_Association__c Where Test_Type__c  = 'Generic' limit 1];
         String assessmentQuestionRec = [Select Id From Assessment_Question__c limit 1].Id;
         Student_Assessment_Result__c assResult = new Student_Assessment_Result__c ();
         assResult.Assessment_Question__c = assessmentQuestionRec;
         assResult.Que_Category__c = 'Testing Category';
         assResult.Student_Test_Association__c = staRec.Id;
         assResult.Answer__c = '2';
         insert assResult;
         
         Student_Test_Association__c staRecToBeUpdated = new Student_Test_Association__c();
         staRecToBeUpdated.Id = staRec.Id;
         staRecToBeUpdated.Status__c = 'Completed';
         //update staRecToBeUpdated;
        test.stopTest();
    }
}