force-app/main/default/objects/CE_Session__c/fields/CE_Module__c.field-meta.xml
<CustomField>
    <fullName>CE_Module__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CE-Module</label>
    <referenceTo>CE_Modules__c</referenceTo>
    <relationshipLabel>CE-Sessions</relationshipLabel>
    <relationshipName>CE_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Attachment__c/fields/CE_Session__c.field-meta.xml
<CustomField>
    <fullName>CE_Session__c</fullName>
    <label>CE-Session</label>
    <referenceTo>CE_Session__c</referenceTo>
    <relationshipLabel>Session Attachments</relationshipLabel>
    <relationshipName>Session_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WS_CourseEnrollmentDetailsHelper.cls
public class WS_CourseEnrollmentDetailsHelper {
    public static Map<Id,List<CE_Session__c>> getSessionByModule(List<CE_Session__c> sessionsList){
        Map<Id,List<CE_Session__c>> CESessionsByModuleId 	= new Map<Id,List<CE_Session__c>> ();
        for(CE_Session__c sessionRec : sessionsList){
            WS_CourseEnrollmentDetails.sessionIds.add(sessionRec.Id);
            if(CESessionsByModuleId.containsKey(sessionRec.CE_Module__c)){
                List<CE_Session__c> sessionsToBeAdded 								= CESessionsByModuleId.get(sessionRec.CE_Module__c);
                sessionsToBeAdded.add(sessionRec);
                CESessionsByModuleId.put(sessionRec.CE_Module__c, sessionsToBeAdded);
            }else{
                CESessionsByModuleId.put(sessionRec.CE_Module__c,new List<CE_Session__c>{sessionRec});
            }
        } 
        return CESessionsByModuleId;
    }
    public static Map<Id,List<Session_Attachment__c>> getAttachmentBySession(List<Session_Attachment__c> attachmentsUnderSession){
        Map<Id,List<Session_Attachment__c>> attachmentListBySessionId 	= new Map<Id,List<Session_Attachment__c>> ();
        for(Session_Attachment__c attRec : attachmentsUnderSession){
            if(attachmentListBySessionId.containsKey(attRec.CE_Session__c)){
                List<Session_Attachment__c> attachmentToBeAdded 			=  attachmentListBySessionId.get(attRec.CE_Session__c);
                attachmentToBeAdded.add(attRec);
                attachmentListBySessionId.put(attRec.CE_Session__c, attachmentToBeAdded);
            }else{
                attachmentListBySessionId.put(attRec.CE_Session__c, new List<Session_Attachment__c>{attRec});
            }
        }
        return attachmentListBySessionId;
    }
}