force-app/main/default/objects/CE_Session__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <formula>CASESAFEID(CE_Module__r.Course_Enrollment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Enrollment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <formula>CE_Module__r.Course_Enrollment__r.Contact__r.FirstName  +  CE_Module__r.Course_Enrollment__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mentor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CE_Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newly created</fullName>
            </value>
            <value>
                <fullName>Applied for Programme</fullName>
            </value>
            <value>
                <fullName>Mentorship Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <description>This record type will be selected when a Mentor comes on platform for mentoring purpose</description>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>This record type will be selected when a Student wants to get mentoring for a particular course</description>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Payment_Order__c.field-meta.xml
<CustomField>
    <fullName>Payment_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Order</label>
    <referenceTo>Payment_Order__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course_Offering__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Schedule__c/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <label>Course Module</label>
    <referenceTo>Course_Offering__c</referenceTo>
    <relationshipLabel>Course Sessions</relationshipLabel>
    <relationshipName>Course_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>ABORTED</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Test Masters</relationshipLabel>
    <relationshipName>Test_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FirebaseUpcomingSessionDetailTest.cls
@isTest public class FirebaseUpcomingSessionDetailTest {
    @isTest static void pushCESessionDetailTest(){
        Ass_Ques_Master__c assessmentQuestionMaster = UtilityClassForTestMethods.createAssementQuestionMaster('Assessment Master for Testing');
        insert assessmentQuestionMaster;
        system.debug('assessmentQuestionMaster::'+assessmentQuestionMaster);
        Assessment_Question__c assessmentQuestion =  UtilityClassForTestMethods.createAssessmentQuestion(assessmentQuestionMaster.Id,'Testing Question', 'Picklist', '1,2,3,4','2', 'Testing Category');
        insert assessmentQuestion;
        system.debug('assessmentQuestion::'+assessmentQuestion);
        Test_Master__c testMasterGeneric = UtilityClassForTestMethods.createTestMater('Testing course',assessmentQuestionMaster.Id, null, 'Generic');
        insert testMasterGeneric;
        Contact student = UtilityClassForTestMethods.insertContactRec('Aakash','Jain','aakash.jain@gmail.com','Student');
        insert student;
        Contact mentor = UtilityClassForTestMethods.insertContactRec('Shubham','Kumar','Shubham.Kumar@gmail.com','Mentor');
        insert mentor;
        Course_Master__c courseMaster = UtilityClassForTestMethods.createCourseMasterRec('Testing course', 'Testing Description', true);
        insert courseMaster;
        Course_Offering__c courseModule = UtilityClassForTestMethods.createModuleUnderCourseMAster('Testing Module',courseMaster.Id,'Testing MOdule Descrition',true,'Testing Module Agenda');
        insert courseModule;
        Course_Schedule__c courseSession = UtilityClassForTestMethods.createSessionUnderModule(courseModule.Id,'Testing Session Agenda','Testing Session Title');
        insert courseSession;
        Course_Schedule__c courseSession1 = UtilityClassForTestMethods.createSessionUnderModule(courseModule.Id,'Testing Session Agenda1','Testing Session Title1');
        insert courseSession1;
        Course_Schedule__c courseSession2 = UtilityClassForTestMethods.createSessionUnderModule(courseModule.Id,'Testing Session Agenda2','Testing Session Title2');
        insert courseSession2;
        Course_Enrollment__c mentorsCE = UtilityClassForTestMethods.enrollForACourse(courseMaster.Id, 'Mentor',mentor.id,'Requested By Mentor',Date.newInstance(2021, 12, 31), 10);
        insert mentorsCE;
        Course_Enrollment__c studentCE = UtilityClassForTestMethods.enrollForACourse(courseMaster.Id, 'Student',student.id,'Requested By Student',null, null);
        insert studentCE;
        Payment_Order__c paymentOrderRec = UtilityClassForTestMethods.insertPaymentOrder(1000, 'Stripe', 'testingOrderId123', 'SUCCESS', studentCE.Contact__c, 'testingTransactionId');
        insert paymentOrderRec;
        test.startTest();
        
        studentCE.Mentor__c = mentorsCE.Contact__c;
        studentCE.Mentor_Course_Enrollment__c = mentorsCE.Id;
        studentCE.Payment_Order__c = paymentOrderRec.Id;
        
        Update studentCE;
        
        Integration_API_Configuration__c integrationFrameWork = UtilityClassForTestMethods.insertFrameworkConfigRec('UPCOMING_SESSION_NOTIFICATION', '/v1beta1/projects/mentorship-program-c8926/databases/(default)/documents:commit?key=', 'text/plain', 120000, '{"Accept":"*/*", "Accept-Encoding":"gzip, deflate, br"}', 'FirebaseUpcomingSessionDetail', true, 'POST', true, 'Firebase_Config');
        insert integrationFrameWork;
        
        List<Id> CESessionId = new List<Id>();
        List<CE_Session__c> CESessionList = [Select Id,Start_DateTime__c,End_DateTime__c,Status__c From CE_Session__c];
        for(CE_Session__c CESessionRec : CESessionList){
            CESessionId.add(CESessionRec.Id);
            CESessionRec.Start_DateTime__c = DateTime.now(); 
            CESessionRec.End_DateTime__c = DateTime.now().addHours(1);
            CESessionRec.Status__c = 'SCHEDULED'; 
        }
        update CESessionList;
        
        FirebaseUpcomingSessionDetail.pushCESessionDetail(CESessionId);
                test.stopTest();

    }
}