force-app/main/default/objects/Student_Test_Association__c/fields/Test_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Type__c</fullName>
    <formula>TEXT( Test_Master__r.Test_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StudentTestAsociationTrigger_Helper.cls
public class StudentTestAsociationTrigger_Helper {
   public static void notifyMenteesAboutModuleTest(Map<Id, Student_Test_Association__c> newStudentTestAssociationMap){
        //system.debug('After Student Test Association Creation'+newStudentTestAssociationMap);
        Set<Id> STAid = new Set<Id>();
        
        for(Student_Test_Association__c STA : newStudentTestAssociationMap.values()){
            if(STA.Test_Type__c == 'Module'){
                STAid.add(STA.Id);
            }
        }
       if(!STAid.isEmpty()){
           EmailHepler.notifyMenteeAboutModuleTest(STAid, 'Module Test Notificaton');
       }
    }
    public static void notifyMenteesAboutGenericTestResult(Map<Id, Student_Test_Association__c> newStudentTestAssociationMap, Map<Id, Student_Test_Association__c> oldStudentTestAssociationMap){
        Set<Id> STAid = new Set<Id>();

        for(Student_Test_Association__c STA : newStudentTestAssociationMap.values()){
            if(STA.Test_Type__c == 'Generic' && STA.Status__c != oldStudentTestAssociationMap.get(STA.Id).Status__c && STA.Status__c == 'Completed'){
                STAid.add(STA.Id);
            }
        }
       if(!STAid.isEmpty()){
           EmailHepler.notifyMenteeAboutGenericTest(STAid, 'Generic Test Result');
       }
    } 
}