force-app/main/default/objects/Integration_API_Configuration__c/fields/Adapter_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Adapter_Class_Name__c</fullName>
    <description>Name of the Class which handles this integration processing.</description>
    <inlineHelpText>Name of the Class which handles this integration processing.</inlineHelpText>
    <label>Adapter Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Additional_Header_Parameters__c.field-meta.xml
<CustomField>
    <fullName>Additional_Header_Parameters__c</fullName>
    <description>The key value pairs to be passed in the HTTP Request Header. Content type is passed in by default, based on the HTTP_Content_Type field. If there are other parameters, then they need to go here, as JSON key/value pairs.</description>
    <inlineHelpText>Key value pairs to be passed in the HTTP Request Header</inlineHelpText>
    <label>Additional Header Parameters</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/API_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>API_Endpoint__c</fullName>
    <description>The endpoint for the API for the third party system. For example in the D &amp; B system, the REST API endpoint for the &apos;Cleanse &amp; Match&apos; API is &apos;/V6.0/organizations&apos;.</description>
    <inlineHelpText>The endpoint for the API for the third party system</inlineHelpText>
    <label>API Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Concurrent_Process__c.field-meta.xml
<CustomField>
    <fullName>Concurrent_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Concurrent Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Disable_Logging__c.field-meta.xml
<CustomField>
    <fullName>Disable_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If true, integration logging feature will be disabled.</inlineHelpText>
    <label>Disable Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/HTTP_Content_Type__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Content_Type__c</fullName>
    <defaultValue>&quot;application/json&quot;</defaultValue>
    <description>The HTTP content type for this API, for example application/xml or application/json.</description>
    <inlineHelpText>HTTP content type for this API</inlineHelpText>
    <label>HTTP Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <description>The HTTP method to be invoked for this API. Typically GET or POST.</description>
    <inlineHelpText>The HTTP method to be invoked for this API</inlineHelpText>
    <label>HTTP Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Log_Request_and_Response_body__c.field-meta.xml
<CustomField>
    <fullName>Log_Request_and_Response_body__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, the request and response body would be logged.</description>
    <inlineHelpText>If true, the request and response body would be logged.</inlineHelpText>
    <label>Log Request and Response</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>The name of the Named Credential record that stores the authentication information needed to invoke this API, if any. The Integration_Configuration__c object stores the Named Credential information for the third party system, if the third party service provides separate authentication that&apos;s not API specific. Over and above that, the API_Named_Credential field stores API specific authentication information, if any.</description>
    <inlineHelpText>Name of the Named Credential record that stores the login credentials needed to invoke this API, if any</inlineHelpText>
    <label>API Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Number_Of_Retries__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Retries__c</fullName>
    <defaultValue>0</defaultValue>
    <description>If the response indicates that the request needs to be retied, or there is an http timeout, then the framework will retry the number of times specified in this field.</description>
    <inlineHelpText>Number of retries allowed for the integration request</inlineHelpText>
    <label>Number Of Retries</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Request_Timeout__c.field-meta.xml
<CustomField>
    <fullName>Request_Timeout__c</fullName>
    <defaultValue>120000</defaultValue>
    <description>HTTP timeout for the integration request, default value is 120 seconds.</description>
    <inlineHelpText>HTTP timeout for the integration request</inlineHelpText>
    <label>Request Timeout</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Response_Mock__c.field-meta.xml
<CustomField>
    <fullName>Response_Mock__c</fullName>
    <label>Response Mock</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/SObject_query_configuration__c.field-meta.xml
<CustomField>
    <fullName>SObject_query_configuration__c</fullName>
    <inlineHelpText>JSON configuration which would be queried and passed to Adapter</inlineHelpText>
    <label>SObject query configuration</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Static_Parameters__c.field-meta.xml
<CustomField>
    <fullName>Static_Parameters__c</fullName>
    <inlineHelpText>JSON key-value pair, the same would be passed down to the Adapter.</inlineHelpText>
    <label>Static Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Use_Response_Mocker__c.field-meta.xml
<CustomField>
    <fullName>Use_Response_Mocker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the response to this request needs to be mocked. Mock responses mimic the third party response.</description>
    <inlineHelpText>Indicates if the response to this request needs to be mocked</inlineHelpText>
    <label>Use Response Mocker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/API_Config_Id__c.field-meta.xml
<CustomField>
    <fullName>API_Config_Id__c</fullName>
    <description>The API type for which the request is being logged.</description>
    <inlineHelpText>The API type for which the request is being logged.</inlineHelpText>
    <label>API Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/End_Date_And_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_And_Time__c</fullName>
    <description>The date and time when the response was received from the external system.</description>
    <inlineHelpText>The date and time when the response was received from the external system.</inlineHelpText>
    <label>End Date And Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>Exception message if an internal exception has been thrown while processing the integration request or the response.</description>
    <inlineHelpText>Exception message if an internal exception has been thrown while processing the integration request or the response.</inlineHelpText>
    <label>Internal Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Processing_Time_Milliseconds__c.field-meta.xml
<CustomField>
    <fullName>Processing_Time_Milliseconds__c</fullName>
    <description>The roundtrip time taken to process the integration request.</description>
    <inlineHelpText>The roundtrip time taken to process the integration request</inlineHelpText>
    <label>Processing Time(Milliseconds)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Request_Log__c.field-meta.xml
<CustomField>
    <fullName>Request_Log__c</fullName>
    <description>The request log for the third party request. Depends on what the adapter chooses to log.</description>
    <inlineHelpText>The request log for the third party request.</inlineHelpText>
    <label>Request Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Response_Log__c.field-meta.xml
<CustomField>
    <fullName>Response_Log__c</fullName>
    <description>The response log for the third party response. Depends on what the adapter chooses to log.</description>
    <inlineHelpText>The response log for the third party response.</inlineHelpText>
    <label>Response Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Start_Date_And_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_And_Time__c</fullName>
    <description>The date and time when the request was sent to the external system.</description>
    <inlineHelpText>The date and time when the request was sent to the external system.</inlineHelpText>
    <label>Start Date And Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Processing status for the request sent to the third party system. Could be Success or Error.</description>
    <inlineHelpText>Processing status for the request sent to the third party system</inlineHelpText>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Third_Party_Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Error_Code__c</fullName>
    <description>The error code from the third party system.</description>
    <inlineHelpText>The error code from the third party system.</inlineHelpText>
    <label>Third Party Error Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Third_Party_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Error_Message__c</fullName>
    <description>Error message from the third party service while processing the integration request.</description>
    <inlineHelpText>Error message from the third party service while processing the integration request.</inlineHelpText>
    <label>Third Party Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/IntegrationServiceProcessor.cls
/*
* Author  : Prithvi
* Created : 2nd Nov
* Purpose : Integration core-processor.
*/

public class IntegrationServiceProcessor {
    private IntegrationAPIRepository repository;
    private Integration_API_Configuration__c apiConfiguration;
    private Datetime processingStartTime = DateTime.now();
    private String requestBody;
    private String responseBody;
    static List<Integration_Log__c> CONNCURRENT_LOG_LIST = new List<Integration_Log__c>();

    public IntegrationServiceProcessor(Integration_API_Configuration__c apiConfiguration, IntegrationAPIRepository repository) {
        this.apiConfiguration = apiConfiguration;
        this.repository = repository;
    }
    
    public IntegrationAPIResponse process(Map<String,Object> queryParameterMap, Map<String,Object> additionalParamsMap) {
        IntegrationAPIResponse apiResponse;
        try{ 
            BaseAPIAdapter adapter;
            if(apiConfiguration.Adapter_Class_Name__c != null)
                adapter = (BaseAPIAdapter)Type.forName(apiConfiguration.Adapter_Class_Name__c).newInstance(); 
            else 
                adapter = new BaseAPIAdapter();
            
            adapter.authenticate();

            Map<String, Object> queriedDataMap = new Map<String, Object>();
            if(apiConfiguration.SObject_query_configuration__c != null) {
                queriedDataMap = repository.getQueryResults(apiConfiguration.SObject_query_configuration__c, queryParameterMap);
            }
            requestBody = adapter.generateReqBody(getStaticParams(apiConfiguration.Static_Parameters__c, queriedDataMap), additionalParamsMap);
            IntegrationAPIRequest request = new IntegrationAPIRequest();
            if(requestBody != null)
                request.setBody(requestBody);
            this.configureRequest(request);
            adapter.createRequest(request.getRequest());
            HttpResponse response;
            if(apiConfiguration.Use_Response_Mocker__c) {   
                response = new HttpResponse();
                response.setBody(apiConfiguration.Response_Mock__c);
            }else {
                response = adapter.sendRequest(request.getRequest());
            }
            apiResponse = adapter.createResponse(response);
            responseBody = apiResponse.getResponse().getBody();
            if(!apiConfiguration.Disable_Logging__c)
                configureSuccessLog(apiResponse, new Integration_Log__c());
        }catch(Exception e) {
            if(!apiConfiguration.Disable_Logging__c)
                configureErroLog(e, new Integration_Log__c());
            return null;
        }
        return apiResponse;
    }    

    private void configureRequest(IntegrationAPIRequest request) {
        request.setEndpoint(this.getEndpoint());
        request.setMethod(apiConfiguration.HTTP_Method__c);
        request.setRetryCount(getIntegerFromDecimal(apiConfiguration.Number_Of_Retries__c) != null ? getIntegerFromDecimal(apiConfiguration.Number_Of_Retries__c) : 0);
        
        if(apiConfiguration.Request_Timeout__c != null)
            request.setTimeout(getIntegerFromDecimal(apiConfiguration.Request_Timeout__c));

        if(apiConfiguration.HTTP_Content_Type__c != null)
            request.setHeader(IntegrationFrameworkConstants.CONTENT_TYPE, apiConfiguration.HTTP_Content_Type__c);
        if(apiConfiguration.Additional_Header_Parameters__c != null) {
            Map<String,String> additionalHeaders = this.getHeaderParams(apiConfiguration.Additional_Header_Parameters__c);
            for(String header : additionalHeaders.keySet())
                request.setHeader(header, additionalHeaders.get(header));
        }
    }

    private Map<String,String> getHeaderParams(String jsonString) {
        return (Map<String,String>)JSON.deserializeStrict(jsonString, Map<String,String>.class);
    }

    private Map<String,Object> getStaticParams(String jsonString, Map<String,Object> staticParams) {
        if(!String.isBlank(jsonString)) {
            Map<String,Object> staticParamsUntypedMap = (Map<String,Object>)JSON.deserializeUntyped(jsonString);
            List<Object> valuesList = (List<Object>)staticParamsUntypedMap.get(IntegrationFrameworkConstants.JSON_VALUES_KEY);
            if(valuesList != null && !valuesList.isEmpty()) {
                for(Object valueMap : valuesList) {
                    Map<String,Object> jsonObject = (Map<String,Object>)valueMap;
                    if(jsonObject.containsKey(IntegrationFrameworkConstants.JSON_OBJECT_KEY) && jsonObject.containsKey(IntegrationFrameworkConstants.JSON_OBJECT_VALUE))
                        staticParams.put((String)jsonObject.get(IntegrationFrameworkConstants.JSON_OBJECT_KEY),(Object)jsonObject.get(IntegrationFrameworkConstants.JSON_OBJECT_VALUE));
                }
            }
            
        }
        return staticParams;
    }

    private String getEndpoint() {
        String endpoint = IntegrationFrameworkConstants.NAMED_CREDS_CALLOUT + apiConfiguration.Named_Credential__c;
        if(apiConfiguration.API_Endpoint__c != null)
            endpoint+=apiConfiguration.API_Endpoint__c;
        return endpoint;
    }

    private Integer getIntegerFromDecimal(Decimal value) {
        if(value != null)
            return Integer.valueOf(value);
        return null;
    }

    private void populateCommonLogFields(Integration_Log__c integrationLog) {
        integrationLog.Start_Date_And_Time__c = processingStartTime;
        integrationLog.API_Config_Id__c = apiConfiguration.API_Name__c;
        integrationLog.End_Date_And_Time__c = Datetime.now();
        integrationLog.Processing_Time_Milliseconds__c = getProcessingTimeInMilliSeconds();
        if(apiConfiguration.Log_Request_and_Response_body__c)
            integrationLog.Request_Log__c = requestBody;
    }

    private void configureSuccessLog(IntegrationAPIResponse apiResponse, Integration_Log__c integrationLog) {
        populateCommonLogFields(integrationLog);
        integrationLog.Status__c = IntegrationFrameworkConstants.INT_LOG_STATUS_SUCCESS;
        integrationLog.Third_Party_Error_Code__c = apiResponse.getThirdPartyErrorCode();
        integrationLog.Third_Party_Error_Message__c = apiResponse.getThirdPartyErrorMessage();
        if(apiConfiguration.Log_Request_and_Response_body__c)
            integrationLog.Response_Log__c = responseBody;
        CONNCURRENT_LOG_LIST.add(integrationLog);
        invokeLogAction();
    }

    private void configureErroLog(Exception e, Integration_Log__c integrationLog) {
        populateCommonLogFields(integrationLog);
        integrationLog.Status__c = IntegrationFrameworkConstants.INT_LOG_STATUS_ERROR;
        integrationLog.Exception_Message__c = prepareExceptionString(e);
        CONNCURRENT_LOG_LIST.add(integrationLog);
        invokeLogAction();
    }

    private void invokeLogAction() {
        if(!apiConfiguration.Concurrent_Process__c && !Test.isRunningTest()) {
            System.enqueueJob(new LogQueueable(CONNCURRENT_LOG_LIST));
        }
    }

    private Long getProcessingTimeInMilliSeconds() {
        return (DateTime.now().getTime() - processingStartTime.getTime());
    }

    private String prepareExceptionString(Exception e) {
        String exceptionString = '';
        exceptionString += IntegrationFrameworkConstants.INT_LOG_ERR_MSG + e.getMessage()+'\n';
        exceptionString += IntegrationFrameworkConstants.INT_LOG_ERR_LINE_NO + e.getLineNumber()+'\n';
        exceptionString += IntegrationFrameworkConstants.INT_LOG_ERR_TYPE + e.getTypeName()+'\n';
        exceptionString += IntegrationFrameworkConstants.INT_LOG_ERR_STK_TRACE + e.getStackTraceString();
        return exceptionString;
    }

    class LogQueueable implements Queueable {
        
        List<Integration_Log__c> logsToInsert;
        LogQueueable(List<Integration_Log__c> concurrentLogsList) {
            this.logsToInsert = concurrentLogsList;
        }

        public void execute(QueueableContext qc) {
            if(logsToInsert != null && !logsToInsert.isEmpty())
                IntegrationAPIRepository.getInstance().insertIntegrationLog(logsToInsert);
        }
    }
}