force-app/main/default/objects/Integration_API_Configuration__c/fields/Adapter_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Adapter_Class_Name__c</fullName>
    <description>Name of the Class which handles this integration processing.</description>
    <inlineHelpText>Name of the Class which handles this integration processing.</inlineHelpText>
    <label>Adapter Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Additional_Header_Parameters__c.field-meta.xml
<CustomField>
    <fullName>Additional_Header_Parameters__c</fullName>
    <description>The key value pairs to be passed in the HTTP Request Header. Content type is passed in by default, based on the HTTP_Content_Type field. If there are other parameters, then they need to go here, as JSON key/value pairs.</description>
    <inlineHelpText>Key value pairs to be passed in the HTTP Request Header</inlineHelpText>
    <label>Additional Header Parameters</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/API_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>API_Endpoint__c</fullName>
    <description>The endpoint for the API for the third party system. For example in the D &amp; B system, the REST API endpoint for the &apos;Cleanse &amp; Match&apos; API is &apos;/V6.0/organizations&apos;.</description>
    <inlineHelpText>The endpoint for the API for the third party system</inlineHelpText>
    <label>API Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Asynchronous_Operation__c.field-meta.xml
<CustomField>
    <fullName>Asynchronous_Operation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this API call is a long running operation. If set to true, the integration platform will execute the API call asynchronously.</description>
    <inlineHelpText>Indicates if this API call is a long running operation. If set to true, the integration platform will execute the API call asynchronously.</inlineHelpText>
    <label>Asynchronous Operation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Concurrent_Process__c.field-meta.xml
<CustomField>
    <fullName>Concurrent_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Concurrent Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Disable_Logging__c.field-meta.xml
<CustomField>
    <fullName>Disable_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If true, integration logging feature will be disabled.</inlineHelpText>
    <label>Disable Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/HTTP_Content_Type__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Content_Type__c</fullName>
    <defaultValue>&quot;application/json&quot;</defaultValue>
    <description>The HTTP content type for this API, for example application/xml or application/json.</description>
    <inlineHelpText>HTTP content type for this API</inlineHelpText>
    <label>HTTP Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <description>The HTTP method to be invoked for this API. Typically GET or POST.</description>
    <inlineHelpText>The HTTP method to be invoked for this API</inlineHelpText>
    <label>HTTP Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Log_Request_and_Response_body__c.field-meta.xml
<CustomField>
    <fullName>Log_Request_and_Response_body__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, the request and response body would be logged.</description>
    <inlineHelpText>If true, the request and response body would be logged.</inlineHelpText>
    <label>Log Request and Response</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>The name of the Named Credential record that stores the authentication information needed to invoke this API, if any. The Integration_Configuration__c object stores the Named Credential information for the third party system, if the third party service provides separate authentication that&apos;s not API specific. Over and above that, the API_Named_Credential field stores API specific authentication information, if any.</description>
    <inlineHelpText>Name of the Named Credential record that stores the login credentials needed to invoke this API, if any</inlineHelpText>
    <label>API Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Number_Of_Retries__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Retries__c</fullName>
    <defaultValue>0</defaultValue>
    <description>If the response indicates that the request needs to be retied, or there is an http timeout, then the framework will retry the number of times specified in this field.</description>
    <inlineHelpText>Number of retries allowed for the integration request</inlineHelpText>
    <label>Number Of Retries</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Request_Timeout__c.field-meta.xml
<CustomField>
    <fullName>Request_Timeout__c</fullName>
    <defaultValue>120000</defaultValue>
    <description>HTTP timeout for the integration request, default value is 120 seconds.</description>
    <inlineHelpText>HTTP timeout for the integration request</inlineHelpText>
    <label>Request Timeout</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Response_Mock__c.field-meta.xml
<CustomField>
    <fullName>Response_Mock__c</fullName>
    <label>Response Mock</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/SObject_query_configuration__c.field-meta.xml
<CustomField>
    <fullName>SObject_query_configuration__c</fullName>
    <inlineHelpText>JSON configuration which would be queried and passed to Adapter</inlineHelpText>
    <label>SObject query configuration</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Static_Parameters__c.field-meta.xml
<CustomField>
    <fullName>Static_Parameters__c</fullName>
    <inlineHelpText>JSON key-value pair, the same would be passed down to the Adapter.</inlineHelpText>
    <label>Static Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Use_Response_Mocker__c.field-meta.xml
<CustomField>
    <fullName>Use_Response_Mocker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the response to this request needs to be mocked. Mock responses mimic the third party response.</description>
    <inlineHelpText>Indicates if the response to this request needs to be mocked</inlineHelpText>
    <label>Use Response Mocker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IntegrationAPIRepository.cls
/*
* Author  : Prithvi
* Created : 2nd Nov
* Purpose : Repository class to interact with DB.
*/
public class IntegrationAPIRepository {
    
    static IntegrationAPIRepository repoInstance;
   @TestVisible private IntegrationAPIRepository(){}

    public static IntegrationAPIRepository getInstance() {
        if(repoInstance == null)
            repoInstance = new IntegrationAPIRepository();
        return repoInstance;
    }

    public Integration_API_Configuration__c getAPIConfigurationByName(String apiConfigName) {
        if(String.isBlank(apiConfigName))
            throw new IntegrationException(IntegrationFrameworkConstants.API_CONFIG_BLANK_ERROR);
        Integration_API_Configuration__c apiConfiguration;
        try{
            apiConfiguration = [SELECT Id, Adapter_Class_Name__c, API_Endpoint__c, Named_Credential__c, HTTP_Content_Type__c,API_Name__c,Use_Response_Mocker__c,Response_Mock__c, Disable_Logging__c,
                                                            HTTP_Method__c,Asynchronous_Operation__c,Number_Of_Retries__c,Static_Parameters__c,Request_Timeout__c,Additional_Header_Parameters__c,Log_Request_and_Response_body__c, SObject_query_configuration__c, Concurrent_Process__c
                                                            FROM Integration_API_Configuration__c WHERE API_Name__c = : apiConfigName];
        }catch(QueryException e) {
            throw new IntegrationException(IntegrationFrameworkConstants.NO_API_CONFIG_ERROR);
        }
        return apiConfiguration;
    }

    public void insertIntegrationLog(List<Integration_Log__c> integrationLogList) {
        insert integrationLogList;
    }

    private List<SObject> getQuery(String query) {
        return Database.query(query);
    }
    
    private String prepareQuery(SObjectConfigWrapper.Filters filter, Map<String,Object> queryParams) {
        String SObjectQuery = 'SELECT '+ String.join(filter.fields, ',') + ' FROM ' + filter.SObjectAPI;
        if(!String.isBlank(filter.whereClause)) {
            if(queryParams != null && !queryParams.isEmpty()) {
                for(String queryKey : queryParams.keySet()) {
                    if(filter.whereClause.contains(':'+queryKey)) {
                        Object queryInstance = queryParams.get(queryKey);
                        if(queryInstance != null) {
                            if(queryInstance instanceOf Integer) {
                                filter.whereClause = filter.whereClause.replaceAll(':'+queryKey, (String)queryInstance);
                            }else if(queryInstance instanceOf String) {
                                filter.whereClause = filter.whereClause.replaceAll(':'+queryKey, '\''+(String)queryInstance+'\'');
                            }else if(queryInstance instanceOf List<String>) {
                                String listValue = '(';
                                for(String param : (List<String>)queryInstance) {
                                    listValue += '\'' + param + '\'';
                                }
                                listValue += ')';
                                filter.whereClause = filter.whereClause.replaceAll(':'+queryKey, listValue);
                            }
                            else if(queryInstance instanceOf List<Integer> || queryInstance instanceOf List<Decimal>) {
                                String listValue = '(';
                                for(String param : (List<String>)queryInstance) {
                                    listValue += param;
                                }
                                listValue += ')';
                                filter.whereClause = filter.whereClause.replaceAll(':'+queryKey, listValue);
                            }
                        }
                        
                    }
                }
            }
            SObjectQuery += ' WHERE '+filter.whereClause;
        }
        if(!String.isBlank(filter.orderBy)) {
            SObjectQuery += ' ORDER BY '+filter.orderBy;
        }
        if(filter.limitTo != null) {
            SObjectQuery += ' LIMIT '+filter.limitTo;
        }
        System.debug('--- Framework query '+SObjectQuery);
        return SObjectQuery;
    }

    public Map<String, List<SObject>> getQueryResults(String jsonConfig, Map<String,Object> queryParams) {
        Map<String, List<SObject>> returnObject = new Map<String, List<SObject>>();
        if(!String.isBlank(jsonConfig)) {
            SObjectConfigWrapper configWrapper = SObjectConfigWrapper.parse(jsonConfig);
            if(configWrapper != null && configWrapper.filters != null && !configWrapper.filters.isEmpty()) {
                for(SObjectConfigWrapper.Filters filter : configWrapper.filters) {
                    if(filter.SObjectAPI != null && filter.SObjectAlias != null && filter.fields != null && !filter.fields.isEmpty()) {
                        returnObject.put(filter.SObjectAlias, getQuery(prepareQuery(filter, queryParams)));
                    }else {
                        throw new IntegrationException(IntegrationFrameworkConstants.QUERY_CONFIG_ERR_MESSAGE);
                    }
                }
            }
        }
        return returnObject;
    }
}