force-app/main/default/objects/Integration_API_Configuration__c/fields/API_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>API_Endpoint__c</fullName>
    <description>The endpoint for the API for the third party system. For example in the D &amp; B system, the REST API endpoint for the &apos;Cleanse &amp; Match&apos; API is &apos;/V6.0/organizations&apos;.</description>
    <inlineHelpText>The endpoint for the API for the third party system</inlineHelpText>
    <label>API Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Asynchronous_Operation__c.field-meta.xml
<CustomField>
    <fullName>Asynchronous_Operation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this API call is a long running operation. If set to true, the integration platform will execute the API call asynchronously.</description>
    <inlineHelpText>Indicates if this API call is a long running operation. If set to true, the integration platform will execute the API call asynchronously.</inlineHelpText>
    <label>Asynchronous Operation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <description>The HTTP method to be invoked for this API. Typically GET or POST.</description>
    <inlineHelpText>The HTTP method to be invoked for this API</inlineHelpText>
    <label>HTTP Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/SObject_query_configuration__c.field-meta.xml
<CustomField>
    <fullName>SObject_query_configuration__c</fullName>
    <inlineHelpText>JSON configuration which would be queried and passed to Adapter</inlineHelpText>
    <label>SObject query configuration</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_API_Configuration__c/fields/Static_Parameters__c.field-meta.xml
<CustomField>
    <fullName>Static_Parameters__c</fullName>
    <inlineHelpText>JSON key-value pair, the same would be passed down to the Adapter.</inlineHelpText>
    <label>Static Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/IntegrationFrameworkTest.cls
@isTest
public class IntegrationFrameworkTest {
    
    @TestSetup
    static void makeData() {
        List<Integration_API_Configuration__c> apiConfigList = new List<Integration_API_Configuration__c>();
        Integration_API_Configuration__c apiConfig = new Integration_API_Configuration__c(
            API_Endpoint__c = 'mock',
            API_Name__c = 'API_CONFIG',
            HTTP_Method__c = 'GET',
            Static_Parameters__c = '{"key":"test"}',
            SObject_query_configuration__c	 = '{'+
                '  "filters": ['+
                '    {'+
                '      "SObjectAPI": "Account",'+
                '      "SObjectAlias": "Account",'+
                '      "fields": ["Id","Name"],'+
                '      "whereClause": "Name != null AND Id IN :accountIds",'+
                '      "orderBy": "CreatedDate DESC"'+
                '    }'+
                '  ]'+
                '}'+
                ''
        );
        apiConfigList.add(apiConfig);

        Integration_API_Configuration__c apiConfigAsync = new Integration_API_Configuration__c(
            API_Endpoint__c = 'mock',
            API_Name__c = 'API_CONFIG_ASYNC',
            HTTP_Method__c = 'GET',
            Static_Parameters__c = '{"key":"test"}',
            Asynchronous_Operation__c = true
        );
        apiConfigList.add(apiConfigAsync);

        insert apiConfigList;

        Account account = new Account(Name = 'Test Account');
        insert account;
    }

    @IsTest
    static void syncTest(){
        Test.setMock(HttpCalloutMock.class, new Mock());
        Test.startTest();
        IntegrationService service = IntegrationFactory.getBaseIntegrationService();
        IntegrationAPIResponse response = service.runAPIService('API_CONFIG', new Map<String,Object>{'accountIds' => new List<Id> {[SELECT Id FROM Account LIMIT 1].Id}}, new Map<String,Object>());
        Test.stopTest();
        
    }


    @IsTest
    static void asyncTest(){
        Test.setMock(HttpCalloutMock.class, new Mock());
        Test.startTest();
        IntegrationService service = IntegrationFactory.getBaseIntegrationService();
        IntegrationAPIResponse response = service.runAPIService('API_CONFIG_ASYNC', new Map<String,Object>(), new Map<String,Object>());
        Test.stopTest();
        
    }

    @IsTest
    static void errorTest(){
        Test.setMock(HttpCalloutMock.class, new Mock());
        Test.startTest();
        IntegrationService service = IntegrationFactory.getBaseIntegrationService();
        IntegrationAPIResponse response = service.runAPIService('API_CONFIG');
        Test.stopTest();
        
    }

    @IsTest
    static void coverGeneric() {

        IntegrationAPIRequest apiRequest = new IntegrationAPIRequest();
        apiRequest.getBody();
        apiRequest.getEndpoint();
        apiRequest.getMethod();
        apiRequest.getRequest();
        apiRequest.getRetryCount();
        apiRequest.setBody('');
        apiRequest.setEndpoint('endpoint');
        apiRequest.setHeader('key', 'value');
        apiRequest.setMethod('POST');
        apiRequest.setRetryCount(0);
        apiRequest.setTimeout(12000);
        
        IntegrationAPIResponse apiResponse = new IntegrationAPIResponse(new HttpResponse());
        apiResponse.getProcessingErrorMessage();
        apiResponse.getprocessingStatus();
        apiResponse.getResponse();
        apiResponse.getResponseLog();
        apiResponse.getThirdPartyErrorCode();
        apiResponse.getThirdPartyErrorMessage();
        apiResponse.setProcessingErrorMessage('message');
        apiResponse.setThirdPartyErrorMessage('message');
        apiResponse.setServiceInvocationId('id');
        apiResponse.getStatusCode();
        apiResponse.getServiceInvocationId();
        apiResponse.setThirdPartyErrorCode('code');

        BaseAPIAdapter adapter = new BaseAPIAdapter();
        adapter.createRetryRequest(apiRequest, 0);
        adapter.isRetryNeeded(apiResponse);

       // IntegrationAPIRepository.getInstance().insertIntegrationLog(new List<uintegration__Integration_Log__c>{ new uintegration__Integration_Log__c() });
    }

    /* Mock class returns response from static resource depending on endpoint being called */
    private class Mock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
        
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"example": "test"}');
            res.setStatusCode(200);
            return res;
        }        
    }
      @IsTest
    static void insertIntegrationLogTest(){
        Test.startTest();
        List<Integration_Log__c> integrationFrameworkList = new List<Integration_Log__c>();
       
        IntegrationAPIRepository instance = new IntegrationAPIRepository();
        instance.insertIntegrationLog(integrationFrameworkList);
        IntegrationException newinstance =  new IntegrationException();
        Test.stopTest();
        
    }
    
}