force-app/main/default/objects/Integration_API_Configuration__c/fields/Asynchronous_Operation__c.field-meta.xml
<CustomField>
    <fullName>Asynchronous_Operation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this API call is a long running operation. If set to true, the integration platform will execute the API call asynchronously.</description>
    <inlineHelpText>Indicates if this API call is a long running operation. If set to true, the integration platform will execute the API call asynchronously.</inlineHelpText>
    <label>Asynchronous Operation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IntegrationService.cls
/*
* Author  : Prithvi
* Created : 2nd Nov
* Purpose : Service class.
*/
global class IntegrationService {

    private IntegrationAPIRepository repository;

    public IntegrationService(IntegrationAPIRepository repository) {
        this.repository = repository;
    }
    
    public IntegrationAPIResponse runAPIService(String apiConfigName) {
        return initiateService(apiConfigName, null, null);
    }

    public IntegrationAPIResponse runAPIService(String apiConfigName, Map<String,Object> queryParameterMap) {
        return initiateService(apiConfigName, queryParameterMap, null);
    }


    public IntegrationAPIResponse runAPIService(String apiConfigName, Map<String,Object> queryParameterMap, Map<String,Object> additionalParams) {
        return initiateService(apiConfigName, queryParameterMap, additionalParams);
    }

    private IntegrationAPIResponse initiateService(String apiConfigName, Map<String,Object> queryParameterMap, Map<String,Object> additionalParams) {
        Integration_API_Configuration__c apiConfiguration = repository.getAPIConfigurationByName(apiConfigName);
        if(apiConfiguration.Asynchronous_Operation__c) {
            System.enqueueJob(new IntegrationServiceProcessorQueueable(apiConfiguration, repository, queryParameterMap, additionalParams));
        }else {
            IntegrationServiceProcessor serviceProcessor = new IntegrationServiceProcessor(apiConfiguration, repository);
            return serviceProcessor.process(queryParameterMap, additionalParams);
        }
        return null;
    }    
    
}