force-app/main/default/objects/Course_Master__c/fields/Course_Price__c.field-meta.xml
<CustomField>
    <fullName>Course_Price__c</fullName>
    <label>Course Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Paid_Course__c.field-meta.xml
<CustomField>
    <fullName>Paid_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Total_Student_Enrolments__c.field-meta.xml
<CustomField>
    <fullName>Total_Student_Enrolments__c</fullName>
    <label>Total Student Enrolments</label>
    <summaryFilterItems>
        <field>Course_Enrollment__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Student</value>
    </summaryFilterItems>
    <summaryForeignKey>Course_Enrollment__c.Course_Master__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/getCourseAndEnrolledStudentsCount.cls
@RestResource(urlMapping='/get/CourseName/StudentsEnrolledUnder/*')
global class getCourseAndEnrolledStudentsCount {
    @HttpGet
    global static list<MentorshipServiceModels.courseNameAndCountOfStudent> courseNameWithCountOfStudent(){
        List<Course_Master__c> courseMasterList = [Select Name,Total_Student_Enrolments__c,Thumbnail_URL__c From Course_Master__c Where Paid_Course__c = true AND Course_Price__c > 0];
        list<MentorshipServiceModels.courseNameAndCountOfStudent> courseList = new List<MentorshipServiceModels.courseNameAndCountOfStudent>();
        for(Course_Master__c courseMasterRec : courseMasterList){
            MentorshipServiceModels.courseNameAndCountOfStudent wrapInstance = new MentorshipServiceModels.courseNameAndCountOfStudent();
            wrapInstance.CourseName = courseMasterRec.Name;
            wrapInstance.numberOfStudents = Integer.valueOf(courseMasterRec.Total_Student_Enrolments__c);
            wrapInstance.courseImageURL = courseMasterRec.Thumbnail_URL__c;
            courseList.add(wrapInstance);
        }
        return courseList;
    }
}