force-app/main/default/objects/Result_Category__c/fields/Percentage_Obtained__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Obtained__c</fullName>
    <formula>( Right_Answered_Ques__c  /  Total_Questions__c ) * 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percentage Obtained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Result_Category__c/fields/Right_Answered_Ques__c.field-meta.xml
<CustomField>
    <fullName>Right_Answered_Ques__c</fullName>
    <label>Right Answered Questions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Result_Category__c/fields/Student_Test_Association__c.field-meta.xml
<CustomField>
    <fullName>Student_Test_Association__c</fullName>
    <label>Student Test Association</label>
    <referenceTo>Student_Test_Association__c</referenceTo>
    <relationshipLabel>Result Categories</relationshipLabel>
    <relationshipName>Result_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Result_Category__c/fields/Total_Questions__c.field-meta.xml
<CustomField>
    <fullName>Total_Questions__c</fullName>
    <label>Total Questions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Total_Questions__c.field-meta.xml
<CustomField>
    <fullName>Total_Questions__c</fullName>
    <description>display total number of questions</description>
    <label>Total Questions</label>
    <summaryForeignKey>Student_Assessment_Result__c.Student_Test_Association__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/GetCategoryWiseResult.cls
@RestResource(urlMapping='/v1/Student_Test_Association__c/')
global with sharing class GetCategoryWiseResult {
    @HttpGet
    global static List<Result_Category__c> doGetResult() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        Map<String,String> paramsMap = RestContext.request.params;
        String studentTestAssociationId=paramsMap.get('id');
        //String studentTestAssociationId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        List<Result_Category__c> resultList = [SELECT Name,Percentage_Obtained__c,Right_Answered_Ques__c,Student_Test_Association__c,Total_Questions__c FROM Result_Category__c WHERE Student_Test_Association__c =: studentTestAssociationId];
       	//system.debug('studentTestAssociationId::'+studentTestAssociationId);
        //system.debug('resultList::'+resultList);
        return resultList;
    }
}