force-app/main/default/objects/Course_Offering__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CourseModuleTriggerHelper.cls
public class CourseModuleTriggerHelper {
    public static void attachPdfOnCourseMaster(Map<Id, Course_Offering__c> newCourseModuleMap){
        //System.debug('IN Course Module Trigger'+newCourseModuleMap);
        string courseMasterId = newCourseModuleMap.values()[0].Course_Master__c;
        //system.debug('courseMasterId::>>'+courseMasterId);
        CourseSessionPdfHelper.attachPDF(courseMasterId);
    }
}