force-app/main/default/objects/Course_Offering__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Schedule__c/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <label>Course Module</label>
    <referenceTo>Course_Offering__c</referenceTo>
    <relationshipLabel>Course Sessions</relationshipLabel>
    <relationshipName>Course_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CourseSessionTriggerHelper.cls
public class CourseSessionTriggerHelper {  
    public static void attachPdfOnCourseMaster(Map<Id, Course_Schedule__c> newCourseSessionMap){
        //System.debug('IN Course Session Trigger'+newCourseSessionMap);
        if(newCourseSessionMap.values()[0].Course_Offering__c != null){
            string courseModuleId = newCourseSessionMap.values()[0].Course_Offering__c;
            string courseMasterId = [SELECT Course_Master__c FROM Course_Offering__c WHERE Id =: courseModuleId].Course_Master__c;
            CourseSessionPdfHelper.attachPDF(courseMasterId);
        }
    }
}