force-app/main/default/objects/Course_Offering__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Offering__c/fields/Module_Weightage__c.field-meta.xml
<CustomField>
    <fullName>Module_Weightage__c</fullName>
    <formula>Total_Sessions__c  /Course_Master__r.Total_Sessions__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Module Weightage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Course_Schedule__c/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <label>Course Module</label>
    <referenceTo>Course_Offering__c</referenceTo>
    <relationshipLabel>Course Sessions</relationshipLabel>
    <relationshipName>Course_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Schedule__c/fields/Session_Agenda__c.field-meta.xml
<CustomField>
    <fullName>Session_Agenda__c</fullName>
    <label>Session Agenda</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Course_Schedule__c/fields/Session_s_Title__c.field-meta.xml
<CustomField>
    <fullName>Session_s_Title__c</fullName>
    <label>Session&apos;s Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CourseSessionPdfHelper.cls
global class CourseSessionPdfHelper {
    public static List<Course_Offering__c> courseModuleWithCourseSession    {get;set;}
    public String courseMasterId                                            {get; set;}
    public static string CourseName                                         {get;set;}
    public static string courseDescription                                  {get;set;}
    
    global CourseSessionPdfHelper (){
        List<Course_Offering__c> courseModulesList = new List<Course_Offering__c> ();
        courseMasterId = ApexPages.currentPage().getParameters().get('id');
        CourseName = [Select Name From Course_Master__c Where Id = :courseMasterId].Name;
        courseDescription = [Select Description__c From Course_Master__c Where Id = :courseMasterId].Description__c;
        //system.debug('courseMasterId::'+courseMasterId);
        courseModulesList = [SELECT Id FROM Course_Offering__c WHERE Course_Master__c =: courseMasterId];
        //system.debug('courseModulesList::'+courseModulesList);
        courseModuleWithCourseSession = [Select Id, Name,Module_Weightage__c,(Select Id,Session_Agenda__c,Session_s_Title__c From Course_Schedules__r) From Course_Offering__c Where Course_Master__c =: courseMasterId ];
        //system.debug('courseModuleWithCourseSession::'+courseModuleWithCourseSession);
        
    }
    @auraEnabled
    public static void attachPDFByLightningCmp(string courseMasterId){
        //system.debug('courseMasterId::'+courseMasterId);
        attachPDF(courseMasterId);
    }
    @Future(callout=true)
    global static void attachPDF(string courseMasterId) {
        //system.debug('courseMasterId::'+courseMasterId);
        PageReference pdfPage = Page.CourseSessionPDFpageClone;
        pdfPage.getParameters().put('id',courseMasterId);
        
        Blob pdfBlob;
        if(Test.isRunningTest()){
            pdfBlob = blob.valueof('TEST');
        }else{
            pdfBlob = pdfPage.getContent(); 
        }
        List<Attachment> attachmetsList = new List<Attachment> ();
        attachmetsList = [select id from Attachment where parentId = : courseMasterId]; 
        delete attachmetsList;
        
        Attachment attach = new Attachment(parentId = courseMasterId, Name = 'courseSession.pdf', body = pdfBlob); 
        insert attach;        
    }
}