force-app/main/default/objects/Contact/fields/Current_Company__c.field-meta.xml
<CustomField>
    <fullName>Current_Company__c</fullName>
    <label>Current Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Role__c.field-meta.xml
<CustomField>
    <fullName>Current_Role__c</fullName>
    <label>Current Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Facebook_Id__c.field-meta.xml
<CustomField>
    <fullName>Facebook_Id__c</fullName>
    <label>Facebook Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Firebase_Id__c.field-meta.xml
<CustomField>
    <fullName>Firebase_Id__c</fullName>
    <externalId>true</externalId>
    <label>Firebase Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Github_Id__c.field-meta.xml
<CustomField>
    <fullName>Github_Id__c</fullName>
    <label>Github Repository Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Instagram_Id__c.field-meta.xml
<CustomField>
    <fullName>Instagram_Id__c</fullName>
    <label>Instagram Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LinkedIn_Id__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Id__c</fullName>
    <label>LinkedIn Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Public_Profile__c.field-meta.xml
<CustomField>
    <fullName>Public_Profile__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Public Profile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Registered_By__c.field-meta.xml
<CustomField>
    <fullName>Registered_By__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registered By</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Student_Enrolled__c.field-meta.xml
<CustomField>
    <fullName>Total_Student_Enrolled__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Student Enrolled</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <description>This record type will be selected when a Mentor comes on platform for mentoring purpose</description>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Student_Feedback__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Students Feedback</relationshipLabel>
    <relationshipName>Students_Feedback</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/fields/Mentor_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Students Feedback (Mentor Course Enrollment)</relationshipLabel>
    <relationshipName>Students_Feedback1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/fields/Student_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Student_Course_Enrollment__c</fullName>
    <label>Student Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Students Feedback</relationshipLabel>
    <relationshipName>Students_Feedback</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/fields/Student_Rating__c.field-meta.xml
<CustomField>
    <fullName>Student_Rating__c</fullName>
    <label>Student Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/classes/UpcomingBatchDetailsHandler.cls
public class UpcomingBatchDetailsHandler{
    
    public static list<MentorshipServiceModels.mentor_details> topMentors(Set<id> coursId){
        list<Course_Enrollment__c> courseEnrollList = new list<Course_Enrollment__c>();
        list<AggregateResult> fd = new list<AggregateResult>();
        set<string> setofContactId = new set<string>();
        list<contact> contactList = new list<contact>();
        map<string,Decimal> mapofConIdByRating = new map<string,Decimal>();
        map<string,string> mapofConIdByConname = new map<string,string>();
        if(coursId == null){
            // fd = [select AVG(Student_Rating__c)sc,Student_Course_Enrollment__c,Student_Course_Enrollment__r.contact__r.name,Mentor_Course_Enrollment__r.Contact__c from Student_Feedback__c  GROUP BY Student_Course_Enrollment__c,Mentor_Course_Enrollment__r.Contact__c,Student_Course_Enrollment__r.contact__r.name];
            contactList = [select id,name,Firebase_Id__c,Total_Student_Enrolled__c,email,Profile_Picture__c,Current_Company__c,Current_Role__c,LinkedIn_Id__c,Github_Id__c,Instagram_Id__c,Facebook_Id__c,Public_Profile__c from contact where Registered_By__c = 'Mentor' AND Public_Profile__c = TRUE];            
            //system.debug('contactList::'+contactList);
            list<MentorshipServiceModels.mentor_details> mentorDetailsList = new list<MentorshipServiceModels.mentor_details>();
            if(!contactList.isEmpty()){
                for(contact con : contactList){
                    MentorshipServiceModels.mentor_details mentorrec = new MentorshipServiceModels.mentor_details();
                    mentorrec.contact_details = con;
                    mentorrec.rating = 1;
                    mentorDetailsList.add(mentorrec);
                }
            }
            
            //system.debug('mentorDetailsList::'+mentorDetailsList);
            mentorDetailsList.sort();
            //system.debug('aftermentorDetailsList::'+mentorDetailsList);
            return mentorDetailsList;
        }
        else{
            fd = [select AVG(Student_Rating__c)sc,Student_Course_Enrollment__c,Student_Course_Enrollment__r.contact__r.name,Mentor_Course_Enrollment__r.Contact__c from Student_Feedback__c Where Course_Master__c =: coursId  GROUP BY Student_Course_Enrollment__c,Mentor_Course_Enrollment__r.Contact__c,Student_Course_Enrollment__r.contact__r.name];
            //system.debug('fd::'+fd);
            for(AggregateResult  ar : fd){
                
                if(mapofConIdByRating.containsKey((string)ar.get('Contact__c'))){
                    //system.debug('logic::'+ar);
                    Decimal finalRating = 0;
                    finalRating = (mapofConIdByRating.get((string)ar.get('Contact__c')) + (Decimal)ar.get('sc')) / 2;
                    mapofConIdByRating.put((string)ar.get('Contact__c'),finalRating);
                }else{
                    mapofConIdByRating.put((string)ar.get('Contact__c'),(Decimal)ar.get('sc'));
                }
                
                if(!mapofConIdByConname.containsKey((string)ar.get('Contact__c'))){
                    mapofConIdByConname.put((string)ar.get('Contact__c'),(string)ar.get('Name'));
                }
                
            }
            if(!mapofConIdByRating.isEmpty()){
                for(string conId : mapofConIdByRating.keySet()){
                    setofContactId.add(conId);
                } 
                if(!setofContactId.isEmpty()){
                    //system.debug('setofContactId::'+setofContactId);
                    contactList = [select id,name,Firebase_Id__c,Total_Student_Enrolled__c,email,Profile_Picture__c,Current_Company__c,LinkedIn_Id__c,Github_Id__c,Instagram_Id__c,Facebook_Id__c from contact where id in: setofContactId];
                }
            }
            list<MentorshipServiceModels.mentor_details> mentorDetailsList = new list<MentorshipServiceModels.mentor_details>();
            if(!contactList.isEmpty()){
                for(contact con : contactList){
                    MentorshipServiceModels.mentor_details mentorrec = new MentorshipServiceModels.mentor_details();
                    mentorrec.contact_details = con;
                    mentorrec.rating = mapofConIdByRating.get(con.id);
                    mentorDetailsList.add(mentorrec);
                }
            }
            // system.debug('mentorDetailsList::'+mentorDetailsList);
            mentorDetailsList.sort();
            //system.debug('aftermentorDetailsList::'+mentorDetailsList);
            return mentorDetailsList;
        }
    }
}