force-app/main/default/objects/Contact/fields/Current_Company__c.field-meta.xml
<CustomField>
    <fullName>Current_Company__c</fullName>
    <label>Current Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Role__c.field-meta.xml
<CustomField>
    <fullName>Current_Role__c</fullName>
    <label>Current Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Employment_details__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employment detail</relationshipLabel>
    <relationshipName>Employment_detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employment_details__c/fields/Experience_in_Months__c.field-meta.xml
<CustomField>
    <fullName>Experience_in_Months__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Experience in Months</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EmploymentDetailTriggerHelper.cls
public class EmploymentDetailTriggerHelper {
    public static void updateCurrentCompanyAndRoleOnContact(Map<Id, Employment_details__c> newEmploymentDetailMap){
        //system.debug('newEmploymentDetailMap:: '+newEmploymentDetailMap);
        Set<Id> contactsId = new Set<Id>();
        List<Contact> contactWithEmploymentDetail = new List<Contact>();
        List<Contact> contactListToBeUpdated = new List<Contact>();
        
        for(Employment_details__c employmentRec : newEmploymentDetailMap.values()){
            contactsId.add(employmentRec.Contact__c);
        }
        if(!contactsId.isEmpty()){
            contactWithEmploymentDetail = [Select id,(SELECT Contact__c,CreatedById,CreatedDate,Occupation__c,Description__c,End_Date__c,Experience_in_Months__c,Id,Name,Start_Date__c FROM Employment_detail__r ORDER BY End_Date__c DESC NULLS LAST Limit 1) From Contact where Id in :contactsId];
        }
        if(!contactWithEmploymentDetail.isEmpty()){
            for(Contact con : contactWithEmploymentDetail){
                Contact contactToBeUpdated = new Contact();
                contactToBeUpdated.Id = con.Id;
                for(Employment_details__c employDetail : con.Employment_detail__r){
                    contactToBeUpdated.Current_Company__c = employDetail.Name != null? employDetail.Name: '';
                    contactToBeUpdated.Current_Role__c =  employDetail.Occupation__c != null? employDetail.Occupation__c: '' ;
                }
                contactListToBeUpdated.add(contactToBeUpdated);
            }
        }
        if(!contactListToBeUpdated.isEmpty()){
            update contactListToBeUpdated;
        }
    }
}