force-app/main/default/objects/Contact/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Enrolled__c.field-meta.xml
<CustomField>
    <fullName>Enrolled__c</fullName>
    <formula>IF(Applied_by__c = &apos;Mentor&apos;,true,If(Course_Master__r.Paid_Course__c = false,true,If( ISPICKVAL(Payment_Order__r.Status__c, &apos;SUCCESS&apos;),true,false)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enrolled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Enrollment_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Enrollment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Session_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Session_Percentage__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;Mentor&apos;, IF(Total_Sessions_Completed__c &gt; 0 &amp;&amp; Total_Sessions__c &gt; 0, Total_Sessions_Completed__c/Total_Sessions__c, 0),  IF(Total_Sessions_Completed_By_Student__c &gt; 0 &amp;&amp; Total_Session_of_Students__c&gt; 0, Total_Sessions_Completed_By_Student__c/Total_Session_of_Students__c, 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Session Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Students_Enrolled__c.field-meta.xml
<CustomField>
    <fullName>Students_Enrolled__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Students Enrolled</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <label>Total Hours</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Points</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Total_Session_of_Students__c.field-meta.xml
<CustomField>
    <fullName>Total_Session_of_Students__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Session of Students</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Total_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Total_Sessions__c</fullName>
    <label>Total Sessions</label>
    <summarizedField>CE_Modules__c.Total_Session__c</summarizedField>
    <summaryForeignKey>CE_Modules__c.Course_Enrollment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Total_Sessions_Completed__c.field-meta.xml
<CustomField>
    <fullName>Total_Sessions_Completed__c</fullName>
    <label>Total Sessions Completed</label>
    <summarizedField>CE_Modules__c.Total_Sessions_Completed__c</summarizedField>
    <summaryForeignKey>CE_Modules__c.Course_Enrollment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Total_Sessions_Completed_By_Student__c.field-meta.xml
<CustomField>
    <fullName>Total_Sessions_Completed_By_Student__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Sessions Completed By Student</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Total_Mentor_Enrolments__c.field-meta.xml
<CustomField>
    <fullName>Total_Mentor_Enrolments__c</fullName>
    <label>Total Mentors Enrolments</label>
    <summaryFilterItems>
        <field>Course_Enrollment__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Mentor</value>
    </summaryFilterItems>
    <summaryForeignKey>Course_Enrollment__c.Course_Master__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Total_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Total_Sessions__c</fullName>
    <label>Total Session</label>
    <summarizedField>Course_Offering__c.Total_Sessions__c</summarizedField>
    <summaryForeignKey>Course_Offering__c.Course_Master__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Total_Student_Enrolments__c.field-meta.xml
<CustomField>
    <fullName>Total_Student_Enrolments__c</fullName>
    <label>Total Student Enrolments</label>
    <summaryFilterItems>
        <field>Course_Enrollment__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Student</value>
    </summaryFilterItems>
    <summaryForeignKey>Course_Enrollment__c.Course_Master__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Students Feedback</relationshipLabel>
    <relationshipName>Students_Feedback</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/fields/Given_By__c.field-meta.xml
<CustomField>
    <fullName>Given_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Given By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Students Feedback</relationshipLabel>
    <relationshipName>Students_Feedback</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/fields/Mentor_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Students Feedback (Mentor Course Enrollment)</relationshipLabel>
    <relationshipName>Students_Feedback1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/fields/Student_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Student_Course_Enrollment__c</fullName>
    <label>Student Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Students Feedback</relationshipLabel>
    <relationshipName>Students_Feedback</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/fields/Student_Rating__c.field-meta.xml
<CustomField>
    <fullName>Student_Rating__c</fullName>
    <label>Student Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CourseEnrollmentswithRating.cls
@RestResource(urlMapping='/get_my_enrollments/*')
global class CourseEnrollmentswithRating {
    @HttpGet
    global static list<MentorshipServiceModels.cls_my_enrollments> upcomingBatch(){
        RestRequest GetRequest = RestContext.request;
        RestResponse GetResponse = RestContext.response;
        String contactId = '';
        contactId = GetRequest.requestURI.substring(GetRequest.requestURI.lastIndexOf('/')+1);
        set<string> courseMasterSet = new set<string>();
        list<Course_Enrollment__c> courseEnrollList = new list<Course_Enrollment__c >();
        list<Student_Feedback__c> studentReviewList = new list<Student_Feedback__c>();
        map<string,Course_Enrollment__c> mapofCourseEnrollById = new map<string,Course_Enrollment__c>();
        map<string,Student_Feedback__c> mapofReviewbyCoursId = new map<string,Student_Feedback__c>();
        list<MentorshipServiceModels.cls_my_enrollments> enrollRatingList = new list<MentorshipServiceModels.cls_my_enrollments>();
        if(contactId != ''){
            courseEnrollList = [SELECT Id, Name, Contact__c,Enrollment_Date__c,Mentor__r.Name,Mentor__r.FirstName,Mentor__r.LastName, Course_Master__c,Mentor__c,Mentor_Course_Enrollment__c, Course_Master__r.Total_Student_Enrolments__c, 
                                Students_Enrolled__c, Course_Master__r.Total_Mentor_Enrolments__c, Course_Master__r.Name, Course_Master__r.Short_Description__c, 
                                Course_Master__r.Thumbnail_URL__c,Total_Sessions__c,Total_Sessions_Completed__c,Total_Sessions_Completed_By_Student__c,Total_Session_of_Students__c,Session_Percentage__c,Total_Hours__c,Total_Points__c FROM Course_Enrollment__c WHERE Contact__c =: contactId AND Enrolled__c = True order by CreatedDate desc];

            if(!courseEnrollList.isEmpty()){
                for(Course_Enrollment__c courseEnroll : courseEnrollList){
                    mapofCourseEnrollById.put(courseEnroll.Course_Master__c,courseEnroll);
                    courseMasterSet.add(courseEnroll.Course_Master__c);
                }
            }

            if(!courseMasterSet.isEmpty()){
				studentReviewList = [select id,name,Course_Master__c,Description__c,Given_By__c,Mentor_Course_Enrollment__c,Student_Course_Enrollment__c,Student_Rating__c from Student_Feedback__c where Given_By__c =: contactId and Course_Master__c in: courseMasterSet];
                if(!studentReviewList.isEmpty()){
                    for(Student_Feedback__c studentReview : studentReviewList){
                        mapofReviewbyCoursId.put(studentReview.Course_Master__c,studentReview);
                    }
                }
            }
            if(!mapofCourseEnrollById.isEmpty()){
                for(string cmId : mapofCourseEnrollById.keySet()){
                    MentorshipServiceModels.cls_my_enrollments myEnrollments = new MentorshipServiceModels.cls_my_enrollments();
                    myEnrollments.course_enrollment =   mapofCourseEnrollById.get(cmId);
                    if(mapofReviewbyCoursId.get(cmId) != null)
                        myEnrollments.course_review = mapofReviewbyCoursId.get(cmId);
                    else
                        myEnrollments.course_review = null;
                    enrollRatingList.add(myEnrollments);
                }
            }

            //system.debug('enrollRatingList::'+enrollRatingList);
            
        }else{
            //system.debug('Error Handling');
        }
        return enrollRatingList;
    }
}