force-app/main/default/objects/Contact/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Firebase_Id__c.field-meta.xml
<CustomField>
    <fullName>Firebase_Id__c</fullName>
    <externalId>true</externalId>
    <label>Firebase Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Initials__c.field-meta.xml
<CustomField>
    <fullName>Initials__c</fullName>
    <formula>LEFT(FirstName, 1)+&apos;.&apos;+LEFT(LastName, 1)</formula>
    <label>Initials</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newly created</fullName>
            </value>
            <value>
                <fullName>Applied for Programme</fullName>
            </value>
            <value>
                <fullName>Mentorship Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <description>This record type will be selected when a Mentor comes on platform for mentoring purpose</description>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>This record type will be selected when a Student wants to get mentoring for a particular course</description>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/fields/Applied_by__c.field-meta.xml
<CustomField>
    <fullName>Applied_by__c</fullName>
    <formula>Contact__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applied by</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentoring_Fee__c.field-meta.xml
<CustomField>
    <fullName>Mentoring_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Mentoring Fee</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Payment_Order__c.field-meta.xml
<CustomField>
    <fullName>Payment_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Order</label>
    <referenceTo>Payment_Order__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Remaining_Slots__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Slots__c</fullName>
    <formula>Students_to_Be_Alloted__c  -  Students_Enrolled__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Slots</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Schedule_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Start_Date__c</fullName>
    <description>Thee date from which the mentor will take classes</description>
    <label>Schedule Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Students_to_Be_Alloted__c.field-meta.xml
<CustomField>
    <fullName>Students_to_Be_Alloted__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Students to Be Alloted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course_Master__c/fields/Average_review_rating__c.field-meta.xml
<CustomField>
    <fullName>Average_review_rating__c</fullName>
    <formula>Total_Reviews__c  /  Count_of_Ratings__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Average Review Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Course_Price__c.field-meta.xml
<CustomField>
    <fullName>Course_Price__c</fullName>
    <label>Course Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Paid_Course__c.field-meta.xml
<CustomField>
    <fullName>Paid_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Offering__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>ABORTED</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Students Feedback</relationshipLabel>
    <relationshipName>Students_Feedback</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/fields/Given_By__c.field-meta.xml
<CustomField>
    <fullName>Given_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Given By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Students Feedback</relationshipLabel>
    <relationshipName>Students_Feedback</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/fields/Mentor_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Students Feedback (Mentor Course Enrollment)</relationshipLabel>
    <relationshipName>Students_Feedback1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/fields/Student_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Student_Course_Enrollment__c</fullName>
    <label>Student Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Students Feedback</relationshipLabel>
    <relationshipName>Students_Feedback</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/fields/Student_Rating__c.field-meta.xml
<CustomField>
    <fullName>Student_Rating__c</fullName>
    <label>Student Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student_Feedback__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/classes/UpcomingBatchDetailsService.cls
@RestResource(urlMapping='/course/detail/*')
global with sharing class UpcomingBatchDetailsService {
    @HttpGet
    global static MentorshipServiceModels.cls_upcoming_batch upcomingBatch(){
        RestRequest GetRequest = RestContext.request;
        RestResponse GetResponse = RestContext.response;
        String courseId = '';
        courseId = GetRequest.requestURI.substring(GetRequest.requestURI.lastIndexOf('/')+1);
        //System.debug('courseId::'+courseId);
        list<Course_Master__c > courseMasterList = new list<Course_Master__c>();
        list<Course_Enrollment__c> courseEnrollList = new list<Course_Enrollment__c>();
        MentorshipServiceModels.cls_upcoming_batch upcomingBatch = new MentorshipServiceModels.cls_upcoming_batch();
        MentorshipServiceModels.Error errorUpdate = new MentorshipServiceModels.Error();
        if(courseId != ''){
            
            courseMasterList = [select Id, Name, Description__c, Thumbnail_URL__c, Short_Description__c, Course_Price__c, Paid_Course__c, Average_Review_Rating__c, 
            (SELECT Id, Name, Description__c FROM Course_Offerings__r WHERE Active__c = true Order By Order__c),
            (SELECT Id, Name, Given_By__c, Given_By__r.FirstName, Given_By__r.LastName, Given_By__r.Initials__c, Given_By__r.Profile_Picture__c,Course_Master__c,Description__c,Mentor_Course_Enrollment__c,Student_Course_Enrollment__c,Student_Rating__c,CreatedDate FROM Students_Feedback__r) 
            FROM Course_Master__c where Id=:courseId and Active__c = true limit 10];
			
            courseEnrollList = [select id,Schedule_Start_Date__c,Students_to_Be_Alloted__c,contact__r.Name,Mentoring_Fee__c,Remaining_Slots__c,Course_master__r.name,Course_master__r.Short_Description__c,Course_master__r.Thumbnail_URL__c,contact__r.Profile_Picture__c, contact__r.Firebase_Id__c from Course_Enrollment__c where 
            Course_Master__c =:courseId and (Status__c = 'Requested by Mentor' OR Status__c = 'Sessions Scheduled' ) AND Schedule_Start_Date__c > TODAY and Applied_by__c = 'Mentor' AND Remaining_Slots__c > 0 ORDER BY Schedule_Start_Date__c ASC NULLS LAST LIMIT 1];
            System.debug('courseEnrollList::'+courseEnrollList);
            if(courseMasterList.size() > 0)
                upcomingBatch.course_master = courseMasterList[0];
            upcomingBatch.upcoming_sessions = courseEnrollList;
            upcomingBatch.top_mentors = UpcomingBatchDetailsHandler.topMentors(new Set<Id>{courseId});
            upcomingBatch.menteesEnrollment = [select id,Schedule_Start_Date__c,Students_to_Be_Alloted__c,contact__r.Name,Mentoring_Fee__c,Remaining_Slots__c,Course_master__r.name,Course_master__r.Short_Description__c,Course_master__r.Thumbnail_URL__c,contact__r.Profile_Picture__c, contact__r.Firebase_Id__c,Payment_Order__c from Course_Enrollment__c where 
                                               Course_Master__c =:courseId and Applied_by__c = 'Student' AND Payment_Order__c != NULL];
        }else{
            errorUpdate.code = '400 Bad Request';
            errorUpdate.message = 'Course id not found';
            upcomingBatch.error = errorUpdate;
        }
        return upcomingBatch;
    }
}