force-app/main/default/objects/Contact/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Registered_By__c.field-meta.xml
<CustomField>
    <fullName>Registered_By__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registered By</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <description>This record type will be selected when a Mentor comes on platform for mentoring purpose</description>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/fields/Applied_by__c.field-meta.xml
<CustomField>
    <fullName>Applied_by__c</fullName>
    <formula>Contact__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applied by</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Count_of_Ratings__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Ratings__c</fullName>
    <label>Count of Ratings</label>
    <summaryForeignKey>Student_Feedback__c.Student_Course_Enrollment__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Schedule_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Start_Date__c</fullName>
    <description>Thee date from which the mentor will take classes</description>
    <label>Schedule Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Students_to_Be_Alloted__c.field-meta.xml
<CustomField>
    <fullName>Students_to_Be_Alloted__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Students to Be Alloted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Total_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Total_Sessions__c</fullName>
    <label>Total Sessions</label>
    <summarizedField>CE_Modules__c.Total_Session__c</summarizedField>
    <summaryForeignKey>CE_Modules__c.Course_Enrollment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Course_Master__c/fields/Average_review_rating__c.field-meta.xml
<CustomField>
    <fullName>Average_review_rating__c</fullName>
    <formula>Total_Reviews__c  /  Count_of_Ratings__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Average Review Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Count_of_Ratings__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Ratings__c</fullName>
    <label>Count of Ratings</label>
    <summaryForeignKey>Student_Feedback__c.Course_Master__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Course_Category__c.field-meta.xml
<CustomField>
    <fullName>Course_Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course Category</label>
    <referenceTo>Course_Category__c</referenceTo>
    <relationshipLabel>Course Masters</relationshipLabel>
    <relationshipName>Course_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Course_Price__c.field-meta.xml
<CustomField>
    <fullName>Course_Price__c</fullName>
    <label>Course Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Paid_Course__c.field-meta.xml
<CustomField>
    <fullName>Paid_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Total_Mentor_Enrolments__c.field-meta.xml
<CustomField>
    <fullName>Total_Mentor_Enrolments__c</fullName>
    <label>Total Mentors Enrolments</label>
    <summaryFilterItems>
        <field>Course_Enrollment__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Mentor</value>
    </summaryFilterItems>
    <summaryForeignKey>Course_Enrollment__c.Course_Master__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Total_Reviews__c.field-meta.xml
<CustomField>
    <fullName>Total_Reviews__c</fullName>
    <label>Total Reviews</label>
    <summarizedField>Student_Feedback__c.Student_Rating__c</summarizedField>
    <summaryForeignKey>Student_Feedback__c.Course_Master__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Total_Session_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Session_Hours__c</fullName>
    <label>Total Session Hours</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Total_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Total_Sessions__c</fullName>
    <label>Total Session</label>
    <summarizedField>Course_Offering__c.Total_Sessions__c</summarizedField>
    <summaryForeignKey>Course_Offering__c.Course_Master__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/TopMentorsAndUpcomingBatchWebsite.cls
@RestResource(urlMapping='/TopMentor/UpcomingBatch/CourseDetail/')
global with sharing class TopMentorsAndUpcomingBatchWebsite {
    @HttpGet
    global static MentorshipServiceModels.topMentorsAndUpcomingBatchForWebsite doGetMentorsUpcomingBatchAndCourseDetail(){
        MentorshipServiceModels.topMentorsAndUpcomingBatchForWebsite wrapInstance = new MentorshipServiceModels.topMentorsAndUpcomingBatchForWebsite ();
        List<Contact> contactList = new List<Contact>();
        List<Course_Enrollment__c> upcomingBatchDetails = new List<Course_Enrollment__c>();
        List<Course_Master__c> courseMasterDetails = new List<Course_Master__c> ();
        //wrapInstance.top_mentors = [SELECT FirstName,Name,Phone,Profile_Picture__c,LastName,Email FROM Contact  WHERE Registered_By__c = 'Mentor' limit 5];
        wrapInstance.top_mentors = UpcomingBatchDetailsHandler.topMentors(null);
        wrapInstance.upcoming_sessions = [select id,Schedule_Start_Date__c,Students_to_Be_Alloted__c,contact__r.Profile_Picture__c,contact__r.Name,Course_master__r.name,Course_master__r.Short_Description__c,Course_master__r.Thumbnail_URL__c from Course_Enrollment__c where Schedule_Start_Date__c > Today and Applied_by__c = 'Mentor'];
        wrapInstance.course_master = [SELECT Active__c,Average_review_rating__c,Brand__c,Count_of_Ratings__c,Course_Category__c,Course_Price__c,Description__c,Name,Order__c,Paid_Course__c,Short_Description__c,Thumbnail_URL__c,Total_Mentor_Enrolments__c,Total_Reviews__c,Total_Sessions__c,Total_Session_Hours__c FROM Course_Master__c];
        return wrapInstance;
    }
}