force-app/main/default/objects/Contact/fields/Facebook_Id__c.field-meta.xml
<CustomField>
    <fullName>Facebook_Id__c</fullName>
    <label>Facebook Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Firebase_Id__c.field-meta.xml
<CustomField>
    <fullName>Firebase_Id__c</fullName>
    <externalId>true</externalId>
    <label>Firebase Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Firebase_idToken__c.field-meta.xml
<CustomField>
    <fullName>Firebase_idToken__c</fullName>
    <label>Token Id From Firebase</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Github_Id__c.field-meta.xml
<CustomField>
    <fullName>Github_Id__c</fullName>
    <label>Github Repository Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Instagram_Id__c.field-meta.xml
<CustomField>
    <fullName>Instagram_Id__c</fullName>
    <label>Instagram Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LinkedIn_Id__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Id__c</fullName>
    <label>LinkedIn Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_To_FB__c.field-meta.xml
<CustomField>
    <fullName>Push_To_FB__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push To Firebase</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Qualification__c.field-meta.xml
<CustomField>
    <fullName>Qualification__c</fullName>
    <label>Qualification</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Registered_By__c.field-meta.xml
<CustomField>
    <fullName>Registered_By__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registered By</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <description>This record type will be selected when a Mentor comes on platform for mentoring purpose</description>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>This record type will be selected when a Student wants to get mentoring for a particular course</description>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentoring_Fee__c.field-meta.xml
<CustomField>
    <fullName>Mentoring_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Mentoring Fee</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Schedule_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Start_Date__c</fullName>
    <description>Thee date from which the mentor will take classes</description>
    <label>Schedule Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Students_to_Be_Alloted__c.field-meta.xml
<CustomField>
    <fullName>Students_to_Be_Alloted__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Students to Be Alloted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/classes/MentorCourseEnrollmentByWebsite.cls
@RestResource(urlMapping='/MentorCreationAndCourseEnrollment/')
global class MentorCourseEnrollmentByWebsite {
    @HttpPost global static MentorshipServiceModels.GenericResponse enrolMentor() {
        List<Contact> conList = new List<Contact>();
        Map<String,Id> contactIdByEmail = new Map<String,Id>();
        Contact cUser;
        Course_Enrollment__c mentorsCE;
        String[] combineFBIdAndToken;
        String usersFirebaseId; 
        String idToken;
        
        String requestJSON = RestContext.request.requestBody.toString();
        if(!String.isBlank(requestJSON)) {
            MentorshipServiceModels.MentorRegistraionFromWebsite mentorWrapper = (MentorshipServiceModels.MentorRegistraionFromWebsite) JSON.deserialize(requestJSON, MentorshipServiceModels.MentorRegistraionFromWebsite.class);
            if((mentorWrapper.email.length() > 0) && (mentorWrapper.userType.length() > 0)){
                conList = [Select Id,Email From Contact where Email != null AND Email =: mentorWrapper.email];
                if(!conList.isEmpty()){
                    return createErrorResponse(false, 'Email Already exists');
                }else{
                    String usersFirebaseIdAndIdToken 	= createUserOnFireBase.userCreation(mentorWrapper.email, mentorWrapper.firstName+'@12345');
                    if(!string.isBlank(usersFirebaseIdAndIdToken)){
                        combineFBIdAndToken     		= usersFirebaseIdAndIdToken.split(',');
                        usersFirebaseId         		= combineFBIdAndToken[0]; 
                        idToken          				= combineFBIdAndToken[1]; 
                    }
                    if(!String.isBlank(mentorWrapper.userType)) {
                        Account mentorHousehold = new Account(Name = mentorWrapper.lastName + ' Household');
                        insert mentorHousehold;
                        cUser = new Contact(AccountId = mentorHousehold.Id,Firebase_Id__c = usersFirebaseId, Firebase_idToken__c = idToken ,Email = mentorWrapper.email, FirstName = mentorWrapper.firstName, LastName = mentorWrapper.lastName,Gender__c= mentorWrapper.Gender ,Location__c = mentorWrapper.Location ,Qualification__c = mentorWrapper.Qualification ,Short_Description__c = mentorWrapper.ShortDescription , Phone = mentorWrapper.Phone,Facebook_Id__c =mentorWrapper.FacebookId ,Github_Id__c =mentorWrapper.GithubId ,Instagram_Id__c = mentorWrapper.InstagramId ,LinkedIn_Id__c =mentorWrapper.LinkedInId,Push_To_FB__c = false );
                        if(mentorWrapper.userType.equalsIgnoreCase('mentor')){
                            mentorWrapper.userType = 'Mentor';
                        }else if(mentorWrapper.userType.equalsIgnoreCase('student')){
                            mentorWrapper.userType = 'Student';
                        }
                        cUser.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(mentorWrapper.userType).getRecordTypeId();
                        try{
                            insert cUser;
                        }catch(Exception e){
                            return createErrorResponse(false, e.getMessage());
                        }
                        if(!String.isBlank(cUser.Id) && !String.isBlank(usersFirebaseId)){
                            DocumentCreationOnFireBase.createDocumentOnFB(cUser.Id);
                        }else{
                            return createErrorResponse(false, 'Either User creation failed in Salesforce or FireBase');
                        }
                        if(!String.isBlank(mentorWrapper.CourseMasterId)){
                            mentorsCE = new Course_Enrollment__c(Course_Master__c = mentorWrapper.CourseMasterId, Contact__c = cUser.Id, Schedule_End_Date__c = mentorWrapper.scheduleEndDate, Schedule_Start_Date__c = mentorWrapper.scheduleStartDate,Students_to_Be_Alloted__c = mentorWrapper.numberOfStudents,Mentoring_Fee__c = mentorWrapper.courseFee);
                            mentorsCE.RecordTypeId = Schema.SObjectType.Course_Enrollment__c.getRecordTypeInfosByName().get(mentorWrapper.userType).getRecordTypeId();
                            insert mentorsCE;
                            return createErrorResponse(true, 'User Created and enrolled under course');
                        }
                    }else{
                        return createErrorResponse(false, 'Please Provide UserType');
                    }
                }
            }else{
                return createErrorResponse(false, 'Please Provide Email/UserType');
            }
            Contact con = [Select Id, Registered_By__c From Contact Where id = : cUser.Id];
            if(con.Registered_By__c == 'Student'){
                return createErrorResponse(true, 'You have been Successfully Enrolled as a Mentee, We will shortly get in touch with you'); 
            }else{
                return createErrorResponse(true, 'You have been Successfully Enrolled as a Mentor, We will shortly get in touch with you');
            } 
        }else {
            return createErrorResponse(false, 'Invalid request.');
        }
    }
    global static MentorshipServiceModels.GenericResponse createErrorResponse(Boolean success, String message) {
        MentorshipServiceModels.GenericResponse genRes = new MentorshipServiceModels.GenericResponse();
        genRes.success = success;
        genRes.message = message;
        return genRes;
    }
}