force-app/main/default/objects/Contact/fields/Facebook_Id__c.field-meta.xml
<CustomField>
    <fullName>Facebook_Id__c</fullName>
    <label>Facebook Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Firebase_Id__c.field-meta.xml
<CustomField>
    <fullName>Firebase_Id__c</fullName>
    <externalId>true</externalId>
    <label>Firebase Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Github_Id__c.field-meta.xml
<CustomField>
    <fullName>Github_Id__c</fullName>
    <label>Github Repository Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Instagram_Id__c.field-meta.xml
<CustomField>
    <fullName>Instagram_Id__c</fullName>
    <label>Instagram Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LinkedIn_Id__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Id__c</fullName>
    <label>LinkedIn Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Qualification__c.field-meta.xml
<CustomField>
    <fullName>Qualification__c</fullName>
    <label>Qualification</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newly created</fullName>
            </value>
            <value>
                <fullName>Applied for Programme</fullName>
            </value>
            <value>
                <fullName>Mentorship Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor_Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StudentCourseEnrollmentBYWebsite.cls
@RestResource(urlMapping='/StudentCreationAndCourseEnrollment/')
global class StudentCourseEnrollmentBYWebsite {
 @HttpPost global static String enrolStudent() {
        String requestJSON = RestContext.request.requestBody.toString();
        //System.debug(requestJSON);
        if(!String.isBlank(requestJSON)) {
            MentorshipServiceModels.StudentRegistraionFromWebsite studentWrapper = (MentorshipServiceModels.StudentRegistraionFromWebsite) JSON.deserialize(requestJSON, MentorshipServiceModels.StudentRegistraionFromWebsite.class);
            //  system.debug('studentWrapper::'+studentWrapper);
            // system.debug('studentWrapper.firebaseId::'+studentWrapper.firebaseId);
            // system.debug('studentWrapper.email::'+studentWrapper.email);
            /*
            global String firebaseId;
       		global String email;
       	 	global String firstName;
        	global String lastName;
        	global String userType;
        	global String CourseMasterId;
    		global String gender;
            global String qualification;
            global String location;
            global String phone;
            global String shortDescription;
            global String currentCompany;
            global String currentRole;
            global String facebook;
            global String github;
            global String linkedIn;
            global String instagram;
    		*/
            Account studentHousehold = new Account(Name = studentWrapper.lastName + ' Household');
            insert studentHousehold;
            Contact cUser = new Contact(AccountId = studentHousehold.Id, Email = studentWrapper.email, Firebase_Id__c = studentWrapper.firebaseId, FirstName = studentWrapper.firstName, LastName = studentWrapper.lastName,Gender__c = studentWrapper.gender ,Location__c = studentWrapper.location ,Qualification__c = studentWrapper.qualification ,Short_Description__c = studentWrapper.shortDescription , Phone = studentWrapper.phone,Facebook_Id__c =studentWrapper.facebook ,Github_Id__c =studentWrapper.github ,Instagram_Id__c = studentWrapper.instagram ,LinkedIn_Id__c =studentWrapper.linkedIn );

            if(!String.isBlank(studentWrapper.userType)) {
                cUser.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(studentWrapper.userType).getRecordTypeId();
                insert cUser;
                //system.debug('---'+cUser);
                 Course_Enrollment__c studentsCE = new  Course_Enrollment__c ();
                if(!String.isBlank(studentWrapper.mentorsCEId)){
                    String mentorsContactId  = [Select Contact__c From Course_Enrollment__c where Id =: studentWrapper.mentorsCEId].Contact__c;
                    studentsCE = new Course_Enrollment__c(Course_Master__c = studentWrapper.CourseMasterId, Contact__c = cUser.Id,Mentor_Course_Enrollment__c = studentWrapper.mentorsCEId,Mentor__c = mentorsContactId,Status__c ='Allocated for Mentoring' );
                }
                else{
                    studentsCE = new Course_Enrollment__c(Course_Master__c = studentWrapper.CourseMasterId, Contact__c = cUser.Id);
                }
                studentsCE.RecordTypeId = Schema.SObjectType.Course_Enrollment__c.getRecordTypeInfosByName().get(studentWrapper.userType).getRecordTypeId();
                insert studentsCE;
                //system.debug('---'+studentsCE);
                
                return JSON.serialize(createSuccessResponse(cUser));
            }else {
                JSON.serialize(createErrorResponse(false, 'Invalid request.'));
            }
        
        }else {
            JSON.serialize(createErrorResponse(false, 'Missing required fields.'));
        }
     
     return null;
 }
    
    global static MentorshipServiceModels.Response createSuccessResponse(Object result) {
        MentorshipServiceModels.Response res = new MentorshipServiceModels.Response();
        res.result = result;
        return res;
    }
    
    global static MentorshipServiceModels.GenericResponse createErrorResponse(Boolean success, String message) {
        MentorshipServiceModels.GenericResponse genRes = new MentorshipServiceModels.GenericResponse();
        genRes.success = success;
        genRes.message = message;
        return genRes;
    }
    
}