force-app/main/default/objects/Contact/fields/Firebase_Id__c.field-meta.xml
<CustomField>
    <fullName>Firebase_Id__c</fullName>
    <externalId>true</externalId>
    <label>Firebase Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Contact ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_To_FB__c.field-meta.xml
<CustomField>
    <fullName>Push_To_FB__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push To Firebase</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Registered_By__c.field-meta.xml
<CustomField>
    <fullName>Registered_By__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registered By</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newly created</fullName>
            </value>
            <value>
                <fullName>Applied for Programme</fullName>
            </value>
            <value>
                <fullName>Mentorship Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <description>This record type will be selected when a Mentor comes on platform for mentoring purpose</description>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>This record type will be selected when a Student wants to get mentoring for a particular course</description>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Payment_Order__c.field-meta.xml
<CustomField>
    <fullName>Payment_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Order</label>
    <referenceTo>Payment_Order__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Payment_Order__c.field-meta.xml
<CustomField>
    <fullName>Payment_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Order</label>
    <referenceTo>Payment_Order__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Order__c/fields/Paid_By__c.field-meta.xml
<CustomField>
    <fullName>Paid_By__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Paid By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Orders</relationshipLabel>
    <relationshipName>Payment_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>ABORTED</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Course_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Enrollment</label>
    <referenceTo>Course_Enrollment__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Test_Master__c.field-meta.xml
<CustomField>
    <fullName>Test_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Master</label>
    <referenceTo>Test_Master__c</referenceTo>
    <relationshipLabel>Student Test Associations</relationshipLabel>
    <relationshipName>Student_Test_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Test_Association__c/fields/Test_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Type__c</fullName>
    <formula>TEXT( Test_Master__r.Test_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Master__c/fields/Test_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Type__c</fullName>
    <label>Test Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactTrigger_Helper.cls
public class ContactTrigger_Helper {
    // send email to mentor on first time singup i.e. contact creation
    public static void sendWelcomeEmail(Map<id, Contact> newContactMap){
        //System.debug('Contact Trigger Sending mail');
        set<id> mentorsContactIds = new set<id>();
        for(Contact con : newContactMap.values()){
            // when singup as mentor
            if(con.Email != null && con.Registered_By__c == 'Mentor'){
                mentorsContactIds.add(con.Id);
            }
        }
        if(!mentorsContactIds.isEmpty()){
            EmailHepler.sendWelcomeEmailNotification('Welcome Email For Mentor', mentorsContactIds);
        }
    } 
    public static void deleteFbAcc(Map<id, Contact> oldContactMap){
        //system.debug('oldContactMap Contact Map Before Deletion::'+oldContactMap);
        
        set<String> deletedConFBId = new Set<String>();
        for(Contact con : oldContactMap.values()){
            if(con.Firebase_Id__c != null){
                deletedConFBId.add(con.Firebase_Id__c);
            }
        }
        //system.debug('deletedConFBId::'+deletedConFBId);
        if(!deletedConFBId.isEmpty()){
            FirebaseDeleteAccount.deleteDocFromFB(deletedConFBId);
        }
    }
    public static void deletePaymentSTAOpportunity(Map<id, Contact> oldContactMap){
        //system.debug('oldContactMap Contact Map Before Deletion::'+oldContactMap);
        set<String> deletedConId = new Set<String>();
        List<Payment_Order__c> paymentOrderToBeDeleted = new List<Payment_Order__c>();            
        List<Student_Test_Association__c> STAToBeDeleted = new List<Student_Test_Association__c>();      
        List<Opportunity> OpportunityToBeDeleted = new List<Opportunity>();      
        List<Course_Enrollment__c> CEToBeDeleted = new List<Course_Enrollment__c>();      
        
        for(Contact con : oldContactMap.values()){
            if(con.Registered_By__c == 'Student'){
                deletedConId.add(con.Id);
            }
        }
        //system.debug('deletedConId::'+deletedConId);
        if(!deletedConId.isEmpty()){
            paymentOrderToBeDeleted = [SELECT Id FROM Payment_Order__c WHERE Paid_By__c in : deletedConId];
            STAToBeDeleted = [SELECT Id FROM Student_Test_Association__c WHERE Contact__c in : deletedConId];
            OpportunityToBeDeleted = [SELECT Id FROM Opportunity WHERE ContactId  in : deletedConId];
            CEToBeDeleted = [SELECT Id FROM Course_Enrollment__c WHERE Contact__c in : deletedConId];
            
            if(!paymentOrderToBeDeleted.isEmpty()){
                delete paymentOrderToBeDeleted;
            }
            if(!STAToBeDeleted.isEmpty()){
                delete STAToBeDeleted;
            }
            if(!OpportunityToBeDeleted.isEmpty()){
                delete OpportunityToBeDeleted;
            }
            if(!CEToBeDeleted.isEmpty()){
                delete CEToBeDeleted;
            }
            
        }
    }
    //insert STA record for generic test before enrollment of Student in any Course
    public static void insertSTAForGenericTest(Map<id, Contact> newContactMap){
        set<id> studentsContactIds = new set<id>();
        List<Test_Master__c> testMasterList = new List<Test_Master__c>();
        List<Student_Test_Association__c> STAtoBeInserted = new List<Student_Test_Association__c>();
        
        testMasterList = [Select Id From Test_Master__c Where Test_Type__c = : Constants.GENERIC_TEST_MASTER];
        
        for(Contact con : newContactMap.values()){
            // when singup as student
            if(con.Email != null && con.Registered_By__c == 'Student'){
                studentsContactIds.add(con.Id);
            }
        }
        if(!studentsContactIds.isEmpty()){
            for(Id studentId : studentsContactIds){
                Student_Test_Association__c staRec = new Student_Test_Association__c();
                staRec.Contact__c = studentId;
                staRec.Test_Master__c = testMasterList[0].Id;
                staRec.Status__c = Constants.STA_STATUS_PENDING;
                STAtoBeInserted.add(staRec);                    
            }
            if(!STAtoBeInserted.isEmpty()){
                insert STAtoBeInserted;
            }
            
        }
    } 
    public static void insertContactDetailsOnFB(Map<Id, Contact> newMap){
        system.debug('newMap:'+newMap);
        
        for(Contact conRec : newMap.values()){
            if(conRec.Email != null && conRec.Firebase_Id__c == null && conRec.Push_To_FB__c == true){
                system.debug('conRec::'+conRec);
                CreateUserOnFBAsyncCall.userCreation(conRec.email, conRec.firstName+'@12345');
            }
        }
    }
   /* public static void updateSinglePrimaryConUnderAccount(Map<Id, Contact> newMap, Map<Id, Contact> oldMap){
        system.debug('Before Update trigger Method');
        Set<Id> accountIds = new Set<Id>();
        system.debug('newMap::'+newMap);
        system.debug('oldMap::'+oldMap);
        List<Contact> contactsListUnderAccount = new List<Contact>();
        for(Contact conRec : newMap.values()){
            if(conRec.Primary_Contact__c == true && conRec.AccountId != null){
                accountIds.add(conRec.AccountId);
            }
        }
        if(!accountIds.isEmpty()){
            contactsListUnderAccount = [Select Id,Primary_Contact__c,AccountId From Contact Where AccountId in : accountIds];
        }
        
    } */
}