force-app/main/default/objects/Contact/fields/Initials__c.field-meta.xml
<CustomField>
    <fullName>Initials__c</fullName>
    <formula>LEFT(FirstName, 1)+&apos;.&apos;+LEFT(LastName, 1)</formula>
    <label>Initials</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newly created</fullName>
            </value>
            <value>
                <fullName>Applied for Programme</fullName>
            </value>
            <value>
                <fullName>Mentorship Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Applied_by__c.field-meta.xml
<CustomField>
    <fullName>Applied_by__c</fullName>
    <formula>Contact__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applied by</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Master_Name__c</fullName>
    <formula>Course_Master__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Master Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Enrollment_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Enrollment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Payment_Order__c.field-meta.xml
<CustomField>
    <fullName>Payment_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Order</label>
    <referenceTo>Payment_Order__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Order__c/fields/Amount_without_Tax__c.field-meta.xml
<CustomField>
    <fullName>Amount_without_Tax__c</fullName>
    <formula>Amount__c - Amount__c*(18/100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount without Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Order__c/fields/Gateway__c.field-meta.xml
<CustomField>
    <fullName>Gateway__c</fullName>
    <label>Gateway</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Razor Pay</fullName>
            </value>
            <value>
                <fullName>Stripe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Order__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <externalId>true</externalId>
    <label>Order Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Order__c/fields/Paid_By__c.field-meta.xml
<CustomField>
    <fullName>Paid_By__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Paid By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Orders</relationshipLabel>
    <relationshipName>Payment_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Order__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <formula>TEXT( TODAY() )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>ABORTED</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Order__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <label>Transaction Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentInvoice.cls
global class PaymentInvoice {
    global String currentRecordId {get; set;}
    public Course_Enrollment__c paidByRecord {get; set;}
    public string companyName  {get; set;}
    public string companyAddress {get; set;}
    public string phone {get; set;}
    public string companyPAN {get; set;}
    public string companyTAN {get; set;}
    public string GST {get; set;}
    public string accountNumber {get; set;}
    public string bankName {get; set;}
    public string bankIFSCCode {get; set;}
    public string bankSwiftCode {get; set;}
    global PaymentInvoice(){
        companyName =System.Label.Company_Name;// 'CODE GLADIATORS PVT LTD';
        companyAddress = System.Label.Company_Address;//'First Floor, No. 23 19th Cross, 24th,Main JP Nagar, 5th StageBengaluru 560078';
        phone = System.Label.Phone;//'+91 9910770310'; 
        companyPAN = System.Label.Company_PAN;//'AACCU5285G' ;
        companyTAN = System.Label.Company_TAN;//'RTKU02062E';
        GST = System.Label.GST;//'06AACCU5285G1Z7' ;
        accountNumber = System.Label.Account_Number;//'235805000614' ;
        bankName = System.Label.Bank_Name;//'ICICI' ;
        bankIFSCCode = System.Label.bank_IFSCCode;//'ICIC0002358' ;
        bankSwiftCode = System.Label.Bank_Swift_Code;//'ICICINBB' ; 
        currentRecordId =  ApexPages.CurrentPage().getparameters().get('id');
        system.debug('currentRecordId===>'+currentRecordId);
        paidByRecord = [Select Applied_by__c,Contact__c,Course_Master_Name__c,Enrollment_Date__c,Mentor__c,Payment_Order__c,
                        Payment_Order__r.Amount__c,Payment_Order__r.Amount_without_Tax__c,Payment_Order__r.Gateway__c,Payment_Order__r.Name,Payment_Order__r.Payment_Date__c,Payment_Order__r.Paid_By__c,Payment_Order__r.Status__c,Payment_Order__r.Transaction_Id__c,Payment_Order__r.Order_Id__c,
                        Contact__r.Name,Contact__r.Email,Contact__r.Phone,Name  From Course_Enrollment__c where id =: currentRecordId];
        // system.debug('paidByRecord::'+paidByRecord);
        
    }
    @future(callout=true)
    global static void attachPDF(string paymentOrderId) {
        //system.debug('paymentOrderId::'+paymentOrderId);
        List<Course_Enrollment__c> enrollmentList = [Select Id,Contact__c From Course_Enrollment__c where Payment_Order__c =: paymentOrderId];
        //system.debug('enrollmentList::'+enrollmentList);
        Payment_Order__c paymentOrderrec = [SELECT Amount__c,Order_Id__c,Paid_By__r.FirstName,Paid_By__r.LastName,Paid_By__r.Email,Status__c,Id,Paid_By__r.Initials__c FROM Payment_Order__c Where id =: paymentOrderId limit 1];
        //system.debug('paymentOrderrec::'+paymentOrderrec);
        //generate and attach the PDF document
        PageReference pdfPage = Page.PaymentInvoicePage;
        if(!enrollmentList.isEmpty()){
            pdfPage.getParameters().put('id',enrollmentList[0].Id);
        }
        
        Blob pdfBlob; //create a blob for the PDF content
        //pdfBlob = pdfPage.getContent(); //generate the pdf blob
        if(Test.isRunningTest()){
            pdfBlob = blob.valueof('TEST');
        }else{
            pdfBlob = pdfPage.getContent(); 
        }
        Attachment attach = new Attachment(parentId = paymentOrderrec.Id, Name = 'Pay-Order-'+paymentOrderrec.Paid_By__r.Initials__c+'.pdf', body = pdfBlob); //create the attachment object
        insert attach;
        EmailHepler.sendPaymentConfirmationEmailNotification('Successful Payment Done', paymentOrderId);
    }    
}