force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newly created</fullName>
            </value>
            <value>
                <fullName>Applied for Programme</fullName>
            </value>
            <value>
                <fullName>Mentorship Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>This record type will be selected when a Student wants to get mentoring for a particular course</description>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/fields/Applied_by__c.field-meta.xml
<CustomField>
    <fullName>Applied_by__c</fullName>
    <formula>Contact__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applied by</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested by Mentor</fullName>
            </value>
            <value>
                <fullName>Requested by Student</fullName>
            </value>
            <value>
                <fullName>Allocated for Mentoring</fullName>
            </value>
            <value>
                <fullName>Student Allocated</fullName>
            </value>
            <value>
                <fullName>Course in Progress</fullName>
            </value>
            <value>
                <fullName>Course Completed</fullName>
            </value>
            <value>
                <fullName>Sessions Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/Course_Master__c/fields/Paid_Course__c.field-meta.xml
<CustomField>
    <fullName>Paid_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchForCoolingPeriod.cls
public class BatchForCoolingPeriod implements Database.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext BC){
    List<Course_Enrollment__c> ce = [SELECT Contact__c,Contact__r.Email,Contact__r.Name,Status__c FROM Course_Enrollment__c WHERE Status__c = 'Allocated for Mentoring' AND Applied_by__c = 'Student' ];
        //system.debug('ce::'+ce);
        return Database.getQueryLocator([SELECT Contact__c,Contact__r.Email,Contact__r.Name,Status__c FROM Course_Enrollment__c WHERE Status__c = 'Allocated for Mentoring' AND Applied_by__c = 'Student' ]);
    }
    
    public void execute(Database.BatchableContext BC, List<Course_Enrollment__c> courseEnrollmentList){
        
        List<Course_Master__c> coursemasterList = [SELECT Id,Paid_Course__c,Name FROM Course_Master__c Where Paid_Course__c = False limit 2];
        List<Messaging.SingleEmailMessage> mails =  new List<Messaging.SingleEmailMessage>();     
        
        EmailTemplate emailTemplateRec = [Select id, Name, DeveloperName, Subject, Body, HtmlValue from EmailTemplate where Name =: 'Cooling Period Mail'];
        if(!courseEnrollmentList.isEmpty()){
            for (Course_Enrollment__c courseEnrolled : courseEnrollmentList) {
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                
                List<String> recipients = new List<String>();
                recipients.add(courseEnrolled.Contact__r.Email);
                //system.debug('recipients------'+recipients);
                mail.setToAddresses(recipients);
                mail.setSenderDisplayName('Utilitarian Labs');
                
                String htmlBody = emailTemplateRec.HtmlValue;
                
                htmlBody = htmlBody.replace('{!Contact.Name}', courseEnrolled.Contact__r.Name);
                integer i = 1;
                for(Course_Master__c courseMaster : coursemasterList){
                    htmlBody = htmlBody.replace('{!Course'+i+'.Name}', courseMaster.Name);
                    i++;
                }
                
                //system.debug('htmlBody==>'+htmlBody);
                mail.setSubject(emailTemplateRec.Subject);
                mail.setHtmlBody(htmlBody);
                mails.add(mail);
                
            }
        }
        //system.debug('mails:::'+mails);
        if(!mails.isEmpty()){
            Messaging.sendEmail(mails);       
        }
    }
    
    public void finish(Database.BatchableContext BC){
    }
}