force-app/main/default/objects/Payment_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>ABORTED</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentOrderTriggerHelper.cls
public class PaymentOrderTriggerHelper {
    public static void notifyStudentAboutPayment(map<id, Payment_Order__c> paymentOrderMap){
        set<id> paymentOrderIds = new set<id>();
        
        for(Payment_Order__c paymentOrder : paymentOrderMap.values()){
            if(paymentOrder.Status__c == 'SUCCESS'){
                paymentOrderIds.add(paymentOrder.Id); 
            }
        }
        //system.debug('paymentOrderIds::'+paymentOrderIds);
        if(!paymentOrderIds.isEmpty()){
            for(Id pamentRecId  : paymentOrderIds){
                //system.debug('pamentRecId::'+pamentRecId);
                PaymentInvoice.attachPDF(pamentRecId);
            } 
        }
    }
}