force-app/main/default/objects/Contact/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <description>This record type will be selected when a Mentor comes on platform for mentoring purpose</description>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Course_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Enrollments</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Course_Master_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Master_Name__c</fullName>
    <formula>Course_Master__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Master Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mentees</relationshipLabel>
    <relationshipName>Mentees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrollment__c/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <label>Mentor</label>
</RecordType>

force-app/main/default/classes/SendScheduleCSSessionsPdfToMenteeHelper.cls
public class SendScheduleCSSessionsPdfToMenteeHelper {
    @auraEnabled
    public static void sendEmailNotification(String courseEnrollmentId){
        //system.debug('courseEnrollmentId::'+courseEnrollmentId);
        
        List<Messaging.SingleEmailMessage> mails =  new List<Messaging.SingleEmailMessage>();     
        List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();
        Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
        Attachment attachment = new Attachment();
       	
        if(courseEnrollmentId != null){
            attachment = [SELECT Body,BodyLength,ContentType,Id,Name,ParentId FROM Attachment WHERE ParentId =: courseEnrollmentId ];
        }
        //system.debug('attachment::'+attachment);
        
        string mentorId = [SELECT Contact__c FROM Course_Enrollment__c WHERE Id =: courseEnrollmentId].Contact__c;
        //system.debug('mentorId::'+mentorId);
        string courseMasterId = [SELECT Course_Master__c  FROM Course_Enrollment__c WHERE Id =: courseEnrollmentId].Course_Master__c ;
        //system.debug('courseMasterId::'+courseMasterId);
        List<Course_Enrollment__c> courseEnrollmentsByStudent = [SELECT Contact__r.Name, Contact__r.Email,Mentor__r.Name,Mentor__r.Email,Course_Master_Name__c FROM Course_Enrollment__c WHERE Mentor__c =: mentorId And Course_Master__c =: courseMasterId limit 10];
        //system.debug('courseEnrollmentsByStudent::'+courseEnrollmentsByStudent);
      
        if(attachment != null ){
            EmailTemplate emailTemplateRec = [Select id, Name, DeveloperName, Subject, Body, HtmlValue from EmailTemplate where Name =: 'Send Scheduled CESessions Pdf'];
            
            if(!courseEnrollmentsByStudent.isEmpty()){
                for (Course_Enrollment__c courseEnrollment : courseEnrollmentsByStudent) {
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                  
                        efa.setFileName(attachment.Name);
                        efa.setBody(attachment.Body);
                        efa.setContentType(attachment.ContentType);
                        attachments.add(efa);
                        
                    
                    List<String> recipients = new List<String>();
                    recipients.add(courseEnrollment.Contact__r.Email);
                    //system.debug('recipients------'+recipients);
                    mail.setToAddresses(recipients);
                    mail.setSenderDisplayName('Utilitarian Labs');
                    
                    String htmlBody = emailTemplateRec.HtmlValue;
                    
                    htmlBody = htmlBody.replace('{!Contact.Name}',courseEnrollment.Contact__r.Name);
                    htmlBody = htmlBody.replace('{!Course.name}',courseEnrollment.Course_Master_Name__c);
                    htmlBody = htmlBody.replace('{!Mentor.Name}',courseEnrollment.Mentor__r.Name);
                    htmlBody = htmlBody.replace('{!Mentor.Email}',courseEnrollment.Mentor__r.Email);
                    
                    if(attachments != null){
                        mail.setFileAttachments(attachments);
                    }
                    mail.setSubject(emailTemplateRec.Subject);
                    mail.setHtmlBody(htmlBody);
                    mails.add(mail);
                 }
            }
            //system.debug('mails:::'+mails);
            if(!mails.isEmpty()){
                Messaging.sendEmail(mails);  
            }
        }
    }
}